/**
 * apps/api/src/routes/deals/deal-core.routes.ts
 * registerDealCoreRoutes — extracted from deals.ts (PR12)
 * AUTO-GENERATED by scripts/dev/split-deals-final.py
 */
import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import { fetchPhaseBVisualsFromDb } from "../../lib/phaseb-visuals";
import { getUploadsRootDir } from "../../plugins/uploads-static";
import { getPool } from "../../lib/db";
import { resolveVisualAssetImageUriForApi } from "../../lib/visual-asset-image-uri";
import type { Deal } from "@dealdecision/contracts";
import type { JobStatus, JobType } from "@dealdecision/contracts";
import { QUEUE_NAMES } from "@dealdecision/core";
import { enqueueBullmqJob, enqueueJob, insertJobRow } from "../../services/jobs";
import { getQueues } from "../../lib/queue";
import { runIdempotentOperation } from "../../lib/jobs";
import { getStorageDriver } from "../../lib/storage-contract";
import { autoProgressDealStage } from "../../services/stageProgression";
import { updateDealPriority, updateAllDealPriorities } from "../../services/priorityClassification";
import { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";
import { getNodeEvidenceGateForDeal } from "../../services/nodeEvidenceGateForDeal";
import { normalizeDealName } from "../../lib/normalize-deal-name";
import { buildDocumentsDigest } from "../../lib/documents-digest";
import type { DocumentsDigestV1 } from "../../lib/documents-digest";
import { objectExistsInR2 } from "../../lib/r2";
import { writePlatformAuditLog, getAuditActorContext, extractAuditReason } from "../../lib/platform-audit-log";
import {
  purgeDealCascade,
  isPurgeDealNotFoundError,
  sanitizeText,
  getDocumentCapabilities,
  buildDealScoringInputV0FromLineage,
  getSegmentConfidenceThresholds,
  detectContentArchetypeTags,
  buildOrchestratorReportV1,
  buildDealDeepDiveV1,
} from "@dealdecision/core";
import {
  BrandModel,
  PageInput,
  buildBrandModel,
  inferDocumentBrandName,
  inferSlideTitleForSlide,
  isLikelyGarbledSlideTitle,
  normalizePhrase,
} from "../../lib/slide-title";
import {
  buildClassificationText,
  buildSegmentFeatures,
  classifySegment,
  normalizeAnalystSegment,
  type AnalystSegment,
  type SegmentClassifierInput,
} from "../../lib/analyst-segment";
import {
  groupWordVisualAssetsByDocument,
  groupWordVisualAssetsByDocumentWithStats,
  type WordGroupingStats,
} from "../../lib/word-visual-grouping";
import { fetchPageUnderstandingReadinessForDeal } from "../../lib/deal-page-understanding-readiness";
import { ensureDocumentsReadyForAnalysis } from "../../lib/ensure-documents-ready-for-analysis";
import { getCanonicalFieldsForAI } from "../../lib/canonical-fields-for-ai";
import type {
  QueryResult,
  DealRoutesPool,
  DealRoutesClient,
  DealApiMode,
  AutoProfileDocRow,
  DealRow,
  DIOAggregateRow,
  ScoreBreakdownSectionKey,
  EvidenceRow,
  StatusSummaryAnalysis,
  StatusSummaryReport,
  StatusSummaryEvidenceGate,
  StatusSummary,
} from "./_shared";
import {
  hasTable,
  hasColumn,
  getColumnDataType,
  isUuid,
  stripEvidenceFromExecutiveSummary,
  stripEvidenceFromClaims,
  parseDealApiMode,
  bestEffortReadinessJobPresenceCheck,
  parseBoolQ,
  computeOcrV2CleanText,
  pickNonUnknownSegment,
  majorityNonUnknownSegment,
  isStructuredWordSectionAsset,
  structuredWordContentStats,
  isEmptyStructuredWordSectionAsset,
  computeDocHintSegmentByDocId,
  applyNeighborHintPropagationToAssets,
  buildDeterministicGroupCapturedText,
  extractStructuredWordTextForCue,
  inferStructuredWordCueSegment,
  requireDestructiveAuth,
  requirePurgeAuth,
  buildPurgeConfirmationToken,
  requirePurgeConfirmation,
  dealStageEnum,
  dealPriorityEnum,
  normalizeDealTrend,
  dealTrendEnum,
  dealCreateSchema,
  dealDraftCreateSchema,
  dealConfirmProfileSchema,
  sanitizeProfileValue,
  extractLabeledValue,
  isGenericCandidateName,
  deriveNameFromFilenameLike,
  extractCompanyFromEarlyText,
  computeAutoProfileFromDocuments,
  normalizeWarningsForPersistence,
  jsonbParam,
  dealUpdateSchema,
  llmPhaseModeEnum,
  parseNullableNumber,
  SCORE_BREAKDOWN_SECTION_ORDER,
  CLAIM_CATEGORY_SECTION_MAP,
  normalizeCategory,
  sectionForCategory,
  buildScoreBreakdownV1,
  collectEvidenceIdsFromClaims,
  getEvidenceByIds,
  getDocumentIndex,
  fetchEvidenceSamplesBySection,
  normalizeEvidenceSnippet,
  BUSINESS_MODEL_STRONG_REGEX,
  deriveSectionKeyFromClaim,
  ensureEvidenceLinksForClaims,
  buildPhase1ScoreEvidence,
  buildScoreEvidenceFromBreakdown,
  mapDeal,
  safeJsonValue,
  ocrSnippet,
  deriveStructuredSummary,
  cueRescueLowSignal,
  deriveBestExtractionConfidence,
  mapAnalysisJobStatus,
  mapReportRowStatus,
  maxIsoTs,
  buildStatusSummary,
} from "./_shared";

export async function registerDealCoreRoutes(
  app: FastifyInstance,
  pool: DealRoutesPool,
  enqueue: typeof enqueueJob,
  r2: { objectExistsInR2: typeof objectExistsInR2 },
  debugRoutesEnabled: boolean,
  deps?: {
    enqueueJob?: typeof enqueueJob;
    jobs?: { queue?: any };
    r2?: { objectExistsInR2?: typeof objectExistsInR2 };
    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };
  }
): Promise<void> {
  app.get("/api/v1/deals", async (request, reply) => {
    const mode = parseDealApiMode(request);
    const lifecycleRaw = typeof (request.query as any)?.lifecycle === "string"
      ? String((request.query as any).lifecycle).trim().toLowerCase()
      : "active";
    const lifecycleFilter = lifecycleRaw === "all" || lifecycleRaw === "archived" || lifecycleRaw === "active"
      ? lifecycleRaw
      : null;
    if (!lifecycleFilter) {
      return reply.status(400).send({ error: "Invalid lifecycle filter. Expected one of: active, archived, all" });
    }

    const hasLifecycleStatus = await hasColumn(pool, "deals", "lifecycle_status");
    const hasDealOrgId = await hasColumn(pool, "deals", "org_id");
    if (!hasLifecycleStatus && lifecycleFilter === "archived") {
      return [];
    }

    const userId = (request as any)?.auth?.userId;
    const orgId = (request as any)?.auth?.orgId;
    const bypassAuthEnvRaw = typeof process.env.DISABLE_CLERK_AUTH === "string" ? process.env.DISABLE_CLERK_AUTH : "";
    const bypassAuthEnv = ["1", "true", "yes", "on"].includes(bypassAuthEnvRaw.trim().toLowerCase());
    const bypassAuth = Boolean((request as any)?.auth?.claims?.bypass_auth) || bypassAuthEnv;
    const hasUserId = !bypassAuth && typeof userId === "string" && userId.trim().length > 0;
    const hasOrgScope = !bypassAuth && hasDealOrgId && typeof orgId === "string" && orgId.trim().length > 0;
    const whereClauses = ["d.deleted_at IS NULL"];
    const params: any[] = [];

    if (hasOrgScope && hasUserId) {
      params.push(userId);
      const userIdx = params.length;
      params.push(orgId.trim());
      const orgIdx = params.length;
      // Hybrid access: always include a user's own deals, plus org-associated deals.
      // This prevents empty pipelines when org linkage lags behind deal creation.
      whereClauses.push(`(d.created_by_user_id = $${userIdx} OR d.org_id = $${orgIdx})`);
    } else if (hasOrgScope) {
      params.push(orgId.trim());
      const i = params.length;
      whereClauses.push(`d.org_id = $${i}`);
    } else if (hasUserId) {
      params.push(userId);
      const i = params.length;
      whereClauses.push(`(d.created_by_user_id = $${i} OR d.created_by_user_id IS NULL)`);
    }

    if (hasLifecycleStatus && lifecycleFilter !== "all") {
      if (lifecycleFilter === "active") {
        // Draft deals are in-progress user-created deals — include them in the active pipeline so
        // newly created deals (which start as 'draft') are immediately visible.
        whereClauses.push(`COALESCE(d.lifecycle_status, 'active') IN ('active', 'draft')`);
      } else {
        params.push(lifecycleFilter);
        const i = params.length;
        whereClauses.push(`COALESCE(d.lifecycle_status, 'active') = $${i}`);
      }
    }

    const { rows } = await pool.query<DealRow & {
      dio_id: string | null;
      analysis_version: number | null;
      recommendation: string | null;
      overall_score: number | null;
      overall_score_resolved: number | null;
      last_analyzed_at: string | null;
      run_count: number | null;
		selected_policy: string | null;
		policy_id: string | null;
		deal_classification_v1: any | null;
		executive_summary_v1: any | null;
		executive_summary_v2: any | null;
		decision_summary_v1: any | null;
		phase1_coverage: any | null;
		phase1_business_archetype_v1: any | null;
		phase1_deal_overview_v2: any | null;
		phase1_update_report_v1: any | null;
		analysis_foundation_spec_version: string | null;
		phase_inference_v1: any | null;
		fundability_assessment_v1: any | null;
		fundability_decision_v1: any | null;
		phase_b_latest_run: any | null;
    phase_b_history: any | null;
    canonical_decision_v1: any | null;
    }>(
      `SELECT d.*,
              latest.dio_id,
              latest.analysis_version,
              latest.recommendation,
              latest.overall_score,
              latest.overall_score_resolved,
              latest.updated_at as last_analyzed_at,
          latest.selected_policy,
          latest.policy_id,
          latest.deal_classification_v1,
				  latest.executive_summary_v1,
				  latest.executive_summary_v2,
				  latest.decision_summary_v1,
				  latest.deal_overview_v2 as phase1_deal_overview_v2,
				  latest.update_report_v1 as phase1_update_report_v1,
				  latest.phase1_coverage,
				  latest.analysis_foundation_spec_version,
				  latest.phase_inference_v1,
				  latest.fundability_assessment_v1,
				  latest.fundability_decision_v1,
              phaseb.phase_b_latest_run,
    					phaseb.phase_b_history,
              stats.run_count,
              iir.canonical_decision_v1
         FROM deals d
         LEFT JOIN LATERAL (
           SELECT dio_id,
                  analysis_version,
                  recommendation,
                  overall_score,
                  COALESCE(
                    overall_score,
                    NULLIF((dio_data #>> '{overall_score}'), '')::double precision,
                    NULLIF((dio_data #>> '{score_explanation,totals,overall_score}'), '')::double precision
                  ) AS overall_score_resolved,
				  NULLIF((dio_data #>> '{dio,deal_classification_v1,selected_policy}'), '') AS selected_policy,
				  NULLIF((dio_data #>> '{dio,deal_classification_v1,selected_policy}'), '') AS policy_id,
				  (dio_data #> '{dio,deal_classification_v1}') AS deal_classification_v1,
                  updated_at,
					  (dio_data #> '{dio,phase1,executive_summary_v1}') AS executive_summary_v1
					, (dio_data #> '{dio,phase1,executive_summary_v2}') AS executive_summary_v2
  					, (dio_data #> '{dio,phase1,decision_summary_v1}') AS decision_summary_v1
					, (dio_data #> '{dio,phase1,coverage}') AS phase1_coverage
          , (dio_data #> '{dio,phase1,business_archetype_v1}') AS phase1_business_archetype_v1
					, (dio_data #> '{dio,phase1,deal_overview_v2}') AS deal_overview_v2
					, (dio_data #> '{dio,phase1,update_report_v1}') AS update_report_v1
            , (dio_data #> '{dio,phase1,deal_summary_v2}') AS deal_summary_v2
					, (dio_data #>> '{dio,spec_versions,analysis_foundation}') AS analysis_foundation_spec_version
					, (dio_data #> '{dio,phase_inference_v1}') AS phase_inference_v1
					, (dio_data #> '{dio,fundability_assessment_v1}') AS fundability_assessment_v1
					, (dio_data #> '{dio,fundability_decision_v1}') AS fundability_decision_v1
             FROM deal_intelligence_objects
            WHERE deal_id = d.id
            ORDER BY analysis_version DESC
            LIMIT 1
         ) latest ON TRUE
         LEFT JOIN LATERAL (
           SELECT jsonb_build_object(
                    'id', id,
                    'deal_id', deal_id,
                    'version', version,
                    'phase_b_result', phase_b_result,
                    'phase_b_features', phase_b_features,
                    'source_run_id', source_run_id,
               'created_at', created_at
             ) AS phase_b_latest_run,
             (
             	SELECT jsonb_agg(run ORDER BY (run ->> 'created_at')::timestamptz DESC NULLS LAST)
             	FROM (
             		SELECT jsonb_build_object(
             			'id', id,
             			'deal_id', deal_id,
             			'version', version,
             			'phase_b_result', phase_b_result,
             			'phase_b_features', phase_b_features,
             			'source_run_id', source_run_id,
             			'created_at', created_at
             		) AS run
             		FROM deal_phase_b_runs
             		WHERE deal_id = d.id
             		ORDER BY COALESCE(
             			created_at,
             			NULLIF((phase_b_features ->> 'computed_at'), '')::timestamptz,
             			'1970-01-01'::timestamptz
             		) DESC,
             		version DESC,
             		id DESC
             		LIMIT 3
             	) t(run)
             ) AS phase_b_history
             FROM deal_phase_b_runs
            WHERE deal_id = d.id
            ORDER BY COALESCE(
              created_at,
              NULLIF((phase_b_features ->> 'computed_at'), '')::timestamptz,
              '1970-01-01'::timestamptz
            ) DESC,
            version DESC,
            id DESC
            LIMIT 1
         ) phaseb ON TRUE
         LEFT JOIN LATERAL (
           SELECT COUNT(*)::int AS run_count
             FROM deal_intelligence_objects
            WHERE deal_id = d.id
         ) stats ON TRUE
         LEFT JOIN LATERAL (
           SELECT (report_payload -> 'canonical_decision_v1') AS canonical_decision_v1
             FROM investor_insight_reports
            WHERE deal_id = d.id
            ORDER BY updated_at DESC
            LIMIT 1
         ) iir ON TRUE
        WHERE ${whereClauses.join(" AND ")}
        ORDER BY d.created_at DESC`,
      params
    );
    return rows.map((row) => mapDeal(row, {
      dio_id: row.dio_id,
      analysis_version: row.analysis_version,
      recommendation: row.recommendation,
      overall_score: parseNullableNumber((row as any).overall_score_resolved) ?? row.overall_score,
      last_analyzed_at: row.last_analyzed_at,
      run_count: row.run_count,
    selected_policy: (row as any).selected_policy ?? null,
    policy_id: (row as any).policy_id ?? null,
    deal_classification_v1: (row as any).deal_classification_v1 ?? null,
		executive_summary_v1: row.executive_summary_v1,
    executive_summary_v2: row.executive_summary_v2,
		decision_summary_v1: row.decision_summary_v1,
		phase1_coverage: row.phase1_coverage,
		phase1_business_archetype_v1: (row as any).phase1_business_archetype_v1,
    phase1_deal_overview_v2: row.phase1_deal_overview_v2,
    phase1_update_report_v1: row.phase1_update_report_v1,
		phase1_deal_summary_v2: (row as any).deal_summary_v2,
		analysis_foundation_spec_version: row.analysis_foundation_spec_version,
		phase_inference_v1: row.phase_inference_v1,
		fundability_assessment_v1: row.fundability_assessment_v1,
		fundability_decision_v1: row.fundability_decision_v1,
    phase1_claims: null,
    phase_b_latest_run: (row as any).phase_b_latest_run,
		phase_b_history: (row as any).phase_b_history,
    canonical_decision_v1: (row as any).canonical_decision_v1 ?? null,
    }, mode));
  });

  app.get("/api/v1/deals/:deal_id", async (request, reply) => {
    const startTs = Date.now();
    const dealId = (request.params as { deal_id: string }).deal_id;
    request.log.info({ msg: "deal.detail.start", deal_id: dealId, start_ts: new Date(startTs).toISOString() });
    const mode = parseDealApiMode(request);
    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );
    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const deal = rows[0];

        try {
          deal.documents_digest_v1 = await buildDocumentsDigest({ dealId, pool });
        } catch (err: any) {
          request.log.warn({ err, deal_id: dealId }, "documents_digest_v1.failed");
        }

    const { rows: latestDioRows } = await pool.query<{
      dio_id: string;
      analysis_version: number | null;
      recommendation: string | null;
      overall_score: number | null;
      dio_data: any;
      updated_at: string | null;
    }>(
      `SELECT dio_id, analysis_version, recommendation, overall_score, dio_data, updated_at
         FROM deal_intelligence_objects
        WHERE deal_id = $1
        ORDER BY analysis_version DESC
        LIMIT 1`,
      [dealId]
    );

    const { rows: dioStatsRows } = await pool.query<{ run_count: number | null; last_analyzed_at: string | null }>(
      `SELECT COUNT(*)::int AS run_count, MAX(updated_at) AS last_analyzed_at
         FROM deal_intelligence_objects
        WHERE deal_id = $1`,
      [dealId]
    );

    const { rows: phaseBRows } = await pool.query<{
      id: string;
      deal_id: string;
      version: number | null;
      phase_b_result: any;
      phase_b_features: any;
      source_run_id: string | null;
      created_at: string | null;
    }>(
      `SELECT id, deal_id, version, phase_b_result, phase_b_features, source_run_id, created_at
         FROM deal_phase_b_runs
        WHERE deal_id = $1
        ORDER BY COALESCE(
          created_at,
          NULLIF((phase_b_features ->> 'computed_at'), '')::timestamptz,
          '1970-01-01'::timestamptz
        ) DESC,
        version DESC,
        id DESC
        LIMIT 3`,
      [dealId]
    );

    const { rows: iirCanonicalRows } = await pool.query<{ canonical_decision_v1: any | null }>(
      `SELECT (report_payload -> 'canonical_decision_v1') AS canonical_decision_v1
         FROM investor_insight_reports
        WHERE deal_id = $1
        ORDER BY updated_at DESC
        LIMIT 1`,
      [dealId]
    );

    const dioRows: Array<DIOAggregateRow & { overall_score_resolved?: any }> = [];
    if (latestDioRows[0]) {
      const latest = latestDioRows[0];
      const dioData = (latest as any).dio_data ?? {};
      const overallScoreResolved =
        parseNullableNumber(latest.overall_score) ??
        parseNullableNumber((dioData as any)?.overall_score) ??
        parseNullableNumber((dioData as any)?.score_explanation?.totals?.overall_score);

      const phaseBLatest = phaseBRows[0]
        ? {
          id: phaseBRows[0].id,
          deal_id: phaseBRows[0].deal_id,
          version: phaseBRows[0].version,
          phase_b_result: phaseBRows[0].phase_b_result,
          phase_b_features: phaseBRows[0].phase_b_features,
          source_run_id: phaseBRows[0].source_run_id,
          created_at: phaseBRows[0].created_at,
        }
        : null;

      const phaseBHistory = phaseBRows.map((r) => ({
        id: r.id,
        deal_id: r.deal_id,
        version: r.version,
        phase_b_result: r.phase_b_result,
        phase_b_features: r.phase_b_features,
        source_run_id: r.source_run_id,
        created_at: r.created_at,
      }));

      dioRows.push({
        dio_id: (latest as any).dio_id,
        analysis_version: latest.analysis_version,
        recommendation: latest.recommendation,
        overall_score: latest.overall_score,
        overall_score_resolved: overallScoreResolved,
    selected_policy: (dioData as any)?.dio?.deal_classification_v1?.selected_policy ?? null,
    policy_id: (dioData as any)?.dio?.deal_classification_v1?.selected_policy ?? null,
    deal_classification_v1: (dioData as any)?.dio?.deal_classification_v1 ?? null,
		analysis_foundation_spec_version: (dioData as any)?.dio?.spec_versions?.analysis_foundation ?? null,
		phase_inference_v1: (dioData as any)?.dio?.phase_inference_v1 ?? null,
		fundability_assessment_v1: (dioData as any)?.dio?.fundability_assessment_v1 ?? null,
		fundability_decision_v1: (dioData as any)?.dio?.fundability_decision_v1 ?? null,
        executive_summary_v1: (dioData as any)?.dio?.phase1?.executive_summary_v1 ?? null,
        executive_summary_v2: (dioData as any)?.dio?.phase1?.executive_summary_v2 ?? null,
        decision_summary_v1: (dioData as any)?.dio?.phase1?.decision_summary_v1 ?? null,
        phase1_coverage: (dioData as any)?.dio?.phase1?.coverage ?? null,
        phase1_business_archetype_v1: (dioData as any)?.dio?.phase1?.business_archetype_v1 ?? null,
        phase1_deal_overview_v2: (dioData as any)?.dio?.phase1?.deal_overview_v2 ?? null,
        phase1_update_report_v1: (dioData as any)?.dio?.phase1?.update_report_v1 ?? null,
        phase1_deal_summary_v2: (dioData as any)?.dio?.phase1?.deal_summary_v2 ?? null,
        phase1_claims: (dioData as any)?.dio?.phase1?.claims ?? null,
        phase_b_latest_run: phaseBLatest,
        phase_b_history: phaseBHistory,
        last_analyzed_at: dioStatsRows[0]?.last_analyzed_at ?? null,
        run_count: dioStatsRows[0]?.run_count ?? 0,
        canonical_decision_v1: iirCanonicalRows[0]?.canonical_decision_v1 ?? null,
      });
    }

    let sectionEvidenceSamples: Partial<Record<ScoreBreakdownSectionKey, string[]>> | undefined;

    if (dioRows[0]) {
      let evidencePkColumn: string | null = null;
      try {
        try {
          const hasEvidenceTable = await hasTable(pool, "evidence");
          if (hasEvidenceTable) {
            const [hasId, hasEvidenceId] = await Promise.all([
              hasColumn(pool, "evidence", "id"),
              hasColumn(pool, "evidence", "evidence_id"),
            ]);
            evidencePkColumn = hasId ? "id" : hasEvidenceId ? "evidence_id" : null;
          }
        } catch {
          // best-effort only; do not block deal detail response
          evidencePkColumn = null;
        }

        const execV2 = (dioRows[0] as any).executive_summary_v2;
        let claims = Array.isArray((dioRows[0] as any).phase1_claims) ? (dioRows[0] as any).phase1_claims : [];

        claims = await ensureEvidenceLinksForClaims({ pool, dealId, dioId: (dioRows[0] as any)?.dio_id ?? null, claims });
        (dioRows[0] as any).phase1_claims = claims;
        try {
          sectionEvidenceSamples = await fetchEvidenceSamplesBySection({ pool, dealId, dioId: dioRows[0]?.dio_id ?? null, limit: 60 });
        } catch (err) {
          request.log?.info?.({
            deal_id: dealId,
            error: err instanceof Error ? err.message : String(err),
          }, "deal.score_breakdown_samples.fail_open");
          sectionEvidenceSamples = {};
        }

        const sampleIds = Object.values(sectionEvidenceSamples ?? {})
          .flatMap((arr) => (Array.isArray(arr) ? arr : []))
          .filter((id): id is string => typeof id === "string" && id.trim().length > 0);

        const evidenceIds = collectEvidenceIdsFromClaims(claims);
        const allEvidenceIds = Array.from(new Set([...evidenceIds, ...sampleIds]));
        const evidenceRows = allEvidenceIds.length > 0 ? await getEvidenceByIds(pool, allEvidenceIds) : [];
        const docIds = Array.from(
          new Set(
            evidenceRows
              .map((ev) => ev?.document_id)
              .filter((id): id is string => typeof id === "string" && id.trim().length > 0)
          )
        );
        const docIndex = docIds.length > 0 ? await getDocumentIndex(pool, docIds) : {};
        const evidenceById = new Map<string, EvidenceRow>();
        for (const ev of evidenceRows) {
          if (!ev?.id) continue;
          evidenceById.set(ev.id, ev);
        }

        const precomputedBreakdown = buildScoreBreakdownV1({
          accountability: (execV2 as any)?.accountability_v1,
          scoreAudit: (execV2 as any)?.score_audit_v1,
          coverage: (dioRows[0] as any)?.phase1_coverage,
          claims,
          sectionEvidenceSamples,
        });

        if (precomputedBreakdown) {
          // Path A telemetry: quantify how much of the score-linked evidence is actually node-backed.
          // This does not change the score yet; it makes the defensibility measurable and enables gating.
          try {
            for (const section of precomputedBreakdown.sections ?? []) {
              const linkedIds = Array.isArray(section.evidence_ids_linked)
                ? section.evidence_ids_linked.filter((v) => typeof v === "string" && v.trim().length > 0)
                : [];
              if (linkedIds.length === 0) {
                section.node_evidence_count_linked = 0;
                section.node_trace_coverage_pct = 0;
                section.node_coverage_pct = 0;
                continue;
              }

              let nodeBacked = 0;
              const missing: string[] = [];
              for (const id of linkedIds) {
                const row = evidenceById.get(id);
                const vaId = typeof (row as any)?.visual_asset_id === "string" ? String((row as any).visual_asset_id).trim() : "";
                if (vaId) nodeBacked += 1;
                else missing.push(id);
              }

              section.node_evidence_count_linked = nodeBacked;
              const pct = Math.min(1, Math.max(0, nodeBacked / linkedIds.length));
              section.node_trace_coverage_pct = pct;
              section.node_coverage_pct = Math.round(pct * 100);
              if (missing.length > 0) section.node_missing_linked_evidence_ids = missing.slice(0, 10);
            }
          } catch (err) {
            request.log?.info?.({
              deal_id: dealId,
              error: err instanceof Error ? err.message : String(err),
            }, "deal.node_evidence_coverage.fail_open");
          }

          // Path A gate: summarize node-backed coverage into a single readiness signal for UI and future enforcement.
          const nodeGate = computeNodeEvidenceGateV1(precomputedBreakdown.sections ?? []);
          (dioRows[0] as any).phase1_node_evidence_gate_v1 = nodeGate;
          if (execV2 && typeof execV2 === "object") {
            (execV2 as any).node_evidence_gate_v1 = nodeGate;

            // Keep executive accountability internally consistent by surfacing both counts:
            // - claim-based evidence (built from Phase 1 claims)
            // - score-linked evidence (from breakdown + node-backed locator coverage)
            const accountability = (execV2 as any).accountability_v1;
            if (accountability && typeof accountability === "object") {
              const evidenceCounts = (accountability as any).evidence_counts;
              if (evidenceCounts && typeof evidenceCounts === "object") {
                (evidenceCounts as any).node_linked_total = nodeGate.evidence_count_linked_total;
                (evidenceCounts as any).node_linked_node_backed = nodeGate.evidence_count_linked_node_backed;
                (evidenceCounts as any).node_linked_trace_coverage_pct = nodeGate.node_trace_coverage_pct;
                (evidenceCounts as any).node_linked_sections_considered = nodeGate.sections_considered;
                (evidenceCounts as any).node_linked_sections_blocking = nodeGate.sections_blocking;
              }

              const claimsTotal = typeof (evidenceCounts as any)?.claims_total === "number" ? (evidenceCounts as any).claims_total : null;
              const claimEvidenceTotal = typeof (evidenceCounts as any)?.evidence_total === "number" ? (evidenceCounts as any).evidence_total : null;
              const nodeLinkedTotal = nodeGate.evidence_count_linked_total;

              // If the two counts diverge, add an explicit note so users don't assume they are the same unit.
              if (claimEvidenceTotal != null && nodeLinkedTotal > 0 && claimEvidenceTotal !== nodeLinkedTotal) {
                const notes = Array.isArray((accountability as any).notes) ? (accountability as any).notes : [];
                const msg = `Evidence counts use different units: claims=${claimsTotal ?? 0}, claim_evidence=${claimEvidenceTotal} vs score_linked_evidence=${nodeLinkedTotal} (node_backed=${nodeGate.evidence_count_linked_node_backed}).`;
                if (!notes.some((x: any) => typeof x === "string" && x.includes("Evidence counts use different units"))) {
                  notes.push(msg);
                  (accountability as any).notes = notes;
                }
              }
            }
          }

          // Optional enforcement: degrade confidence + add a highlight when node-backed trace is poor.
          // This only affects the API response (does not persist to the DIO).
          const gateModeRaw = typeof process.env.DDAI_NODE_EVIDENCE_GATE_MODE === "string" ? process.env.DDAI_NODE_EVIDENCE_GATE_MODE : "off";
          const gateMode = gateModeRaw.toLowerCase();
          const enforce = gateMode === "enforce" || gateMode === "hard";
          const warnOnly = gateMode === "warn" || gateMode === "soft";
          if ((enforce || warnOnly) && execV2 && typeof execV2 === "object" && nodeGate.status !== "ok") {
            const signals = (execV2 as any)?.signals;
            if (signals && typeof signals === "object") {
              if (enforce && nodeGate.status === "block") {
                (signals as any).confidence = "low";
              }
            }
            const hl = Array.isArray((execV2 as any).highlights) ? (execV2 as any).highlights : [];
            const msg = `Node-backed scoring gate: ${nodeGate.status.toUpperCase()} (${nodeGate.node_coverage_pct}% node-locatable linked evidence).`;
            if (!hl.some((x: any) => typeof x === "string" && x.includes("Node-backed scoring gate"))) {
              hl.unshift(msg);
              (execV2 as any).highlights = hl.slice(0, 8);
            }
          }

          // Make the enriched breakdown visible to downstream mappers by attaching it to ES2.
          // (Some clients prefer execV2.score_breakdown_v1 from the persisted DIO payload.)
          if (execV2 && typeof execV2 === "object") {
            (execV2 as any).score_breakdown_v1 = precomputedBreakdown;
            if ((precomputedBreakdown as any).trace_audit_v1) {
              (execV2 as any).score_trace_audit_v1 = (precomputedBreakdown as any).trace_audit_v1;
            }
          }

          (dioRows[0] as any).computed_score_breakdown_v1 = precomputedBreakdown;
          const scoreEvidenceCanonical = buildScoreEvidenceFromBreakdown({
            sections: precomputedBreakdown.sections,
            evidenceById,
            docIndex,
          });
          (dioRows[0] as any).phase1_score_evidence = scoreEvidenceCanonical;
        } else {
          const scoreEvidence = buildPhase1ScoreEvidence({
            executiveSummaryV2: execV2,
            claims,
            evidenceById,
            docIndex,
          });
          if (scoreEvidence) (dioRows[0] as any).phase1_score_evidence = scoreEvidence;
        }
      } catch (err) {
        request.log?.info?.({
          deal_id: dealId,
          evidence_pk_column: evidencePkColumn,
          error: err instanceof Error ? err.message : String(err),
        }, "deal.score_evidence.fail_open");
      }
    }

    return mapDeal(rows[0], dioRows[0] ?? null, mode, { sectionEvidenceSamples });
  });

  app.put("/api/v1/deals/:deal_id", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    const parsed = dealUpdateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }
    const updates = parsed.data;
    if (Object.keys(updates).length === 0) {
      return reply.status(400).send({ error: "No fields to update" });
    }

    // Path A gate: optionally block manual transition to ready_decision when score-linked evidence isn't node-locatable.
    // This is a hard backstop for stage updates that bypass auto-progress.
    const nextStage = (updates as any)?.stage;
    if (nextStage === "ready_decision") {
      const gateModeRaw = typeof process.env.DDAI_NODE_EVIDENCE_GATE_MODE === "string" ? process.env.DDAI_NODE_EVIDENCE_GATE_MODE : "off";
      const gateMode = gateModeRaw.toLowerCase();
      const enforce = gateMode === "enforce" || gateMode === "hard";

      if (enforce) {
        const { rows: cur } = await pool.query<{ stage: string }>(
          `SELECT stage FROM deals WHERE id = $1 AND deleted_at IS NULL`,
          [dealId]
        );
        if (cur.length === 0) {
          return reply.status(404).send({ error: "Deal not found" });
        }

        // Only gate actual transitions into ready_decision (not idempotent updates).
        if (cur[0].stage !== "ready_decision") {
          const { gate } = await getNodeEvidenceGateForDeal(pool as any, dealId);
          if (gate.status === "block") {
            const msg = `Blocked from ready_decision. Node-backed scoring gate: ${gate.status.toUpperCase()} (${gate.node_coverage_pct}% node-locatable linked evidence).`;
            return reply.status(409).send({ error: "Stage transition blocked by node-backed scoring gate", message: msg, gate });
          }
        }
      }
    }

    const fields: string[] = [];
    const values: Array<string | number | null> = [];
    let idx = 1;

    for (const key of Object.keys(updates) as Array<keyof typeof updates>) {
      fields.push(`${key} = $${idx}`);
      const val = updates[key];
      values.push((val as string | number | null | undefined) ?? null);
      idx += 1;
    }

    values.push(dealId);

    const { rows } = await pool.query<DealRow>(
      `UPDATE deals
         SET ${fields.join(", ")}, updated_at = now()
       WHERE id = $${idx} AND deleted_at IS NULL
       RETURNING *`,
      values
    );

    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    return mapDeal(rows[0], null, "full");
  });

  // PR2A: governance-only switch for progressive LLM gating. No side effects.
  app.patch("/api/v1/deals/:deal_id/llm-phase", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    if (!isUuid(dealId)) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }

    const parsed = z.object({ llm_phase_mode: llmPhaseModeEnum }).safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }

    const next = parsed.data.llm_phase_mode;
    const { rows } = await pool.query<DealRow>(
      `UPDATE deals
          SET llm_phase_mode = $2,
              updated_at = now()
        WHERE id = $1
          AND deleted_at IS NULL
        RETURNING *`,
      [dealId, next]
    );

    if (!rows?.[0]) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    return reply.status(200).send(mapDeal(rows[0], null, "full"));
  });

  // PR2B: latest governed LLM overlay artifact (evidence-bound). Read-only; no side effects.
  app.get("/api/v1/deals/:deal_id/governed-llm-overview", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    if (!isUuid(dealId)) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }

    const tableOk = await hasTable(pool as any, "governed_llm_overviews");
    if (!tableOk) {
      return reply.status(200).send({ overview: null });
    }

    const { rows: dealRows } = await pool.query<{ id: string }>(
      `SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );
    if (dealRows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const { rows } = await pool.query<{
      id: string;
      deal_id: string;
      schema_version: string;
      llm_phase_mode: string;
      input_hash: string;
      run_id: string | null;
      step_run_id: string | null;
      summary_text: string;
      claims: any;
      disclosures: any;
      overview_json: any;
      consistency_warnings: any;
      created_at: string;
    }>(
      `SELECT id,
              deal_id::text as deal_id,
              schema_version,
              llm_phase_mode,
              input_hash,
              run_id,
              step_run_id,
              summary_text,
              claims,
              disclosures,
              overview_json,
              COALESCE(consistency_warnings, '[]'::jsonb) as consistency_warnings,
              created_at
         FROM governed_llm_overviews
        WHERE deal_id = $1
        ORDER BY created_at DESC, id DESC
        LIMIT 1`,
      [dealId]
    );

    const latest = rows?.[0] ?? null;
    if (!latest) {
      return reply.status(200).send({ overview: null });
    }

    const coerceJsonArray = (v: unknown): any[] => {
      if (Array.isArray(v)) return v;
      if (typeof v === "string") {
        try {
          const parsed = JSON.parse(v);
          return Array.isArray(parsed) ? parsed : [];
        } catch {
          return [];
        }
      }
      return [];
    };

    const coerceJsonObject = (v: unknown): Record<string, any> | null => {
      if (!v) return null;
      if (typeof v === "object" && !Array.isArray(v)) return v as any;
      if (typeof v === "string") {
        try {
          const parsed = JSON.parse(v);
          return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? (parsed as any) : null;
        } catch {
          return null;
        }
      }
      return null;
    };

    return reply.status(200).send({
      overview: {
        schema_version: latest.schema_version,
        deal_id: latest.deal_id,
        run_id: latest.run_id ?? undefined,
        step_run_id: latest.step_run_id ?? undefined,
        input_hash: latest.input_hash,
        created_at: latest.created_at,
        llm_phase_mode: latest.llm_phase_mode,
        summary_text: latest.summary_text,
        claims: coerceJsonArray(latest.claims),
        disclosures: coerceJsonArray(latest.disclosures),
        overview_json: coerceJsonObject((latest as any).overview_json),
        consistency_warnings: coerceJsonArray((latest as any).consistency_warnings),
      },
    });
  });

  // Deterministic Deal Deep Dive (v1): discovery -> gap -> implementation actions.
  // Read-only composition from existing persisted artifacts. No LLM calls. No DB writes.
  app.get("/api/v1/deals/:deal_id/deep-dive", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    if (!isUuid(dealId)) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }

    const { rows: dealRows } = await pool.query<{ id: string }>(
      `SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );
    if (dealRows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const { rows: latestDioRows } = await pool.query<{
      analysis_version: number | null;
      dio_data: any;
    }>(
      `SELECT analysis_version, dio_data
         FROM deal_intelligence_objects
        WHERE deal_id = $1
        ORDER BY analysis_version DESC NULLS LAST, updated_at DESC NULLS LAST, dio_id DESC
        LIMIT 1`,
      [dealId]
    );

    if (latestDioRows.length === 0) {
      return reply.status(200).send({ deep_dive: null, reason: "analysis_not_started" });
    }

    const latest = latestDioRows[0];
    const analysisVersion = typeof latest.analysis_version === "number" ? latest.analysis_version : null;
    const dioData = latest.dio_data && typeof latest.dio_data === "object" ? latest.dio_data : null;

    const reportPromise = analysisVersion != null
      ? pool.query<{ summary: any }>(
          `SELECT summary
             FROM ingestion_reports
            WHERE deal_id = $1 AND analysis_version = $2
            ORDER BY updated_at DESC NULLS LAST
            LIMIT 1`,
          [dealId, analysisVersion]
        )
      : Promise.resolve({ rows: [] as Array<{ summary: any }> });

    const renderPackagePromise = (async (): Promise<any | null> => {
      try {
        const { rows } = await pool.query<{ render_package: any }>(
          `SELECT render_package
             FROM investor_insight_reports
            WHERE deal_id = $1
            ORDER BY updated_at DESC
            LIMIT 1`,
          [dealId]
        );
        return rows?.[0]?.render_package ?? null;
      } catch (err: any) {
        const code = typeof err?.code === "string" ? err.code : null;
        if (code === "42P01") return null;
        throw err;
      }
    })();

    const [cachedReportResult, renderPackage] = await Promise.all([reportPromise, renderPackagePromise]);

    const report: any = cachedReportResult?.rows?.[0]?.summary ?? dioData?.report ?? null;

    let orchestratorReport: any = null;
    if (renderPackage && Array.isArray(renderPackage.sections)) {
      try {
        orchestratorReport = buildOrchestratorReportV1({ dealId, renderPackage });
      } catch {
        orchestratorReport = null;
      }
    }

    const deepDive = buildDealDeepDiveV1({
      deal_id: dealId,
      analysis_version: analysisVersion,
      dio: dioData,
      report,
      orchestrator_report: orchestratorReport,
    });

    return reply.status(200).send({ deep_dive: deepDive });
  });

  // PR3: latest analysis diagnostics snapshot (read-only). No side effects.
  app.get("/api/v1/deals/:deal_id/analysis-diagnostics", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    if (!isUuid(dealId)) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }

    const tableOk = await hasTable(pool as any, "deal_analysis_diagnostics");
    if (!tableOk) {
      return reply.status(200).send({ diagnostics: null });
    }

    const { rows: dealRows } = await pool.query<{ id: string }>(
      `SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );
    if (dealRows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    // PR3.1: error counters are optional in older DBs; select NULLs when columns absent.
    const hasProviderError = await hasColumn(pool as any, "deal_analysis_diagnostics", "provider_error_count");
    const hasTruncated = await hasColumn(pool as any, "deal_analysis_diagnostics", "model_output_truncated_count");
    const hasNotJson = await hasColumn(pool as any, "deal_analysis_diagnostics", "model_output_not_json_count");
    const hasGuardDegraded = await hasColumn(pool as any, "deal_analysis_diagnostics", "guard_degraded_count");

    const { rows } = await pool.query<{
      deal_id: string;
      report_id: string;
      llm_phase_mode: string;
      citation_integrity_percent: string | number | null;
      numeric_claims_without_evidence: number | null;
      semantic_drift_score: string | number | null;
      hallucination_count: number | null;
      deterministic_coverage_ratio: string | number | null;
      provider_error_count?: number | null;
      model_output_truncated_count?: number | null;
      model_output_not_json_count?: number | null;
      guard_degraded_count?: number | null;
      created_at: string;
    }>(
      `SELECT deal_id::text as deal_id,
              report_id,
              llm_phase_mode,
              citation_integrity_percent,
              numeric_claims_without_evidence,
              semantic_drift_score,
              hallucination_count,
              deterministic_coverage_ratio,
              ${hasProviderError ? "provider_error_count" : "NULL::int as provider_error_count"},
              ${hasTruncated ? "model_output_truncated_count" : "NULL::int as model_output_truncated_count"},
              ${hasNotJson ? "model_output_not_json_count" : "NULL::int as model_output_not_json_count"},
              ${hasGuardDegraded ? "guard_degraded_count" : "NULL::int as guard_degraded_count"},
              created_at
         FROM deal_analysis_diagnostics
        WHERE deal_id = $1
        ORDER BY created_at DESC, id DESC
        LIMIT 1`,
      [dealId]
    );

    const latest = rows?.[0] ?? null;
    if (!latest) {
      return reply.status(200).send({ diagnostics: null });
    }

    const toNum = (v: any): number | null => {
      if (v == null) return null;
      if (typeof v === "number" && Number.isFinite(v)) return v;
      if (typeof v === "string") {
        const n = Number(v);
        return Number.isFinite(n) ? n : null;
      }
      return null;
    };

    return reply.status(200).send({
      diagnostics: {
        deal_id: latest.deal_id,
        report_id: latest.report_id,
        llm_phase_mode: latest.llm_phase_mode,
        citation_integrity_percent: toNum(latest.citation_integrity_percent),
        numeric_claims_without_evidence: latest.numeric_claims_without_evidence,
        semantic_drift_score: toNum(latest.semantic_drift_score),
        hallucination_count: latest.hallucination_count,
        deterministic_coverage_ratio: toNum(latest.deterministic_coverage_ratio),
        provider_error_count: typeof (latest as any).provider_error_count === "number" ? (latest as any).provider_error_count : null,
        model_output_truncated_count: typeof (latest as any).model_output_truncated_count === "number" ? (latest as any).model_output_truncated_count : null,
        model_output_not_json_count: typeof (latest as any).model_output_not_json_count === "number" ? (latest as any).model_output_not_json_count : null,
        guard_degraded_count: typeof (latest as any).guard_degraded_count === "number" ? (latest as any).guard_degraded_count : null,
        created_at: latest.created_at,
      },
    });
  });

  app.patch("/api/v1/deals/:deal_id/archive", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    const reason = extractAuditReason((request as any).body, {
      query: (request as any).query,
      headers: (request as any).headers,
    });
    if (!reason) {
      return reply.status(400).send({ error: "reason is required for this privileged mutation", code: "MISSING_AUDIT_REASON" });
    }
    const actor = getAuditActorContext(request as any);
    const hasLifecycle = await hasColumn(pool, "deals", "lifecycle_status");
    if (!hasLifecycle) {
      return reply.status(501).send({ error: "archive_not_supported", message: "lifecycle_status column is missing" });
    }

    const { rows: beforeRows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 LIMIT 1`,
      [dealId]
    );

    const { rows } = await pool.query<DealRow>(
      `UPDATE deals
          SET lifecycle_status = 'archived',
              updated_at = now()
        WHERE id = $1
          AND deleted_at IS NULL
        RETURNING *`,
      [dealId]
    );

    if (!rows.length) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    await writePlatformAuditLog({
      ...actor,
      action_type: "deal.archive",
      entity_type: "deal",
      entity_id: dealId,
      before_state: beforeRows[0] ?? {},
      after_state: rows[0] ?? {},
      reason,
    });

    return mapDeal(rows[0], null, "full");
  });

  app.patch("/api/v1/deals/:deal_id/unarchive", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    const reason = extractAuditReason((request as any).body, {
      query: (request as any).query,
      headers: (request as any).headers,
    });
    if (!reason) {
      return reply.status(400).send({ error: "reason is required for this privileged mutation", code: "MISSING_AUDIT_REASON" });
    }
    const actor = getAuditActorContext(request as any);
    const hasLifecycle = await hasColumn(pool, "deals", "lifecycle_status");
    if (!hasLifecycle) {
      return reply.status(501).send({ error: "archive_not_supported", message: "lifecycle_status column is missing" });
    }

    const { rows: beforeRows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 LIMIT 1`,
      [dealId]
    );

    const { rows } = await pool.query<DealRow>(
      `UPDATE deals
          SET lifecycle_status = 'active',
              updated_at = now()
        WHERE id = $1
          AND deleted_at IS NULL
        RETURNING *`,
      [dealId]
    );

    if (!rows.length) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    await writePlatformAuditLog({
      ...actor,
      action_type: "deal.unarchive",
      entity_type: "deal",
      entity_id: dealId,
      before_state: beforeRows[0] ?? {},
      after_state: rows[0] ?? {},
      reason,
    });

    return mapDeal(rows[0], null, "full");
  });

  app.patch("/api/v1/deals/:deal_id/restore", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    const reason = extractAuditReason((request as any).body, {
      query: (request as any).query,
      headers: (request as any).headers,
    });
    if (!reason) {
      return reply.status(400).send({ error: "reason is required for this privileged mutation", code: "MISSING_AUDIT_REASON" });
    }
    const actor = getAuditActorContext(request as any);
    const auth = requireDestructiveAuth(request);
    if (!auth.ok) {
      return reply.status(auth.status).send({ error: auth.error });
    }

    const { rows: beforeRows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 LIMIT 1`,
      [dealId]
    );

    const { rows } = await pool.query<DealRow>(
      `UPDATE deals
          SET deleted_at = NULL,
              lifecycle_status = CASE
                WHEN lifecycle_status = 'archived' THEN lifecycle_status
                ELSE 'active'
              END,
              updated_at = now()
        WHERE id = $1
          AND deleted_at IS NOT NULL
        RETURNING *`,
      [dealId]
    );

    if (!rows.length) {
      return reply.status(404).send({ error: "Deleted deal not found" });
    }

    await writePlatformAuditLog({
      ...actor,
      action_type: "deal.restore",
      entity_type: "deal",
      entity_id: dealId,
      before_state: beforeRows[0] ?? {},
      after_state: rows[0] ?? {},
      reason,
    });

    return mapDeal(rows[0], null, "full");
  });

  app.post("/api/v1/deals/:deal_id/view", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    const hasViews = await hasColumn(pool, "deals", "views");
    if (!hasViews) {
      return reply.status(501).send({ error: "views_not_supported", message: "views column is missing" });
    }

    const { rows } = await pool.query<DealRow>(
      `UPDATE deals
          SET views = COALESCE(views, 0) + 1
        WHERE id = $1
          AND deleted_at IS NULL
        RETURNING *`,
      [dealId]
    );

    if (!rows.length) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    return reply.status(200).send({
      ok: true,
      deal_id: dealId,
      views: parseNullableNumber((rows[0] as any).views) ?? 0,
    });
  });

  app.delete("/api/v1/deals/:deal_id", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    const reason = extractAuditReason((request as any).body, {
      query: (request as any).query,
      headers: (request as any).headers,
    });
    if (!reason) {
      return reply.status(400).send({ error: "reason is required for this privileged mutation", code: "MISSING_AUDIT_REASON" });
    }
    const actor = getAuditActorContext(request as any);

    const q = (request.query ?? {}) as any;
    const rawPurge = q?.purge;
    const purge =
      rawPurge === true ||
      rawPurge === "true" ||
      (Array.isArray(rawPurge) && String(rawPurge[0]).toLowerCase() === "true");

    if (!purge) {
      const { rows: beforeRows } = await pool.query<DealRow>(
        `SELECT * FROM deals WHERE id = $1 LIMIT 1`,
        [dealId]
      );
      const { rows } = await pool.query<DealRow>(
        `UPDATE deals
            SET deleted_at = now(),
                updated_at = now()
          WHERE id = $1
            AND deleted_at IS NULL
          RETURNING *`,
        [dealId]
      );

      if (!rows.length) {
        return reply.status(404).send({ error: "Deal not found" });
      }

      await writePlatformAuditLog({
        ...actor,
        action_type: "deal.soft_delete",
        entity_type: "deal",
        entity_id: dealId,
        before_state: beforeRows[0] ?? {},
        after_state: rows[0] ?? {},
        reason,
      });

      return reply.send({ ok: true, deal_id: dealId, delete_mode: "soft" });
    }

    const auth = await requirePurgeAuth(request, reply);
    if (!auth.ok) {
      return reply.status(auth.status).send({ error: auth.error });
    }

    const confirm = requirePurgeConfirmation(
      request,
      buildPurgeConfirmationToken({ entityType: "deal", entityId: dealId })
    );
    if (!confirm.ok) {
      return reply.status(confirm.status).send({ error: confirm.error, code: "PURGE_CONFIRMATION_REQUIRED" });
    }

    const { rows: beforeRows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 LIMIT 1`,
      [dealId]
    );

    const actor_user_id = actor.actor_user_id;

    try {
      const result = await purgeDealCascade({
        deal_id: dealId,
        actor_user_id,
        reason,
        db: pool as any,
        logger: console as any,
      });

      await writePlatformAuditLog({
        ...actor,
        action_type: "deal.purge",
        entity_type: "deal",
        entity_id: dealId,
        before_state: beforeRows[0] ?? {},
        after_state: result as unknown as Record<string, unknown>,
        reason,
      });

      return reply.send({ ok: true, deal_id: dealId, purge: result });
    } catch (err) {
      if (isPurgeDealNotFoundError(err)) {
        return reply.status(404).send({ error: "Deal not found" });
      }
      const message = err instanceof Error ? err.message : "Purge failed";
      return reply.status(500).send({ error: message });
    }
  });

}
