/**
 * apps/api/src/routes/deals/deal-operations.routes.ts
 * registerDealOperationsRoutes — extracted from deals.ts (PR12)
 * AUTO-GENERATED by scripts/dev/split-deals-final.py
 */
import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import { fetchPhaseBVisualsFromDb } from "../../lib/phaseb-visuals";
import { getUploadsRootDir } from "../../plugins/uploads-static";
import { getPool } from "../../lib/db";
import { resolveVisualAssetImageUriForApi } from "../../lib/visual-asset-image-uri";
import type { Deal } from "@dealdecision/contracts";
import type { JobStatus, JobType } from "@dealdecision/contracts";
import { QUEUE_NAMES } from "@dealdecision/core";
import { enqueueBullmqJob, enqueueJob, insertJobRow } from "../../services/jobs";
import { getQueues } from "../../lib/queue";
import { runIdempotentOperation } from "../../lib/jobs";
import { getStorageDriver } from "../../lib/storage-contract";
import { autoProgressDealStage } from "../../services/stageProgression";
import { updateDealPriority, updateAllDealPriorities } from "../../services/priorityClassification";
import { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";
import { getNodeEvidenceGateForDeal } from "../../services/nodeEvidenceGateForDeal";
import { normalizeDealName } from "../../lib/normalize-deal-name";
import { buildDocumentsDigest } from "../../lib/documents-digest";
import type { DocumentsDigestV1 } from "../../lib/documents-digest";
import { objectExistsInR2 } from "../../lib/r2";
import {
  purgeDealCascade,
  isPurgeDealNotFoundError,
  sanitizeText,
  getDocumentCapabilities,
  buildDealScoringInputV0FromLineage,
  getSegmentConfidenceThresholds,
  detectContentArchetypeTags,
  buildOrchestratorReportV1,
} from "@dealdecision/core";
import {
  BrandModel,
  PageInput,
  buildBrandModel,
  inferDocumentBrandName,
  inferSlideTitleForSlide,
  isLikelyGarbledSlideTitle,
  normalizePhrase,
} from "../../lib/slide-title";
import {
  buildClassificationText,
  buildSegmentFeatures,
  classifySegment,
  normalizeAnalystSegment,
  type AnalystSegment,
  type SegmentClassifierInput,
} from "../../lib/analyst-segment";
import {
  groupWordVisualAssetsByDocument,
  groupWordVisualAssetsByDocumentWithStats,
  type WordGroupingStats,
} from "../../lib/word-visual-grouping";
import { fetchPageUnderstandingReadinessForDeal } from "../../lib/deal-page-understanding-readiness";
import { ensureDocumentsReadyForAnalysis } from "../../lib/ensure-documents-ready-for-analysis";
import { getCanonicalFieldsForAI } from "../../lib/canonical-fields-for-ai";
import type {
  QueryResult,
  DealRoutesPool,
  DealRoutesClient,
  DealApiMode,
  AutoProfileDocRow,
  DealRow,
  DIOAggregateRow,
  ScoreBreakdownSectionKey,
  EvidenceRow,
  StatusSummaryAnalysis,
  StatusSummaryReport,
  StatusSummaryEvidenceGate,
  StatusSummary,
} from "./_shared";
import {
  hasTable,
  hasColumn,
  getColumnDataType,
  isUuid,
  stripEvidenceFromExecutiveSummary,
  stripEvidenceFromClaims,
  parseDealApiMode,
  bestEffortReadinessJobPresenceCheck,
  parseBoolQ,
  computeOcrV2CleanText,
  pickNonUnknownSegment,
  majorityNonUnknownSegment,
  isStructuredWordSectionAsset,
  structuredWordContentStats,
  isEmptyStructuredWordSectionAsset,
  computeDocHintSegmentByDocId,
  applyNeighborHintPropagationToAssets,
  buildDeterministicGroupCapturedText,
  extractStructuredWordTextForCue,
  inferStructuredWordCueSegment,
  requireDestructiveAuth,
  dealStageEnum,
  dealPriorityEnum,
  normalizeDealTrend,
  dealTrendEnum,
  dealCreateSchema,
  dealDraftCreateSchema,
  dealConfirmProfileSchema,
  sanitizeProfileValue,
  extractLabeledValue,
  isGenericCandidateName,
  deriveNameFromFilenameLike,
  extractCompanyFromEarlyText,
  computeAutoProfileFromDocuments,
  normalizeWarningsForPersistence,
  jsonbParam,
  dealUpdateSchema,
  llmPhaseModeEnum,
  parseNullableNumber,
  SCORE_BREAKDOWN_SECTION_ORDER,
  CLAIM_CATEGORY_SECTION_MAP,
  normalizeCategory,
  sectionForCategory,
  buildScoreBreakdownV1,
  collectEvidenceIdsFromClaims,
  getEvidenceByIds,
  getDocumentIndex,
  fetchEvidenceSamplesBySection,
  normalizeEvidenceSnippet,
  BUSINESS_MODEL_STRONG_REGEX,
  deriveSectionKeyFromClaim,
  ensureEvidenceLinksForClaims,
  buildPhase1ScoreEvidence,
  buildScoreEvidenceFromBreakdown,
  mapDeal,
  safeJsonValue,
  ocrSnippet,
  deriveStructuredSummary,
  cueRescueLowSignal,
  deriveBestExtractionConfidence,
  mapAnalysisJobStatus,
  mapReportRowStatus,
  maxIsoTs,
  buildStatusSummary,
} from "./_shared";

export async function registerDealOperationsRoutes(
  app: FastifyInstance,
  pool: DealRoutesPool,
  enqueue: typeof enqueueJob,
  r2: { objectExistsInR2: typeof objectExistsInR2 },
  debugRoutesEnabled: boolean,
  deps?: {
    enqueueJob?: typeof enqueueJob;
    jobs?: { queue?: any };
    r2?: { objectExistsInR2?: typeof objectExistsInR2 };
    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };
  }
): Promise<void> {
  app.post("/api/v1/deals/:deal_id/analyze", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
		if (!isUuid(dealId)) {
			return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
		}
    const forceRefresh = Boolean((request.body as any)?.force_refresh);
    const requirePageUnderstanding = Boolean((request.body as any)?.require_page_understanding) || forceRefresh;
    const pageUnderstandingVersionRaw = (request.body as any)?.page_understanding_version;
    const pageUnderstandingVersion =
      typeof pageUnderstandingVersionRaw === "string" && pageUnderstandingVersionRaw.trim().length > 0
        ? pageUnderstandingVersionRaw.trim()
        : "page_understanding_v1";
    const minDpuCreatedAtRaw = (request.body as any)?.min_dpu_created_at;
    const minDpuCreatedAtFromClient =
      typeof minDpuCreatedAtRaw === "string" && minDpuCreatedAtRaw.trim().length > 0
        ? minDpuCreatedAtRaw.trim()
        : null;

    // For reruns/force-refresh flows, callers should treat min_dpu_created_at as a stable
    // token across retries so readiness + subsequent analysis are anchored to the same
    // DPU freshness floor.
    const minDpuCreatedAt =
      (forceRefresh || minDpuCreatedAtFromClient)
        ? (minDpuCreatedAtFromClient ?? new Date().toISOString())
        : null;

    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );

    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    if (requirePageUnderstanding) {
      try {
        const prep = await ensureDocumentsReadyForAnalysis({
          pool: pool as any,
          dealId,
          requirePageUnderstanding: true,
          pageUnderstandingVersion,
          forceRefresh,
          minDpuCreatedAt,
          logger: request.log,
          enqueue,
        });

        request.log.info(
          {
            event: "READINESS_CHECK",
            deal_id: dealId,
            version: prep.readiness.version,
            expected_pages_total: prep.readiness.expected_pages_total,
            dpu_rows_total: prep.readiness.dpu_rows_total,
            missing_pages_total: prep.readiness.missing_pages_total,
            ready: prep.ready,
            blocked_reason: prep.blocked_reason,
            enqueued: prep.enqueued,
          },
          "deal.analysis.preflight"
        );

        if (!prep.ready) {
          // Don't enqueue analysis yet; caller should poll readiness and retry when ready.
          return reply.status(202).send({
            status: "preparing_documents",
            error: "page_understanding_not_ready",
            message: "Preparing documents for analysis. Poll /readiness and retry once readiness is true.",
            blocked_reason: prep.blocked_reason,
            poll_after_ms: prep.poll_after_ms,
            enqueued: prep.enqueued,
            ...(minDpuCreatedAt ? { min_dpu_created_at: minDpuCreatedAt } : {}),
            readiness: prep.readiness,
          });
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        request.log.error(
          { event: "READINESS_CHECK_FAILED", deal_id: dealId, err: message },
          "Failed to compute/ensure page understanding readiness"
        );
        // Return 202 (not 500) so the UI shows "preparing" rather than "Analysis failed to start".
        // The error is surfaced via blocked_reason so the polling loop handles it safely.
        return reply.status(202).send({
          status: "preparing_documents",
          error: "page_understanding_not_ready",
          blocked_reason: "READINESS_COMPUTE_ERROR",
          message: "Failed to compute page understanding readiness — will retry.",
          poll_after_ms: 2000,
          ...(process.env.NODE_ENV === "production" ? {} : { detail: message }),
        });
      }
    }

    let job: { job_id: string; status: string };
    try {
      job = await enqueue(
        {
          deal_id: dealId,
          type: "analyze_deal",
          payload: {
            require_page_understanding: requirePageUnderstanding,
            page_understanding_version: pageUnderstandingVersion,
            ...(minDpuCreatedAt ? { min_dpu_created_at: minDpuCreatedAt } : {}),
            ...(forceRefresh ? { force_refresh: true } : {}),
          },
        },
        { dedupe: { by: "deal" } }
      );
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      request.log.error(
        { event: "analyze_deal.enqueue_failed", deal_id: dealId, err: message },
        "Failed to enqueue analyze_deal"
      );
      return reply.status(503).send({
        error: "queue_unavailable",
        message:
          "Failed to enqueue analysis job. Queue/Redis may be unavailable. Check REDIS_URL and that Redis is running (for local: pnpm local:up).",
        ...(process.env.NODE_ENV === "production" ? {} : { detail: message }),
      });
    }

    // After analysis job is enqueued, mark it so we can auto-progress when complete
    // (This would typically happen in a background worker after job completes)
    // For now, we queue the job and the worker will handle stage progression

    // When preflight is not requested, analysis may fail due to missing prereqs.
    // Make this behavior explicit (extra fields are backwards-compatible).
    if (!requirePageUnderstanding) {
      return reply.status(202).send({
        job_id: job.job_id,
        status: job.status,
        prereqs_kicked: false,
        note:
          "Prerequisites were not kicked because require_page_understanding=false. If readiness is blocked (e.g. PAGE_COUNT_UNKNOWN), call /prepare or call /analyze with {require_page_understanding:true}.",
      });
    }

    return reply.status(202).send({ job_id: job.job_id, status: job.status, prereqs_kicked: true });
  });

  // Explicit opt-in endpoint to prepare documents for analysis.
  // Safe for prod: it only enqueues prerequisites, it does not silently run analysis.
  app.post("/api/v1/deals/:deal_id/prepare", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    if (!isUuid(dealId)) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }

    const pageUnderstandingVersionRaw = (request.body as any)?.page_understanding_version;
    const pageUnderstandingVersion =
      typeof pageUnderstandingVersionRaw === "string" && pageUnderstandingVersionRaw.trim().length > 0
        ? pageUnderstandingVersionRaw.trim()
        : "page_understanding_v1";

    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );
    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    try {
      const prep = await ensureDocumentsReadyForAnalysis({
        pool: pool as any,
        dealId,
        requirePageUnderstanding: true,
        pageUnderstandingVersion,
        logger: request.log,
        enqueue,
      });

      request.log.info(
        {
          event: "DOC_PREPARE_RESULT",
          deal_id: dealId,
          version: prep.readiness.version,
          expected_pages_total: prep.readiness.expected_pages_total,
          dpu_rows_total: prep.readiness.dpu_rows_total,
          missing_pages_total: prep.readiness.missing_pages_total,
          ready: prep.ready,
          blocked_reason: prep.blocked_reason,
          enqueued: prep.enqueued,
        },
        "deal.prepare"
      );

      if (!prep.ready) {
        return reply.status(202).send({
          status: "preparing_documents",
          message: "Preparing documents for analysis. Poll /readiness and retry once readiness is true.",
          blocked_reason: prep.blocked_reason,
          poll_after_ms: prep.poll_after_ms,
          enqueued: prep.enqueued,
          readiness: prep.readiness,
        });
      }

      return reply.send({
        status: "ready",
        blocked_reason: null,
        poll_after_ms: null,
        enqueued: prep.enqueued,
        readiness: prep.readiness,
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      request.log.error(
        { event: "DOC_PREPARE_FAILED", deal_id: dealId, err: message },
        "Failed to prepare documents for analysis"
      );
      return reply.status(500).send({
        error: "prepare_failed",
        message: "Failed to prepare documents for analysis.",
        ...(process.env.NODE_ENV === "production" ? {} : { detail: message }),
      });
    }
  });

  app.get("/api/v1/deals/:deal_id/readiness", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    if (!isUuid(dealId)) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }

    const versionRaw = (request.query as any)?.page_understanding_version;
    const version = typeof versionRaw === "string" && versionRaw.trim().length > 0 ? versionRaw.trim() : "page_understanding_v1";

    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );
    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const readiness = await fetchPageUnderstandingReadinessForDeal(pool as any, dealId, version);

    // Optional freshness gate: callers (UI) may pass min_dpu_created_at to ensure readiness
    // reflects a forced refresh completion, not just missing pages.
    try {
      const minRaw = (request.query as any)?.min_dpu_created_at;
      const min = typeof minRaw === "string" && minRaw.trim().length > 0 ? minRaw.trim() : null;
      const latest = typeof (readiness as any)?.latest_dpu_created_at === "string" ? String((readiness as any).latest_dpu_created_at) : null;
      if (min && latest) {
        const a = Date.parse(latest);
        const b = Date.parse(min);
        if (Number.isFinite(a) && Number.isFinite(b) && a < b) {
          (readiness as any).ready = false;
          (readiness as any).blocked_reason = (readiness as any).blocked_reason ?? "DPU_STALE";
          (readiness as any).poll_after_ms = (readiness as any).poll_after_ms ?? 2000;
          (readiness as any).action = (readiness as any).action ?? { type: "rebuild_page_understanding", deal_id: dealId, version };
        }
      }
    } catch {
      // best-effort
    }

    // If any visual document still has unknown page_count (0), treat readiness as not ready.
    // This prevents analysis from proceeding (or the UI from flipping to ready) before
    // render_document_pages has established page_count + rendered pages.
    try {
      const hasMimeType = await hasColumn(pool as any, "documents", "mime_type");
      const hasFileName = await hasColumn(pool as any, "documents", "file_name");
      const hasFilename = hasFileName ? false : await hasColumn(pool as any, "documents", "filename");
      const fileNameExpr = hasFileName ? "d.file_name" : hasFilename ? "d.filename" : "NULL::text";
      const mimeTypeExpr = hasMimeType ? "d.mime_type" : "NULL::text";

      const { rows: docRows } = await pool.query<{
        id: string;
        page_count: number | null;
        file_name: string | null;
        mime_type: string | null;
      }>(
        `SELECT d.id,
                COALESCE(d.page_count, 0) AS page_count,
                ${fileNameExpr} AS file_name,
                ${mimeTypeExpr} AS mime_type
           FROM documents d
          WHERE d.deal_id = $1
            AND d.deleted_at IS NULL`,
        [dealId]
      );

      const unknownPageCountVisualDocs: string[] = [];
      for (const d of docRows ?? []) {
        const caps = getDocumentCapabilities({
          fileName: typeof d.file_name === "string" ? d.file_name : null,
          mimeType: typeof d.mime_type === "string" ? d.mime_type : null,
        });
        const pageCount = typeof d.page_count === "number" && Number.isFinite(d.page_count) ? Math.max(0, Math.trunc(d.page_count)) : 0;
        if (caps.visualExtractable && caps.supports_page_rendering && pageCount <= 0) {
          unknownPageCountVisualDocs.push(d.id);
        }
      }

      if (unknownPageCountVisualDocs.length > 0) {
        (readiness as any).ready = false;
        (readiness as any).blocked_reason = (readiness as any).blocked_reason ?? "PAGE_COUNT_UNKNOWN";
        (readiness as any).poll_after_ms = (readiness as any).poll_after_ms ?? 2000;
        (readiness as any).action = (readiness as any).action ?? { type: "render_document_pages", deal_id: dealId, version };
        (readiness as any).render_missing_page_count_documents = unknownPageCountVisualDocs;

        // Observability: if no prerequisite jobs exist, explain how to kick them.
        // Readiness is intentionally read-only by default.
        try {
          const res = await pool.query(
            `SELECT 1
               FROM jobs
              WHERE deal_id = $1
                AND type = ANY($2::text[])
                AND created_at >= (now() - interval '2 hours')
              LIMIT 1`,
            [dealId, ["render_document_pages", "document_intelligence_extract", "populate_document_page_understanding"]]
          );
          const hasAnyPrereqJob = Array.isArray((res as any)?.rows) && (res as any).rows.length > 0;
          if (!hasAnyPrereqJob) {
            (readiness as any).blocked_message =
              "No pages rendered yet (page_count=0). Call POST /api/v1/deals/:deal_id/prepare or POST /api/v1/deals/:deal_id/analyze with {require_page_understanding:true} to enqueue render/OCR/DPU prerequisites.";
            (readiness as any).blocked_action = {
              method: "POST",
              path: `/api/v1/deals/${dealId}/prepare`,
              body: { page_understanding_version: version },
            };
          }
        } catch {
          // best-effort only
        }
      }
    } catch {
      // best-effort only
    }
    const nonMeaningfulPagesTotal =
      typeof (readiness as any)?.non_meaningful_pages_total === "number" &&
      Number.isFinite((readiness as any).non_meaningful_pages_total)
        ? (readiness as any).non_meaningful_pages_total
        : 0;

    const hardMissingPagesTotal =
      typeof (readiness as any)?.hard_missing_pages_total === "number" && Number.isFinite((readiness as any).hard_missing_pages_total)
        ? Math.max(0, Math.trunc((readiness as any).hard_missing_pages_total))
        : null;

    // Only treat readiness as "blocked/stalled" when pages are truly missing (no payload row),
    // not when pages exist but are empty.
    const presenceMissingTotal = hardMissingPagesTotal != null ? hardMissingPagesTotal : readiness.missing_pages_total;

    if (readiness.expected_pages_total > 0 && presenceMissingTotal > 0) {
      const shouldPresenceCheck = readiness.dpu_rows_total === 0 || nonMeaningfulPagesTotal > 0;
      if (shouldPresenceCheck) {
        const presence = await bestEffortReadinessJobPresenceCheck({ pool: pool as any, dealId, version });
        (readiness as any).blocked_reason = presence.blocked_reason;
        if (!presence.blocked_reason && nonMeaningfulPagesTotal > 0) {
          (readiness as any).blocked_reason = "DPU_EMPTY_CONTENT";
          (readiness as any).poll_after_ms = 1500;
          (readiness as any).action = { type: "rebuild_page_understanding", deal_id: dealId, version };
        }

        // PR7-lite Rules 1 + 2: Override job-presence blocked reasons when analysis is
        // already complete or a render package exists. DPU_EMPTY_CONTENT is a separate
        // content-quality issue and is intentionally left unchanged.
        const _presenceBlockedReasons = new Set([
          "INGEST_BLOCKED_NO_JOBS",
          "READY_TO_ANALYZE_ENQUEUE_PENDING",
          "INGEST_PENDING_OCR",
        ]);
        if (
          (readiness as any).blocked_reason &&
          _presenceBlockedReasons.has((readiness as any).blocked_reason)
        ) {
          try {
            const [_jobRes, _pkgRes] = await Promise.all([
              pool.query(
                `SELECT status FROM jobs WHERE deal_id = $1 AND type = 'analyze_deal' ORDER BY created_at DESC LIMIT 1`,
                [dealId]
              ),
              pool.query(
                `SELECT 1 FROM investor_insight_reports WHERE deal_id = $1 AND render_package IS NOT NULL LIMIT 1`,
                [dealId]
              ),
            ]);
            const _analyzeStatus = (_jobRes as any)?.rows?.[0]?.status ?? null;
            const _hasRenderPkg =
              Array.isArray((_pkgRes as any)?.rows) && (_pkgRes as any).rows.length > 0;
            if (
              _hasRenderPkg ||
              _analyzeStatus === "succeeded" ||
              _analyzeStatus === "succeeded_with_warnings"
            ) {
              (readiness as any).blocked_reason = null;
            }
          } catch {
            // best-effort override — non-critical
          }
        }

        if ((readiness as any).blocked_reason) {
          request.log.error(
            {
              event: "INGEST_BLOCKED_NO_JOBS",
              deal_id: dealId,
              version,
              expected_pages_total: readiness.expected_pages_total,
              dpu_rows_total: readiness.dpu_rows_total,
              missing_pages_total: readiness.missing_pages_total,
              non_meaningful_pages_total: nonMeaningfulPagesTotal,
              checked: presence.checked,
              blocked_reason: (readiness as any).blocked_reason,
            },
            "Readiness is blocked or stalled"
          );
        }
      }
    }
    const logLevel = readiness.ready ? "info" : (readiness.missing_pages_total > 0 ? "warn" : "info");
    request.log[logLevel](
      {
        event: "READINESS_CHECK",
        deal_id: dealId,
        version: readiness.version,
        expected_pages_total: readiness.expected_pages_total,
        dpu_rows_total: readiness.dpu_rows_total,
        dpu_rows_meaningful_total: (readiness as any).dpu_rows_meaningful_total ?? null,
        missing_pages_total: readiness.missing_pages_total,
        ready: readiness.ready,
        blocked_reason: (readiness as any).blocked_reason ?? null,
        latest_dpu_created_at: (readiness as any).latest_dpu_created_at ?? null,
        min_dpu_created_at_param: (request.query as any)?.min_dpu_created_at ?? null,
        // Per-document snapshot (suppressed in production to avoid noisy logs)
        ...(process.env.NODE_ENV !== "production"
          ? {
              documents: (readiness.documents ?? []).map((d: any) => ({
                document_id: d.document_id,
                title: d.title ?? null,
                page_count: d.page_count,
                dpu_rows: d.dpu_rows,
                dpu_rows_meaningful: d.dpu_rows_meaningful ?? null,
                missing_pages_count: Array.isArray(d.missing_pages) ? d.missing_pages.length : null,
                hard_missing_pages_count: Array.isArray(d.hard_missing_pages) ? d.hard_missing_pages.length : null,
                missing_pages_sample: Array.isArray(d.missing_pages) ? d.missing_pages.slice(0, 5) : null,
              })),
            }
          : {}),
      },
      "deal.page_understanding.readiness"
    );

    return reply.send(readiness);
  });

  // Enqueue a best-effort visual extraction pass for all documents in the deal.
  // This does not re-render pages; it only uses already-rendered page images.
  app.post("/api/v1/deals/:deal_id/extract-visuals", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    if (!isUuid(dealId)) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }

    const forceResegment = Boolean((request.body as any)?.force_resegment);
    const forceReextract = Boolean((request.body as any)?.force_reextract);
    const enqueueDeepScanRaw = (request.body as any)?.enqueue_deep_scan;
    const enqueueDeepScan = enqueueDeepScanRaw == null ? true : Boolean(enqueueDeepScanRaw);

    class AfterCommitEnqueueError extends Error {
      jobId: string;
      constructor(jobId: string, cause: unknown) {
        super("after_commit_enqueue_failed");
        this.name = "AfterCommitEnqueueError";
        this.jobId = jobId;
        (this as any).cause = cause;
      }
    }

    const requestIdHeader = request.headers['x-request-id'];
    const sourceHeader = request.headers['x-client-source'];
    const idempotencyHeader = request.headers['x-idempotency-key'];

    const requestId = typeof requestIdHeader === 'string' && requestIdHeader.trim().length > 0 ? requestIdHeader.trim() : null;
    const source = typeof sourceHeader === 'string' && sourceHeader.trim().length > 0 ? sourceHeader.trim() : null;
    const idempotencyKey = typeof idempotencyHeader === 'string' && idempotencyHeader.trim().length > 0 ? idempotencyHeader.trim() : null;

    const auth = (request as any)?.auth as { userId?: string | null; orgId?: string | null } | undefined;
    const actorUserId = typeof auth?.userId === 'string' && auth.userId ? auth.userId : null;
    const actorOrgId = typeof auth?.orgId === 'string' && auth.orgId ? auth.orgId : null;

    if (requestId || source || idempotencyKey) {
      request.log.info(
        {
          msg: 'deal.extract_visuals.requested',
          deal_id: dealId,
          request_id: requestId,
          idempotency_key: idempotencyKey,
          source,
          actor_user_id: actorUserId,
          actor_org_id: actorOrgId,
        },
        'extract-visuals requested'
      );
    }

    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );

    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const hasMimeType = await hasColumn(pool as any, "documents", "mime_type");
    const canJoinOriginalFile = await hasTable(pool as any, "document_files");
    const { rows: docs } = await pool.query<{ id: string; file_name: string | null; mime_type?: string | null; extraction_metadata: unknown | null }>(
      canJoinOriginalFile
        ? `SELECT d.id,
                  df.file_name AS file_name
                  ${hasMimeType ? ", d.mime_type" : ", NULL::text AS mime_type"},
                  d.extraction_metadata
             FROM documents d
             LEFT JOIN document_files df ON df.document_id = d.id
            WHERE d.deal_id = $1 AND d.deleted_at IS NULL`
        : `SELECT id,
                  NULL::text AS file_name
                  ${hasMimeType ? ", mime_type" : ", NULL::text AS mime_type"},
                  extraction_metadata
             FROM documents
            WHERE deal_id = $1 AND deleted_at IS NULL`,
      [dealId]
    );

    const readyDocIds: string[] = [];
    const blocked: Array<{
      document_id: string;
      failure_reason: string;
      next_action: string;
      retryable: boolean;
      r2_probe?: {
        attempted: boolean;
        skipped_reason?: string;
        key_checked?: string;
        exists?: boolean;
        error?: { name: string; message: string; statusCode?: number | null };
      };
      render_state: {
        rendered_pages_r2_present: boolean;
        rendered_pages_count: number;
        rendered_pages_rendered: number | null;
      };
    }> = [];

    const parseIntWithDefault = (input: unknown, fallback: number): number => {
      const v = Number.parseInt(String(input ?? ""), 10);
      return Number.isFinite(v) ? v : fallback;
    };
    const renderChunkSize = Math.max(1, Math.min(1000, parseIntWithDefault(process.env.VISUAL_PAGE_IMAGE_MAX_PAGES, 10)));
    const toEnqueueRender = new Map<string, { count: number; rendered: number | null }>();

    let visualCandidates = 0;

    const pad4 = (n: number) => String(Math.max(0, Math.trunc(n))).padStart(4, "0");

    const isProd = process.env.NODE_ENV === "production";
    const envFlag = (key: string): boolean => {
      const raw = process.env[key];
      if (typeof raw !== "string") return false;
      const v = raw.trim().toLowerCase();
      return v === "1" || v === "true" || v === "yes";
    };

    // Local-dev fallback: when storage driver is local, treat locally-rendered pages under UPLOAD_DIR as ready.
    // Worker writes page images to `${UPLOAD_DIR}/rendered_pages/<safeDocumentId>/page_%04d.png`.
    const uploadsRootDir = getUploadsRootDir();
    const r2Enabled = getStorageDriver(process.env) === "r2";
    const devLocalFallbackEnabled = !isProd && !r2Enabled && envFlag("DDAI_DEV_LOCAL_FALLBACK");
    const localFallbackUsedDocIds: string[] = [];
    const safeDocIdForPath = (documentId: string) => String(documentId || "").replace(/[^a-zA-Z0-9_\-]/g, "_");
    const localRenderedPagesDirForDoc = (documentId: string) =>
      path.resolve(uploadsRootDir, "rendered_pages", safeDocIdForPath(documentId));
    const hasLocalRenderedPages = (documentId: string): { ok: boolean; count: number } => {
      try {
        const dir = localRenderedPagesDirForDoc(documentId);
        const names = fs.readdirSync(dir);
        const count = (names || []).filter((n) => /^page_\d{4}\.png$/i.test(String(n))).length;
        return { ok: count > 0, count };
      } catch {
        return { ok: false, count: 0 };
      }
    };

    const renderedPageKeyForIndex = (renderedR2: any, pageIndex: number): string | null => {
      const prefix = typeof renderedR2?.prefix === "string" ? renderedR2.prefix : null;
      const fmt = typeof renderedR2?.format === "string" && renderedR2.format.trim().length > 0 ? renderedR2.format.trim() : "page_%04d.png";
      if (!prefix) return null;

      const cleanPrefix = prefix.replace(/^\/+/, "").replace(/\/+$/, "");
      let fileName = fmt;
      if (fileName.includes("%04d")) fileName = fileName.replace("%04d", pad4(pageIndex));
      else if (fileName.includes("%d")) fileName = fileName.replace("%d", String(pageIndex));
      else fileName = `page_${pad4(pageIndex)}.png`;

      return `${cleanPrefix}/${fileName}`;
    };

    const maxR2Probes = 10;
    let r2ProbesUsed = 0;
    const r2ProbeOverrides: Array<{
      document_id: string;
      key_checked: string;
      exists: boolean;
      error?: { name: string; message: string; statusCode?: number | null };
    }> = [];

    for (const d of docs ?? []) {
      const caps = getDocumentCapabilities({
        fileName: typeof d?.file_name === "string" ? d.file_name : null,
        mimeType: typeof (d as any)?.mime_type === "string" ? String((d as any).mime_type) : null,
      });
      if (!caps.visualExtractable) continue;
      visualCandidates += 1;

      const metaObj = d?.extraction_metadata && typeof d.extraction_metadata === "object" ? (d.extraction_metadata as any) : null;
      const renderedR2 = metaObj?.rendered_pages_r2 && typeof metaObj.rendered_pages_r2 === "object" ? (metaObj.rendered_pages_r2 as any) : null;
      const count = typeof metaObj?.rendered_pages_count === "number" && Number.isFinite(metaObj.rendered_pages_count) ? metaObj.rendered_pages_count : 0;
      const rendered = typeof metaObj?.rendered_pages_rendered === "number" && Number.isFinite(metaObj.rendered_pages_rendered) ? metaObj.rendered_pages_rendered : null;

      if (!renderedR2) {
        // If storage driver is local (typical local dev), allow local rendered pages to satisfy readiness
        // only when explicitly enabled.
        if (devLocalFallbackEnabled) {
          const local = hasLocalRenderedPages(d.id);
          if (local.ok) {
            readyDocIds.push(d.id);
            localFallbackUsedDocIds.push(d.id);
            continue;
          }
        }
        blocked.push({
          document_id: d.id,
          failure_reason: "rendered_pages_r2_missing",
          next_action: "enqueue_render_document_pages",
          retryable: true,
          render_state: { rendered_pages_r2_present: false, rendered_pages_count: count, rendered_pages_rendered: rendered },
        });
        if (caps.supports_page_rendering) toEnqueueRender.set(d.id, { count, rendered });
        continue;
      }
      if (!count || count <= 0) {
        blocked.push({
          document_id: d.id,
          failure_reason: "rendered_pages_count_missing",
          next_action: "enqueue_render_document_pages",
          retryable: true,
          render_state: { rendered_pages_r2_present: true, rendered_pages_count: count, rendered_pages_rendered: rendered },
        });
        if (caps.supports_page_rendering) toEnqueueRender.set(d.id, { count, rendered });
        continue;
      }
      if (rendered == null || rendered < count) {
        // Cheap R2 probe: if the last expected page exists, treat rendering as effectively complete.
        // This prevents stale rendered_pages_rendered metadata from forcing persistent 409s.
        let r2Probe:
          | {
              attempted: boolean;
              skipped_reason?: string;
              key_checked?: string;
              exists?: boolean;
              error?: { name: string; message: string; statusCode?: number | null };
            }
          | undefined;
        if (r2ProbesUsed < maxR2Probes) {
          const lastIndex = Math.max(0, count - 1);
          const key = renderedPageKeyForIndex(renderedR2, lastIndex);
          if (key) {
            r2ProbesUsed += 1;
            try {
              const res = await (r2.objectExistsInR2 ?? objectExistsInR2)({ key });
              r2Probe = { attempted: true, key_checked: key, exists: res.exists, error: res.error };
              if (res.exists) {
                readyDocIds.push(d.id);
                r2ProbeOverrides.push({ document_id: d.id, key_checked: key, exists: true, error: res.error });
                continue;
              }
            } catch (err) {
              const e = err as any;
              r2Probe = {
                attempted: false,
                skipped_reason: "r2_not_configured_or_unavailable",
                error: {
                  name: typeof e?.name === "string" ? e.name : "R2ProbeError",
                  message: typeof e?.message === "string" ? e.message : String(err),
                },
              };
            }
          }
        } else {
          r2Probe = { attempted: false, skipped_reason: "probe_limit_reached" };
        }

        blocked.push({
          document_id: d.id,
          failure_reason: "render_incomplete",
          next_action: "enqueue_render_document_pages",
          retryable: true,
          render_state: { rendered_pages_r2_present: true, rendered_pages_count: count, rendered_pages_rendered: rendered },
          ...(r2Probe ? { r2_probe: r2Probe } : {}),
        });
        if (caps.supports_page_rendering) toEnqueueRender.set(d.id, { count, rendered });
        continue;
      }
      readyDocIds.push(d.id);
    }

    // Governance disclosure: surface any metadata override used to mark a document ready.
    if (r2ProbeOverrides.length > 0) {
      request.log.info(
        {
          event: "GOVERNANCE_DISCLOSURE",
          code: "r2_probe_overrode_render_metadata",
          deal_id: dealId,
          overrides: r2ProbeOverrides,
          attempted: r2ProbesUsed,
          max_attempted: maxR2Probes,
          node_env: process.env.NODE_ENV,
        },
        "deal.extract_visuals.governance_disclosure"
      );
    }

    if (localFallbackUsedDocIds.length > 0) {
      request.log.info(
        {
          event: "GOVERNANCE_DISCLOSURE",
          code: "dev_local_rendered_pages_fallback",
          deal_id: dealId,
          document_ids: localFallbackUsedDocIds,
          uploads_root_dir: uploadsRootDir,
          node_env: process.env.NODE_ENV,
        },
        "deal.extract_visuals.governance_disclosure"
      );
    }

    // Best-effort: if render isn't ready, kick render jobs now (idempotent via per-document dedupe).
    // This helps avoid deals getting stuck when upstream enqueue didn't happen (or workers restarted mid-flight).
    const renderEnqueueResults: Array<{ document_id: string; job_id: string; status: string }> = [];
    if (toEnqueueRender.size > 0) {
      // Guardrail: don't spam Redis if a deal has a huge document set.
      const maxDocs = 25;
      const candidates = Array.from(toEnqueueRender.entries()).slice(0, maxDocs);

      await Promise.all(
        candidates.map(async ([documentId, state]) => {
          try {
            const count = state.count;
            const pageStart = 0;
            const pageEnd = Math.max(1, count > 0 ? Math.min(count, renderChunkSize) : renderChunkSize);

            const job = await enqueue(
              {
                deal_id: dealId,
                document_id: documentId,
                type: "render_document_pages",
                payload: { page_start: pageStart, page_end: pageEnd },
              },
              { dedupe: { by: "document" } }
            );

            renderEnqueueResults.push({ document_id: documentId, job_id: job.job_id, status: job.status });
          } catch {
            // Best-effort: keep API response deterministic even if Redis is briefly unavailable.
          }
        })
      );
    }

    if (readyDocIds.length === 0) {
      if (visualCandidates === 0) {
        return reply.status(422).send({
          error: "no_visual_documents",
          message: "No visual-extractable documents found for this deal.",
        });
      }
      return reply.status(409).send({
        error: "rendered_pages_not_ready",
        message: "No documents have completed rendered page images yet. Run re-extract / wait for rendering, then retry.",
        readiness_reason: "blocked_by_render_readiness",
        next_action: "wait_or_enqueue_render_document_pages",
        render_state: { visual_documents_total: visualCandidates, ready_documents: 0, blocked_documents: blocked.length },
        blocked_documents: blocked,
        r2_probe_summary: { attempted: r2ProbesUsed, overrides: r2ProbeOverrides.length, max_attempted: maxR2Probes },
        r2_probe_overrides: r2ProbeOverrides,
        render_jobs_enqueued: renderEnqueueResults,
      });
    }

    // Single job; scope to only the ready docs to avoid ingest_not_complete guard failures.
    // force_resegment updates segment_key for existing structured synthetic assets (pptx/docx/xlsx)
    // before extracting visuals.
    const payload = {
      document_ids: readyDocIds,
      force_resegment: forceResegment,
      force_reextract: forceReextract,
      enqueue_deep_scan: enqueueDeepScan,
      ...(requestId || source || idempotencyKey || actorUserId || actorOrgId
        ? {
            request_context: {
              request_id: requestId,
              idempotency_key: idempotencyKey,
              source,
              actor_user_id: actorUserId,
              actor_org_id: actorOrgId,
            },
          }
        : {}),
    };

    let job:
      | { job_id: string; status: string }
      | ({ job_id: string; status: string; idempotent?: boolean } & Record<string, any>);

    if (idempotencyKey) {
      try {
        job = await runIdempotentOperation({
          deal_id: dealId,
          operation: "extract_visuals",
          idempotency_key: idempotencyKey,
          poolOverride: pool as any,
          runDb: async (client) => {
            const inserted = await insertJobRow(
              {
                deal_id: dealId,
					type: "extract_visuals_deal",
					queue: "extract_visuals",
                payload,
              },
              { dedupe: { by: "deal" }, deps: { pool: client as any } }
            );

            // Return enough information to enqueue after commit.
            return {
              job_id: inserted.job_id,
              status: inserted.status,
              bullPayload: inserted.bullPayload,
            };
          },
          afterCommit: async (dbResult) => {
            try {
              await enqueueBullmqJob(
                {
						type: "extract_visuals_deal",
                  jobId: String(dbResult.job_id),
                  bullPayload: (dbResult as any).bullPayload ?? {},
                },
                { deps: { queue: deps?.jobs?.queue } }
              );
            } catch (err) {
              const errMsg = err instanceof Error ? err.message : String(err);
              const message = sanitizeText(`enqueue_failed: ${errMsg}`);
              const jobId = sanitizeText(String(dbResult.job_id));

              // Ensure deterministic behavior: if Redis enqueue fails after commit, mark the job row failed.
              // Use the regular pool client (not the transaction client) since we're after COMMIT.
              try {
                await pool.query(
                  `UPDATE jobs
                      SET status = 'failed',
                          message = $2,
                          updated_at = now()
                    WHERE job_id = $1`,
                  [jobId, message]
                );
              } catch {
                // Best-effort.
              }

              // Optional: touch idempotency updated_at to reflect the failure path.
              try {
                await pool.query(
                  `UPDATE job_idempotency
                      SET updated_at = now()
                    WHERE deal_id = $1
                      AND operation = $2
                      AND idempotency_key = $3`,
                  [sanitizeText(dealId), sanitizeText("extract_visuals"), sanitizeText(idempotencyKey)]
                );
              } catch {
                // Best-effort.
              }

              throw new AfterCommitEnqueueError(jobId, err);
            }
          },
        });
      } catch (err) {
        if (err instanceof AfterCommitEnqueueError) {
          job = { job_id: err.jobId, status: "failed" };
        } else {
          throw err;
        }
      }
    } else {
      job = await enqueue(
        {
          deal_id: dealId,
				type: "extract_visuals_deal",
				queue: "extract_visuals",
          payload,
        },
        { dedupe: { by: "deal" } }
      );
    }
    return reply.status(202).send({
      job_id: job.job_id,
      status: job.status,
      readiness_reason:
        r2ProbeOverrides.length > 0
          ? "r2_probe_overrode_metadata"
          : localFallbackUsedDocIds.length > 0
            ? "local_rendered_pages_present"
            : "metadata_ready",
      ready_documents: readyDocIds,
      blocked_documents: blocked,
      r2_probe_summary: { attempted: r2ProbesUsed, overrides: r2ProbeOverrides.length, max_attempted: maxR2Probes },
      r2_probe_overrides: r2ProbeOverrides,
      render_jobs_enqueued: renderEnqueueResults,
    });
  });

  // Enqueue a deep scan pass for visuals in the deal.
  // This forces the lightweight vision-understanding model for pages that still lack semantic hints.
  app.post("/api/v1/deals/:deal_id/deep-scan-visuals", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;
    const forceRefresh = Boolean((request.body as any)?.force_refresh);

    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );

    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const job = await enqueueJob(
      {
        deal_id: dealId,
        type: "deep_scan_visuals",
        payload: { force_refresh: forceRefresh },
      },
      { dedupe: { by: "deal" } }
    );

    return reply.status(202).send({ job_id: job.job_id, status: job.status });
  });

  // Canonicalize extracted data (artifact cleanup) + re-verify documents.
  // This does NOT re-extract from original binaries (those are only available at upload time).
  app.post("/api/v1/deals/:deal_id/remediate-extraction", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;

    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );

    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const includeWarnings = Boolean((request.body as any)?.include_warnings);

    const job = await enqueueJob({
      deal_id: dealId,
      type: "remediate_extraction",
      payload: { include_warnings: includeWarnings },
    });

    return reply.status(202).send({ job_id: job.job_id, status: job.status });
  });

  // Auto-check and progress deal stage based on metrics
  app.post("/api/v1/deals/:deal_id/auto-progress", async (request, reply) => {
    const dealId = (request.params as { deal_id: string }).deal_id;

    const { rows } = await pool.query<DealRow>(
      `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
      [dealId]
    );

    if (rows.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    const result = await autoProgressDealStage(pool as any, dealId);

    if (result.progressed) {
      return reply.status(200).send({
        progressed: true,
        newStage: result.newStage,
        message: result.reason
          ? `Deal automatically progressed from ${rows[0].stage} to ${result.newStage}. ${result.reason}`
          : `Deal automatically progressed from ${rows[0].stage} to ${result.newStage}`
      });
    }

    return reply.status(200).send({
      progressed: false,
      currentStage: rows[0].stage,
      message: result.reason ?? "Deal does not meet conditions for stage progression"
    });
  });

  // Recalculate priority for a single deal
  app.post<{ Params: { dealId: string } }>("/api/v1/deals/:dealId/recalculate-priority", async (request, reply) => {
    const { dealId } = request.params;
    const pool = getPool();

    try {
      // Verify deal exists
      const { rows } = await pool.query(
        `SELECT id, name, priority FROM deals WHERE id = $1 AND deleted_at IS NULL`,
        [dealId]
      );

      if (!rows.length) {
        return reply.status(404).send({ error: "Deal not found" });
      }

      const oldPriority = rows[0].priority;

      // Recalculate priority
      await updateDealPriority(dealId);

      // Get updated priority
      const { rows: updatedRows } = await pool.query(
        `SELECT priority FROM deals WHERE id = $1`,
        [dealId]
      );

      return reply.status(200).send({
        dealId,
        name: rows[0].name,
        oldPriority,
        newPriority: updatedRows[0].priority,
        message: `Priority recalculated for deal ${rows[0].name}`
      });
    } catch (error) {
      console.error(`Error recalculating priority for deal ${dealId}:`, error);
      return reply.status(500).send({ error: "Failed to recalculate priority" });
    }
  });

  // Recalculate priority for all deals
  app.post("/api/v1/deals/batch/recalculate-priorities", async (request, reply) => {
    const pool = getPool();

    try {
      const result = await updateAllDealPriorities();

      return reply.status(200).send({
        message: "All deal priorities recalculated",
        stats: result,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      console.error("Error recalculating all priorities:", error);
      return reply.status(500).send({ error: "Failed to recalculate priorities" });
    }
  });

  // ── Status Summary helper ─────────────────────────────────────────────────
  // Returns a normalised status_summary combining the latest analyze_deal job
  // and the latest investor_insight_reports row. Used by GET /investor-insights
  // so the UI has a single source of truth for display state — never derives it
  // from raw table values.
  //
  // Key invariants:
  //   - analysis succeeded but report missing → report_status "not_started",
  //     NOT "analysis failed"
  //   - report row exists with render_package → has_existing_render_package true
  //     AND blocking_reason null (show the existing report, never full-screen block)
  //   - analysis/report failed AND no render_package → blocking_reason set so UI
  //     can surface the right CTA
}
