/**
 * apps/api/src/routes/deals/deal-analysis.routes.ts
 * registerDealAnalysisRoutes — extracted from deals.ts (PR12)
 * AUTO-GENERATED by scripts/dev/split-deals-final.py
 */
import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import { fetchPhaseBVisualsFromDb } from "../../lib/phaseb-visuals";
import { getUploadsRootDir } from "../../plugins/uploads-static";
import { getPool } from "../../lib/db";
import { resolveVisualAssetImageUriForApi } from "../../lib/visual-asset-image-uri";
import type { Deal } from "@dealdecision/contracts";
import type { JobStatus, JobType } from "@dealdecision/contracts";
import { QUEUE_NAMES } from "@dealdecision/core";
import { enqueueBullmqJob, enqueueJob, insertJobRow } from "../../services/jobs";
import { getQueues } from "../../lib/queue";
import { runIdempotentOperation } from "../../lib/jobs";
import { getStorageDriver } from "../../lib/storage-contract";
import { autoProgressDealStage } from "../../services/stageProgression";
import { updateDealPriority, updateAllDealPriorities } from "../../services/priorityClassification";
import { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";
import { getNodeEvidenceGateForDeal } from "../../services/nodeEvidenceGateForDeal";
import { normalizeDealName } from "../../lib/normalize-deal-name";
import { buildDocumentsDigest } from "../../lib/documents-digest";
import type { DocumentsDigestV1 } from "../../lib/documents-digest";
import { objectExistsInR2 } from "../../lib/r2";
import {
  purgeDealCascade,
  isPurgeDealNotFoundError,
  sanitizeText,
  getDocumentCapabilities,
  buildDealScoringInputV0FromLineage,
  getSegmentConfidenceThresholds,
  detectContentArchetypeTags,
  buildOrchestratorReportV1,
} from "@dealdecision/core";
import {
  BrandModel,
  PageInput,
  buildBrandModel,
  inferDocumentBrandName,
  inferSlideTitleForSlide,
  isLikelyGarbledSlideTitle,
  normalizePhrase,
} from "../../lib/slide-title";
import {
  buildClassificationText,
  buildSegmentFeatures,
  classifySegment,
  normalizeAnalystSegment,
  type AnalystSegment,
  type SegmentClassifierInput,
} from "../../lib/analyst-segment";
import {
  groupWordVisualAssetsByDocument,
  groupWordVisualAssetsByDocumentWithStats,
  type WordGroupingStats,
} from "../../lib/word-visual-grouping";
import { fetchPageUnderstandingReadinessForDeal } from "../../lib/deal-page-understanding-readiness";
import { ensureDocumentsReadyForAnalysis } from "../../lib/ensure-documents-ready-for-analysis";
import { getCanonicalFieldsForAI } from "../../lib/canonical-fields-for-ai";
import type {
  QueryResult,
  DealRoutesPool,
  DealRoutesClient,
  DealApiMode,
  AutoProfileDocRow,
  DealRow,
  DIOAggregateRow,
  ScoreBreakdownSectionKey,
  EvidenceRow,
  StatusSummaryAnalysis,
  StatusSummaryReport,
  StatusSummaryEvidenceGate,
  StatusSummary,
} from "./_shared";
import {
  hasTable,
  hasColumn,
  getColumnDataType,
  isUuid,
  stripEvidenceFromExecutiveSummary,
  stripEvidenceFromClaims,
  parseDealApiMode,
  bestEffortReadinessJobPresenceCheck,
  parseBoolQ,
  computeOcrV2CleanText,
  pickNonUnknownSegment,
  majorityNonUnknownSegment,
  isStructuredWordSectionAsset,
  structuredWordContentStats,
  isEmptyStructuredWordSectionAsset,
  computeDocHintSegmentByDocId,
  applyNeighborHintPropagationToAssets,
  buildDeterministicGroupCapturedText,
  extractStructuredWordTextForCue,
  inferStructuredWordCueSegment,
  requireDestructiveAuth,
  dealStageEnum,
  dealPriorityEnum,
  normalizeDealTrend,
  dealTrendEnum,
  dealCreateSchema,
  dealDraftCreateSchema,
  dealConfirmProfileSchema,
  sanitizeProfileValue,
  extractLabeledValue,
  isGenericCandidateName,
  deriveNameFromFilenameLike,
  extractCompanyFromEarlyText,
  computeAutoProfileFromDocuments,
  normalizeWarningsForPersistence,
  jsonbParam,
  dealUpdateSchema,
  llmPhaseModeEnum,
  parseNullableNumber,
  SCORE_BREAKDOWN_SECTION_ORDER,
  CLAIM_CATEGORY_SECTION_MAP,
  normalizeCategory,
  sectionForCategory,
  buildScoreBreakdownV1,
  collectEvidenceIdsFromClaims,
  getEvidenceByIds,
  getDocumentIndex,
  fetchEvidenceSamplesBySection,
  normalizeEvidenceSnippet,
  BUSINESS_MODEL_STRONG_REGEX,
  deriveSectionKeyFromClaim,
  ensureEvidenceLinksForClaims,
  buildPhase1ScoreEvidence,
  buildScoreEvidenceFromBreakdown,
  mapDeal,
  safeJsonValue,
  ocrSnippet,
  deriveStructuredSummary,
  cueRescueLowSignal,
  deriveBestExtractionConfidence,
  mapAnalysisJobStatus,
  mapReportRowStatus,
  maxIsoTs,
  buildStatusSummary,
} from "./_shared";

export async function registerDealAnalysisRoutes(
  app: FastifyInstance,
  pool: DealRoutesPool,
  enqueue: typeof enqueueJob,
  r2: { objectExistsInR2: typeof objectExistsInR2 },
  debugRoutesEnabled: boolean,
  deps?: {
    enqueueJob?: typeof enqueueJob;
    jobs?: { queue?: any };
    r2?: { objectExistsInR2?: typeof objectExistsInR2 };
    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };
  }
): Promise<void> {
  app.post("/api/v1/deals/:deal_id/analysis/deal-terms", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    const bodyParsed = z.object({
      canonical_fields: z.record(z.string(), z.string().nullable()),
      raise_terms_raw: z.string().optional(),
      stage: z.string().optional(),
    }).safeParse(request.body);
    if (!bodyParsed.success) {
      return reply.status(400).send({ error: "invalid_body", message: "canonical_fields must be an object" });
    }
    const { canonical_fields: rawFields, raise_terms_raw, stage } = bodyParsed.data;
    const { canonical_fields } = getCanonicalFieldsForAI({ canonical_fields: rawFields, raise_terms_raw, stage });

    // Verify deal exists
    const { rows: dealRows } = await pool.query<{ id: string }>(
      `SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL LIMIT 1`,
      [dealId],
    );
    if (!dealRows.length) {
      return reply.status(404).send({ error: "deal_not_found" });
    }

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return reply.status(503).send({ error: "llm_unavailable", message: "OPENAI_API_KEY not configured" });
    }

    // Build a field-fact list for the LLM user prompt
    const FIELD_LABELS: Record<string, string> = {
      raise_amount: "Raise amount",
      raise_round: "Round",
      raise_instrument: "Instrument",
      raise_cap: "Valuation cap",
      raise_discount: "Discount rate",
      note_interest_rate: "Note interest rate",
      note_maturity: "Note maturity",
      valuation_pre: "Pre-money valuation",
      valuation_post: "Post-money valuation",
      valuation_safe_cap: "SAFE cap",
    };

    const fieldLines = Object.entries(FIELD_LABELS)
      .map(([key, label]) => {
        const val = canonical_fields[key];
        return `${label}: ${val ?? "not disclosed"}`;
      })
      .join("\n");

    const systemPrompt =
      "You are an institutional investment analyst summarizing deal structure for internal evaluation. " +
      "Write analytically. Do not repeat field names. Explain implications of structure. " +
      "If terms are missing, explicitly state that they are not disclosed. " +
      "Return ONLY a JSON object with these exact keys:\n" +
      '  "structure_summary": string (2–4 sentences, raise details in first sentence),\n' +
      '  "structure_assessment": { "simplicity": "High"|"Medium"|"Low", "dilution_visibility": "High"|"Medium"|"Low", "valuation_clarity": "High"|"Medium"|"Low", "downside_protection": "High"|"Medium"|"Low" },\n' +
      '  "missing_terms": string[] (names of undisclosed key terms; empty array if none)\n' +
      "Rules:\n" +
      "- If SAFE and no cap/discount → dilution_visibility = Low.\n" +
      "- If no valuation terms → valuation_clarity = Low.\n" +
      "- If no downside mechanics (interest, maturity, liquidation preference) → downside_protection = Low.\n" +
      "- No invented numbers. No marketing language.";

    const userPrompt =
      "Summarize the deal structure for these canonical terms:\n\n" + fieldLines;

    const model = process.env.OPENAI_MODEL_DEAL_TERMS || "gpt-4o-mini";

    let rawContent: string;
    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.15,
          max_tokens: 500,
          response_format: { type: "json_object" },
        }),
      });

      if (!res.ok) {
        const text = await res.text().catch(() => "");
        console.error("[deal-terms-analysis] openai_error", { dealId, status: res.status, text });
        return reply.status(502).send({ error: "llm_error", message: `OpenAI returned ${res.status}` });
      }

      type OAIResp = { choices: Array<{ message?: { content?: string } }>; model: string };
      const json = (await res.json()) as OAIResp;
      rawContent = json.choices?.[0]?.message?.content?.trim() ?? "";
    } catch (err) {
      console.error("[deal-terms-analysis] fetch_error", { dealId, err: err instanceof Error ? err.message : String(err) });
      return reply.status(502).send({ error: "llm_error", message: "OpenAI request failed" });
    }

    if (!rawContent) {
      return reply.status(502).send({ error: "llm_empty_response" });
    }

    let parsed2: {
      structure_summary: string;
      structure_assessment: {
        simplicity: string;
        dilution_visibility: string;
        valuation_clarity: string;
        downside_protection: string;
      };
      missing_terms: string[];
    };

    try {
      parsed2 = JSON.parse(rawContent);
    } catch {
      console.error("[deal-terms-analysis] json_parse_error", { dealId, rawContent: rawContent.slice(0, 200) });
      return reply.status(502).send({ error: "llm_parse_error", message: "LLM returned non-JSON" });
    }

    const validLevels = new Set(["High", "Medium", "Low"]);
    const assessment = parsed2.structure_assessment ?? {};
    const normalize = (v: unknown): "High" | "Medium" | "Low" =>
      validLevels.has(String(v)) ? (String(v) as "High" | "Medium" | "Low") : "Low";

    return reply.send({
      structure_summary: typeof parsed2.structure_summary === "string" ? parsed2.structure_summary : "",
      structure_assessment: {
        simplicity: normalize(assessment.simplicity),
        dilution_visibility: normalize(assessment.dilution_visibility),
        valuation_clarity: normalize(assessment.valuation_clarity),
        downside_protection: normalize(assessment.downside_protection),
      },
      missing_terms: Array.isArray(parsed2.missing_terms)
        ? parsed2.missing_terms.filter((t): t is string => typeof t === "string")
        : [],
    });
  });

  // ── AI Analysis Tab: Market Analysis Synthesis ────────────────────────────
  // POST /api/v1/deals/:deal_id/analysis/market
  //
  // Lightweight LLM synthesis endpoint used EXCLUSIVELY by the AI Analysis Tab
  // MarketAnalysisCard component. Does NOT touch the investor insights pipeline.
  //
  // Input:  { canonical_fields: Record<string, string | null>, deal_name?: string }
  // Output: schema_version, score, kpis, strengths, concerns, ai_insight, missing_inputs
  app.post("/api/v1/deals/:deal_id/analysis/market", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    const bodyParsed = z.object({
      canonical_fields: z.record(z.string(), z.string().nullable()),
      deal_name: z.string().optional(),
    }).safeParse(request.body);
    if (!bodyParsed.success) {
      return reply.status(400).send({ error: "invalid_body", message: "canonical_fields must be an object" });
    }
    const { canonical_fields, deal_name } = bodyParsed.data;

    // Verify deal exists
    const { rows: dealRows } = await pool.query<{ id: string }>(
      `SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL LIMIT 1`,
      [dealId],
    );
    if (!dealRows.length) {
      return reply.status(404).send({ error: "deal_not_found" });
    }

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return reply.status(503).send({ error: "llm_unavailable", message: "OPENAI_API_KEY not configured" });
    }

    // Field labels for the prompt
    const MARKET_FIELD_LABELS: Record<string, string> = {
      tam: "Total Addressable Market (TAM)",
      sam: "Serviceable Addressable Market (SAM)",
      som: "Serviceable Obtainable Market (SOM)",
      growth_rate: "Market/Revenue Growth Rate",
      customer_count: "Current Customer Count",
      market_category: "Market Category / Vertical",
      market_geography: "Target Geography",
      icp: "Ideal Customer Profile (ICP)",
      pricing_model: "Pricing Model",
      competition: "Key Competitors",
    };

    const missingInputs: string[] = [];
    const fieldLines = Object.entries(MARKET_FIELD_LABELS)
      .map(([key, label]) => {
        const val = canonical_fields[key];
        if (!val) missingInputs.push(label);
        return `${label}: ${val ?? "not disclosed"}`;
      })
      .join("\n");

    const dealContext = deal_name ? `Deal: ${deal_name}\n\n` : "";

    const PLACEHOLDER_RE = /startup corp|\[company\]|\[name\]|<company>|example company/i;

    const systemPrompt =
      "You are an institutional investment analyst evaluating market opportunity for a startup. " +
      "Write analytically and concisely. Use conservative language when evidence is weak: " +
      "\"materials suggest…\", \"not disclosed…\", \"based on provided data…\". " +
      "RULES:\n" +
      "- Do NOT invent TAM/SAM/SOM values if they are not provided.\n" +
      "- Do NOT guess geographic markets; if not disclosed write exactly: \"Not disclosed\".\n" +
      "- Do NOT use placeholder company names like 'Startup Corp' or '[Company]'.\n" +
      "- score must be an integer 0–100 based on quality/quantity of market evidence provided.\n" +
      "- strengths and concerns must each have 2–6 items.\n" +
      "- ai_insight must be 1–4 sentences and must not introduce new numbers not present in the inputs.\n" +
      "- kpi.tailwind: characterise overall market momentum (e.g., 'Strong upward trend', 'Moderate growth', 'Not disclosed').\n" +
      "- kpi.launch_plan: describe market entry readiness signal (e.g., 'ICP defined', 'Early traction', 'Pre-launch', 'Not disclosed').\n" +
      "- kpi.priority_markets: first target geography or segment (e.g., 'US / SMB', 'Enterprise — North America') — write 'Not disclosed' if unknown.\n" +
      "Return ONLY a valid JSON object with these exact keys:\n" +
      '  "schema_version": "market_analysis_v1",\n' +
      '  "score": number,\n' +
      '  "kpis": { "tailwind": string, "launch_plan": string, "priority_markets": string },\n' +
      '  "strengths": string[],\n' +
      '  "concerns": string[],\n' +
      '  "ai_insight": string,\n' +
      '  "missing_inputs": string[]\n';

    const userPrompt =
      dealContext +
      "Evaluate the market opportunity based on these canonical fields:\n\n" +
      fieldLines;

    const model = process.env.OPENAI_MODEL_MARKET_ANALYSIS || process.env.OPENAI_MODEL_DEAL_TERMS || "gpt-4o-mini";

    let rawContent: string;
    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.15,
          max_tokens: 600,
          response_format: { type: "json_object" },
        }),
      });

      if (!res.ok) {
        const text = await res.text().catch(() => "");
        console.error("[market-analysis] openai_error", { dealId, status: res.status, text });
        return reply.status(502).send({ error: "llm_error", message: `OpenAI returned ${res.status}` });
      }

      type OAIResp = { choices: Array<{ message?: { content?: string } }>; model: string };
      const json = (await res.json()) as OAIResp;
      rawContent = json.choices?.[0]?.message?.content?.trim() ?? "";
    } catch (err) {
      console.error("[market-analysis] fetch_error", { dealId, err: err instanceof Error ? err.message : String(err) });
      return reply.status(502).send({ error: "llm_error", message: "OpenAI request failed" });
    }

    if (!rawContent) {
      return reply.status(502).send({ error: "llm_empty_response" });
    }

    let parsedMarket: {
      schema_version?: string;
      score?: unknown;
      kpis?: { tailwind?: unknown; launch_plan?: unknown; priority_markets?: unknown };
      strengths?: unknown;
      concerns?: unknown;
      ai_insight?: unknown;
      missing_inputs?: unknown;
    };

    try {
      parsedMarket = JSON.parse(rawContent);
    } catch {
      console.error("[market-analysis] json_parse_error", { dealId, rawContent: rawContent.slice(0, 200) });
      return reply.status(502).send({ error: "llm_parse_error", message: "LLM returned non-JSON" });
    }

    // ── Validator ───────────────────────────────────────────────────────────
    const safeStr = (v: unknown, fallback = ""): string =>
      typeof v === "string" && v.trim().length > 0 ? v.trim() : fallback;

    const safeStrArr = (v: unknown, min = 2, max = 6): string[] => {
      if (!Array.isArray(v)) return [];
      const filtered = v.filter((x): x is string => typeof x === "string" && x.trim().length > 0);
      return filtered.slice(0, max);
    };

    const rawScore = Number(parsedMarket.score);
    const score = Number.isFinite(rawScore) && rawScore >= 0 && rawScore <= 100
      ? Math.round(rawScore)
      : 0;

    const kpisRaw = parsedMarket.kpis ?? {};
    const tailwind     = safeStr(kpisRaw.tailwind, "Not disclosed");
    const launchPlan   = safeStr(kpisRaw.launch_plan, "Not disclosed");
    const priorityMkts = safeStr(kpisRaw.priority_markets, "Not disclosed");

    // Reject placeholder company names
    if (
      PLACEHOLDER_RE.test(tailwind) ||
      PLACEHOLDER_RE.test(launchPlan) ||
      PLACEHOLDER_RE.test(priorityMkts)
    ) {
      console.error("[market-analysis] placeholder_detected", { dealId, tailwind, launchPlan, priorityMkts });
      return reply.status(502).send({ error: "llm_quality_error", message: "LLM response contained placeholder values" });
    }

    const strengths = safeStrArr(parsedMarket.strengths, 2, 6);
    const concerns  = safeStrArr(parsedMarket.concerns, 2, 6);
    const aiInsight = safeStr(parsedMarket.ai_insight, "");

    // Merge LLM missing_inputs with our own detected missing fields
    const llmMissing = Array.isArray(parsedMarket.missing_inputs)
      ? parsedMarket.missing_inputs.filter((x): x is string => typeof x === "string")
      : [];
    const allMissing = Array.from(new Set([...missingInputs, ...llmMissing]));

    return reply.send({
      schema_version: "market_analysis_v1",
      score,
      kpis: { tailwind, launch_plan: launchPlan, priority_markets: priorityMkts },
      strengths,
      concerns,
      ai_insight: aiInsight,
      missing_inputs: allMissing,
    });
  });

  // ── AI Analysis Tab: Financial Analysis AI Narrative ──────────────────────
  // POST /api/v1/deals/:deal_id/analysis/financial-analysis
  //
  // Produces the AI Governed narrative panel only.  All deterministic data
  // (score, KPI tiles, revenue table, highlights) is computed client-side in
  // FinancialAnalysisSection.tsx.  This endpoint synthesises 2–4 narrative
  // paragraphs, 3–6 strengths, and 3–6 considerations from the structured
  // financial signals sent by the client.
  //
  // Input payload:
  //   { deal_name?, layout_coverage_pct?, has_statement, has_implied_allocation,
  //     has_health_metrics, revenue_latest?, gross_margin_pct?,
  //     total_annual_cost?, reconciliation_confidence?, warn_fail_flags?,
  //     missing_sections? }
  //
  // Output: schema_version, summary_paragraphs, strengths, considerations
  app.post("/api/v1/deals/:deal_id/analysis/financial-analysis", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    const bodySchema = z.object({
      deal_name:                 z.string().optional(),
      layout_coverage_pct:       z.number().optional(),
      has_statement:             z.boolean(),
      has_implied_allocation:    z.boolean(),
      has_health_metrics:        z.boolean(),
      revenue_latest:            z.string().optional(),
      gross_margin_pct:          z.string().optional(),
      total_annual_cost:         z.string().optional(),
      reconciliation_confidence: z.number().min(0).max(1).optional(),
      warn_fail_flags:           z.array(z.string()).optional(),
      missing_sections:          z.array(z.string()).optional(),
      // Deck financial signals (PDF/PPT-only deals)
      has_deck_signals:          z.boolean().optional(),
      deck_has_revenue:          z.boolean().optional(),
      deck_has_arr_mrr:          z.boolean().optional(),
      deck_has_burn:             z.boolean().optional(),
      deck_has_runway:           z.boolean().optional(),
      deck_has_unit_economics:   z.boolean().optional(),
      deck_revenue_snippets:     z.array(z.string()).optional(),
      deck_burn_snippets:        z.array(z.string()).optional(),
      deck_pages_scanned:        z.number().optional(),
    });

    const bodyParsed = bodySchema.safeParse(request.body);
    if (!bodyParsed.success) {
      return reply.status(400).send({ error: "invalid_body", message: "request body failed schema validation" });
    }
    const fin = bodyParsed.data;

    // Verify deal exists (no investor_insights, render_package, or other tables)
    const { rows: dealRows } = await pool.query<{ id: string }>(
      `SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL LIMIT 1`,
      [dealId],
    );
    if (!dealRows.length) {
      return reply.status(404).send({ error: "deal_not_found" });
    }

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return reply.status(503).send({ error: "llm_unavailable", message: "OPENAI_API_KEY not configured" });
    }

    // Block requests when there is nothing to analyse
    const hasAnyData = fin.has_statement || fin.has_implied_allocation || fin.has_health_metrics ||
      (fin.has_deck_signals === true && (
        fin.deck_has_revenue || fin.deck_has_arr_mrr || fin.deck_has_burn ||
        fin.deck_has_runway || fin.deck_has_unit_economics
      ));
    if (!hasAnyData) {
      return reply.status(400).send({
        error: "insufficient_data",
        message: "At least one financial section must be present to synthesise a narrative",
      });
    }

    // ── Build structured prompt ─────────────────────────────────────────────
    const dealCtx  = fin.deal_name ? `Deal: ${fin.deal_name}\n\n` : "";
    const isImpliedOnly = fin.has_implied_allocation && !fin.has_statement;

    const signals: string[] = [];
    if (fin.layout_coverage_pct != null) signals.push(`Financial data coverage: ${fin.layout_coverage_pct.toFixed(1)}%`);
    if (fin.has_statement)          signals.push("Revenue/expense statement: available");
    else                            signals.push("Revenue/expense statement: not available");
    if (fin.has_health_metrics)     signals.push("Financial health metrics: available");
    else                            signals.push("Financial health metrics: not available");
    if (fin.has_implied_allocation) signals.push("Implied operational budget allocation: available (estimated from cost model, not stated raise)");
    else                            signals.push("Implied operational budget: not available");
    if (fin.revenue_latest)         signals.push(`Revenue (latest period): ${fin.revenue_latest}`);
    if (fin.gross_margin_pct)       signals.push(`Gross margin: ${fin.gross_margin_pct}`);
    if (fin.total_annual_cost)      signals.push(`Implied annual operating cost: ${fin.total_annual_cost}`);
    if (fin.reconciliation_confidence != null) signals.push(`Reconciliation confidence score: ${fin.reconciliation_confidence.toFixed(2)}`);
    if (fin.warn_fail_flags?.length)  signals.push(`Reconciliation issues: ${fin.warn_fail_flags.join("; ")}`);
    if (fin.missing_sections?.length) signals.push(`Missing financial sections: ${fin.missing_sections.join(", ")}`);

    // Deck-derived signals for PDF/PPT-only deals
    if (fin.has_deck_signals) {
      signals.push("Data source: pitch deck narrative (no structured XLSX available)");
      if (fin.deck_has_revenue || fin.deck_has_arr_mrr) signals.push("Revenue/ARR signals: mentioned in deck");
      else signals.push("Revenue/ARR: not explicitly mentioned in deck");
      if (fin.deck_has_burn)    signals.push("Burn rate: referenced in deck narrative");
      if (fin.deck_has_runway)  signals.push("Cash runway: referenced in deck narrative");
      if (fin.deck_has_unit_economics) signals.push("Unit economics (LTV/CAC): referenced in deck");
      if (fin.deck_revenue_snippets?.length)
        signals.push(`Revenue evidence from deck: ${fin.deck_revenue_snippets.join(" | ")}`);
      if (fin.deck_burn_snippets?.length)
        signals.push(`Burn/runway evidence from deck: ${fin.deck_burn_snippets.join(" | ")}`);
      if (fin.deck_pages_scanned != null)
        signals.push(`Deck pages scanned: ${fin.deck_pages_scanned}`);
    }

    const impliedWarning = isImpliedOnly
      ? "\n\nIMPORTANT: ONLY implied operational budget data is available — no revenue statement exists. " +
        "You MUST use the word \"implied\" when referring to the budget/cost data. " +
        "Do NOT state or infer revenue figures from the cost model alone. " +
        "Do NOT invent financial metrics not present in the inputs.\n"
      : "";

    const systemPrompt =
      "You are an institutional investment analyst synthesising a financial health narrative for an investment memo. " +
      "Your narrative must be balanced, concise, and evidence-grounded.\n\n" +
      "RULES:\n" +
      "- Do NOT invent numbers not present in the inputs.\n" +
      "- If only implied/budget data is present, describe it as 'implied operating cost' and explicitly note that revenue is not yet disclosed.\n" +
      "- If data is absent, state 'not yet available' or 'not disclosed'.\n" +
      "- summary_paragraphs: 2–4 sentences total across all paragraphs.\n" +
      "- strengths: 3–6 bullets, each 1 short sentence.\n" +
      "- considerations: 3–6 bullets, each 1 short sentence.\n" +
      "- Do NOT use placeholder company names like 'Startup Corp' or '[Company]'.\n" +
      impliedWarning +
      "Return ONLY a valid JSON object with exactly these keys:\n" +
      '  "schema_version": "financial_analysis_v1",\n' +
      '  "summary_paragraphs": string[],\n' +
      '  "strengths": string[],\n' +
      '  "considerations": string[]\n';

    const userPrompt =
      dealCtx +
      "Synthesise a financial health narrative from these signals:\n\n" +
      signals.join("\n");

    const model =
      process.env.OPENAI_MODEL_FINANCIAL_ANALYSIS ||
      process.env.OPENAI_MODEL_MARKET_ANALYSIS ||
      process.env.OPENAI_MODEL_DEAL_TERMS ||
      "gpt-4o-mini";

    let rawContent: string;
    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.15,
          max_tokens: 700,
          response_format: { type: "json_object" },
        }),
      });

      if (!res.ok) {
        const text = await res.text().catch(() => "");
        console.error("[financial-analysis] openai_error", { dealId, status: res.status, text });
        return reply.status(502).send({ error: "llm_error", message: `OpenAI returned ${res.status}` });
      }

      type OAIResp = { choices: Array<{ message?: { content?: string } }>; model: string };
      const json = (await res.json()) as OAIResp;
      rawContent = json.choices?.[0]?.message?.content?.trim() ?? "";
    } catch (err) {
      console.error("[financial-analysis] fetch_error", {
        dealId, err: err instanceof Error ? err.message : String(err),
      });
      return reply.status(502).send({ error: "llm_error", message: "OpenAI request failed" });
    }

    if (!rawContent) {
      return reply.status(502).send({ error: "llm_empty_response" });
    }

    let parsedFin: {
      schema_version?: string;
      summary_paragraphs?: unknown;
      strengths?: unknown;
      considerations?: unknown;
    };
    try {
      parsedFin = JSON.parse(rawContent);
    } catch {
      console.error("[financial-analysis] json_parse_error", { dealId, rawContent: rawContent.slice(0, 200) });
      return reply.status(502).send({ error: "llm_parse_error", message: "LLM returned non-JSON" });
    }

    // ── Validators ─────────────────────────────────────────────────────────
    const safeStrArr = (v: unknown, min = 2, max = 6): string[] => {
      if (!Array.isArray(v)) return [];
      const filtered = v
        .filter((x): x is string => typeof x === "string" && x.trim().length > 0)
        .map((x) => x.trim());
      return filtered.slice(0, max);
    };

    const summaryParagraphs = safeStrArr(parsedFin.summary_paragraphs, 1, 4);
    const strengths         = safeStrArr(parsedFin.strengths, 2, 6);
    const considerations    = safeStrArr(parsedFin.considerations, 2, 6);

    // Block responses that would confuse implied cost with revenue
    const PLACEHOLDER_RE = /startup corp|\[company\]|\[name\]|<company>|example company/i;
    const allText = [...summaryParagraphs, ...strengths, ...considerations].join(" ");
    if (PLACEHOLDER_RE.test(allText)) {
      console.error("[financial-analysis] placeholder_detected", { dealId });
      return reply.status(502).send({ error: "llm_quality_error", message: "LLM response contained placeholder values" });
    }

    // When only implied data is available, require the word "implied" somewhere in the narrative
    if (isImpliedOnly && !/implied/i.test(allText)) {
      console.error("[financial-analysis] implied_word_missing", { dealId, isImpliedOnly });
      return reply.status(502).send({
        error: "llm_quality_error",
        message: "Narrative for implied-only data must include the word 'implied'",
      });
    }

    return reply.send({
      schema_version: "financial_analysis_v1",
      summary_paragraphs: summaryParagraphs,
      strengths,
      considerations,
    });
  });

  // ── Risk & Verification narrative ──────────────────────────────────────────
  //
  // POST /api/v1/deals/:deal_id/analysis/risk-verification
  //
  // Generates a lightweight AI narrative from structured verification signals:
  //   gate results, missing critical terms, data conflicts, coverage snapshot,
  //   and financial reconciliation confidence.
  //
  // Input payload (all fields optional but at least one must be substantive):
  //   { deal_name?, gates?, missing_critical_terms?, conflicts?, coverage?,
  //     reconciliation? }
  //
  // Output: schema_version, summary_paragraphs, top_risks, verification_requests
  app.post("/api/v1/deals/:deal_id/analysis/risk-verification", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    const gateSchema = z.object({
      id:     z.string(),
      status: z.enum(["pass", "fail", "not_run"]),
      reason: z.string().optional(),
    });

    const conflictSchema = z.object({
      field:   z.string(),
      value_a: z.string(),
      value_b: z.string(),
    });

    const coverageSchema = z.object({
      docs_count:        z.number().optional(),
      dpu_pages:         z.number().optional(),
      nonempty_pages:    z.number().optional(),
      evidence_count:    z.number().optional(),
      text_coverage_pct: z.number().optional(),
    });

    const reconciliationSchema = z.object({
      confidence_score: z.number().min(0).max(1).optional(),
      flags: z.array(z.object({
        name:   z.string(),
        status: z.enum(["PASS", "WARN", "FAIL", "SKIP"]),
        reason: z.string().optional(),
      })).optional(),
    });

    const bodySchema = z.object({
      deal_name:             z.string().optional(),
      gates:                 z.array(gateSchema).optional(),
      missing_critical_terms: z.array(z.string()).optional(),
      conflicts:             z.array(conflictSchema).optional(),
      coverage:              coverageSchema.optional(),
      reconciliation:        reconciliationSchema.optional(),
    });

    const bodyParsed = bodySchema.safeParse(request.body);
    if (!bodyParsed.success) {
      return reply.status(400).send({ error: "invalid_body", message: "request body failed schema validation" });
    }
    const rv = bodyParsed.data;

    // Verify deal exists (no investor_insights, render_package, or other tables)
    const { rows: dealRows } = await pool.query<{ id: string }>(
      `SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL LIMIT 1`,
      [dealId],
    );
    if (!dealRows.length) {
      return reply.status(404).send({ error: "deal_not_found" });
    }

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return reply.status(503).send({ error: "llm_unavailable", message: "OPENAI_API_KEY not configured" });
    }

    // Block requests when there is nothing substantive to analyse
    const hasGates    = (rv.gates?.length ?? 0) > 0;
    const hasConflicts = (rv.conflicts?.length ?? 0) > 0;
    const hasMissing  = (rv.missing_critical_terms?.length ?? 0) > 0;
    const hasCoverage = rv.coverage !== undefined;
    const hasRecon    = rv.reconciliation !== undefined;
    if (!hasGates && !hasConflicts && !hasMissing && !hasCoverage && !hasRecon) {
      return reply.status(400).send({
        error: "insufficient_data",
        message: "At least one of gates, conflicts, missing_critical_terms, coverage, or reconciliation must be present",
      });
    }

    // ── Build structured prompt ─────────────────────────────────────────────
    const dealCtx = rv.deal_name ? `Deal: ${rv.deal_name}\n\n` : "";

    const signals: string[] = [];

    // Gates
    if (rv.gates?.length) {
      const failed = rv.gates.filter((g) => g.status === "fail");
      const passed = rv.gates.filter((g) => g.status === "pass");
      signals.push(`Readiness gates: ${passed.length} passed, ${failed.length} failed`);
      for (const g of failed) {
        signals.push(`  Gate ${g.id} FAILED${g.reason ? `: ${g.reason}` : ""}`);
      }
    }

    // Missing critical terms
    if (rv.missing_critical_terms?.length) {
      signals.push(`Critical terms not disclosed: ${rv.missing_critical_terms.join(", ")}`);
    }

    // Conflicts
    if (rv.conflicts?.length) {
      signals.push(`Data conflicts detected: ${rv.conflicts.length}`);
      for (const c of rv.conflicts) {
        signals.push(`  Field "${c.field}": source A="${c.value_a}" vs source B="${c.value_b}"`);
      }
    }

    // Coverage
    const cov = rv.coverage;
    if (cov) {
      if (cov.docs_count != null)        signals.push(`Documents reviewed: ${cov.docs_count}`);
      if (cov.dpu_pages != null)         signals.push(`Total pages: ${cov.dpu_pages}`);
      if (cov.nonempty_pages != null && cov.dpu_pages != null && cov.dpu_pages > 0) {
        const pct = Math.round((cov.nonempty_pages / cov.dpu_pages) * 100);
        signals.push(`Text coverage: ${pct}% (${cov.nonempty_pages} of ${cov.dpu_pages} pages had readable text)`);
      } else if (cov.text_coverage_pct != null) {
        signals.push(`Text coverage: ${cov.text_coverage_pct}%`);
      }
      if (cov.evidence_count != null)    signals.push(`Evidence extractions: ${cov.evidence_count}`);
    }

    // Reconciliation
    if (rv.reconciliation) {
      const conf = rv.reconciliation.confidence_score;
      if (conf != null) signals.push(`Financial reconciliation confidence: ${conf.toFixed(2)}`);
      const warnFail = (rv.reconciliation.flags ?? []).filter((f) => f.status === "WARN" || f.status === "FAIL");
      if (warnFail.length) {
        signals.push(`Reconciliation issues: ${warnFail.map((f) => f.name).join(", ")}`);
      }
    }

    // Low coverage flag used in validator
    const isLowCoverage = (() => {
      if (!cov) return false;
      if (cov.text_coverage_pct != null) return cov.text_coverage_pct < 70;
      if (cov.nonempty_pages != null && cov.dpu_pages != null && cov.dpu_pages > 0) {
        return (cov.nonempty_pages / cov.dpu_pages) < 0.7;
      }
      return false;
    })();

    const systemPrompt =
      "You are a senior venture capital analyst reviewing a deal for a fund investment committee. " +
      "Your job is to write a concise verification & risk narrative that will appear in a formal investment memo.\n\n" +
      "RULES:\n" +
      "- Do NOT invent numbers, metrics, or facts not present in the inputs.\n" +
      "- If critical terms are listed as not disclosed, you MUST include the phrase 'not disclosed'.\n" +
      "- If text coverage is low, you MUST include the phrase 'data coverage'.\n" +
      "- summary_paragraphs: 2–3 short paragraphs summarising verification status and risk posture.\n" +
      "- top_risks: 3–5 bullets, each 1 short sentence, describing concrete risks from the signals.\n" +
      "- verification_requests: 3–5 bullets stating specific items the fund should request from the company.\n" +
      "- Do NOT use placeholder company names like 'Startup Corp' or '[Company]'.\n" +
      "- Write in third-person professional memo style.\n\n" +
      "Return ONLY a valid JSON object with exactly these keys:\n" +
      '  "schema_version": "risk_verification_v1",\n' +
      '  "summary_paragraphs": string[],\n' +
      '  "top_risks": string[],\n' +
      '  "verification_requests": string[]\n';

    const userPrompt =
      dealCtx +
      "Synthesise a risk & verification narrative from these signals:\n\n" +
      signals.join("\n");

    const model =
      process.env.OPENAI_MODEL_RISK_VERIFICATION ||
      process.env.OPENAI_MODEL_FINANCIAL_ANALYSIS ||
      "gpt-4o-mini";

    let rawContent: string;
    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.15,
          max_tokens: 700,
          response_format: { type: "json_object" },
        }),
      });

      if (!res.ok) {
        const text = await res.text().catch(() => "");
        console.error("[risk-verification] openai_error", { dealId, status: res.status, text });
        return reply.status(502).send({ error: "llm_error", message: `OpenAI returned ${res.status}` });
      }

      type OAIResp = { choices: Array<{ message?: { content?: string } }>; model: string };
      const json = (await res.json()) as OAIResp;
      rawContent = json.choices?.[0]?.message?.content?.trim() ?? "";
    } catch (err) {
      console.error("[risk-verification] fetch_error", {
        dealId, err: err instanceof Error ? err.message : String(err),
      });
      return reply.status(502).send({ error: "llm_error", message: "OpenAI request failed" });
    }

    if (!rawContent) {
      return reply.status(502).send({ error: "llm_empty_response" });
    }

    let parsedRv: {
      schema_version?: string;
      summary_paragraphs?: unknown;
      top_risks?: unknown;
      verification_requests?: unknown;
    };
    try {
      parsedRv = JSON.parse(rawContent);
    } catch {
      console.error("[risk-verification] json_parse_error", { dealId, rawContent: rawContent.slice(0, 200) });
      return reply.status(502).send({ error: "llm_parse_error", message: "LLM returned non-JSON" });
    }

    // ── Validators ──────────────────────────────────────────────────────────
    const safeStrArr = (v: unknown, min = 1, max = 6): string[] => {
      if (!Array.isArray(v)) return [];
      const filtered = v
        .filter((x): x is string => typeof x === "string" && x.trim().length > 0)
        .map((x) => x.trim());
      return filtered.slice(0, max);
    };

    const summaryParagraphs    = safeStrArr(parsedRv.summary_paragraphs, 1, 4);
    const topRisks             = safeStrArr(parsedRv.top_risks, 1, 6);
    const verificationRequests = safeStrArr(parsedRv.verification_requests, 1, 6);

    // ── Post-processing phrase injection ────────────────────────────────────
    // Deterministically inject required compliance phrases BEFORE validator
    // checks so the endpoint returns 200 instead of 502 on model omissions.
    const injectedSummary = [...summaryParagraphs];
    const preCheckText1 = [...injectedSummary, ...topRisks, ...verificationRequests].join(" ");
    if (rv.missing_critical_terms?.length && !/not disclosed/i.test(preCheckText1)) {
      const terms = rv.missing_critical_terms.slice(0, 3).join(", ");
      injectedSummary.unshift(
        `Note: key terms (${terms}) are not disclosed in the provided materials and require follow-up.`
      );
    }
    const preCheckText2 = [...injectedSummary, ...topRisks, ...verificationRequests].join(" ");
    if (isLowCoverage && !/data coverage/i.test(preCheckText2)) {
      injectedSummary.push(
        "Note: data coverage is limited — some key terms may be embedded in non-scannable content."
      );
    }

    const PLACEHOLDER_RE = /startup corp|\[company\]|\[name\]|<company>|example company/i;
    const allText = [...injectedSummary, ...topRisks, ...verificationRequests].join(" ");

    if (PLACEHOLDER_RE.test(allText)) {
      console.error("[risk-verification] placeholder_detected", { dealId });
      return reply.status(502).send({ error: "llm_quality_error", message: "LLM response contained placeholder values" });
    }

    // Validators — will pass because required phrases were injected above.
    if (rv.missing_critical_terms?.length && !/not disclosed/i.test(allText)) {
      console.error("[risk-verification] not_disclosed_missing", { dealId });
      return reply.status(502).send({
        error: "llm_quality_error",
        message: "Narrative for missing critical terms must include the phrase 'not disclosed'",
      });
    }

    // When low text coverage, require phrase "data coverage" in narrative
    if (isLowCoverage && !/data coverage/i.test(allText)) {
      console.error("[risk-verification] data_coverage_missing", { dealId });
      return reply.status(502).send({
        error: "llm_quality_error",
        message: "Narrative for low-coverage reports must include the phrase 'data coverage'",
      });
    }

    return reply.send({
      schema_version: "risk_verification_v1",
      summary_paragraphs: injectedSummary,
      top_risks: topRisks,
      verification_requests: verificationRequests,
    });
  });

}
