/**
 * apps/api/src/routes/deals/deal-ingestion.routes.ts
 * registerDealIngestionRoutes — extracted from deals.ts (PR12)
 * AUTO-GENERATED by scripts/dev/split-deals-final.py
 */
import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import { fetchPhaseBVisualsFromDb } from "../../lib/phaseb-visuals";
import { getUploadsRootDir } from "../../plugins/uploads-static";
import { getPool } from "../../lib/db";
import { resolveVisualAssetImageUriForApi } from "../../lib/visual-asset-image-uri";
import type { Deal } from "@dealdecision/contracts";
import type { JobStatus, JobType } from "@dealdecision/contracts";
import { QUEUE_NAMES } from "@dealdecision/core";
import { enqueueBullmqJob, enqueueJob, insertJobRow } from "../../services/jobs";
import { getQueues } from "../../lib/queue";
import { runIdempotentOperation } from "../../lib/jobs";
import { getStorageDriver } from "../../lib/storage-contract";
import { autoProgressDealStage } from "../../services/stageProgression";
import { updateDealPriority, updateAllDealPriorities } from "../../services/priorityClassification";
import { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";
import { getNodeEvidenceGateForDeal } from "../../services/nodeEvidenceGateForDeal";
import { normalizeDealName } from "../../lib/normalize-deal-name";
import { buildDocumentsDigest } from "../../lib/documents-digest";
import type { DocumentsDigestV1 } from "../../lib/documents-digest";
import { objectExistsInR2 } from "../../lib/r2";
import {
  purgeDealCascade,
  isPurgeDealNotFoundError,
  sanitizeText,
  getDocumentCapabilities,
  buildDealScoringInputV0FromLineage,
  getSegmentConfidenceThresholds,
  detectContentArchetypeTags,
  buildOrchestratorReportV1,
} from "@dealdecision/core";
import {
  BrandModel,
  PageInput,
  buildBrandModel,
  inferDocumentBrandName,
  inferSlideTitleForSlide,
  isLikelyGarbledSlideTitle,
  normalizePhrase,
} from "../../lib/slide-title";
import {
  buildClassificationText,
  buildSegmentFeatures,
  classifySegment,
  normalizeAnalystSegment,
  type AnalystSegment,
  type SegmentClassifierInput,
} from "../../lib/analyst-segment";
import {
  groupWordVisualAssetsByDocument,
  groupWordVisualAssetsByDocumentWithStats,
  type WordGroupingStats,
} from "../../lib/word-visual-grouping";
import { fetchPageUnderstandingReadinessForDeal } from "../../lib/deal-page-understanding-readiness";
import { ensureDocumentsReadyForAnalysis } from "../../lib/ensure-documents-ready-for-analysis";
import { getCanonicalFieldsForAI } from "../../lib/canonical-fields-for-ai";
import type {
  QueryResult,
  DealRoutesPool,
  DealRoutesClient,
  DealApiMode,
  AutoProfileDocRow,
  DealRow,
  DIOAggregateRow,
  ScoreBreakdownSectionKey,
  EvidenceRow,
  StatusSummaryAnalysis,
  StatusSummaryReport,
  StatusSummaryEvidenceGate,
  StatusSummary,
} from "./_shared";
import {
  hasTable,
  hasColumn,
  getColumnDataType,
  isUuid,
  stripEvidenceFromExecutiveSummary,
  stripEvidenceFromClaims,
  parseDealApiMode,
  bestEffortReadinessJobPresenceCheck,
  parseBoolQ,
  computeOcrV2CleanText,
  pickNonUnknownSegment,
  majorityNonUnknownSegment,
  isStructuredWordSectionAsset,
  structuredWordContentStats,
  isEmptyStructuredWordSectionAsset,
  computeDocHintSegmentByDocId,
  applyNeighborHintPropagationToAssets,
  buildDeterministicGroupCapturedText,
  extractStructuredWordTextForCue,
  inferStructuredWordCueSegment,
  requireDestructiveAuth,
  dealStageEnum,
  dealPriorityEnum,
  normalizeDealTrend,
  dealTrendEnum,
  dealCreateSchema,
  dealDraftCreateSchema,
  dealConfirmProfileSchema,
  sanitizeProfileValue,
  extractLabeledValue,
  isGenericCandidateName,
  deriveNameFromFilenameLike,
  extractCompanyFromEarlyText,
  computeAutoProfileFromDocuments,
  normalizeWarningsForPersistence,
  jsonbParam,
  dealUpdateSchema,
  llmPhaseModeEnum,
  parseNullableNumber,
  SCORE_BREAKDOWN_SECTION_ORDER,
  CLAIM_CATEGORY_SECTION_MAP,
  normalizeCategory,
  sectionForCategory,
  buildScoreBreakdownV1,
  collectEvidenceIdsFromClaims,
  getEvidenceByIds,
  getDocumentIndex,
  fetchEvidenceSamplesBySection,
  normalizeEvidenceSnippet,
  BUSINESS_MODEL_STRONG_REGEX,
  deriveSectionKeyFromClaim,
  ensureEvidenceLinksForClaims,
  buildPhase1ScoreEvidence,
  buildScoreEvidenceFromBreakdown,
  mapDeal,
  safeJsonValue,
  ocrSnippet,
  deriveStructuredSummary,
  cueRescueLowSignal,
  deriveBestExtractionConfidence,
  mapAnalysisJobStatus,
  mapReportRowStatus,
  maxIsoTs,
  buildStatusSummary,
} from "./_shared";

export async function registerDealIngestionRoutes(
  app: FastifyInstance,
  pool: DealRoutesPool,
  enqueue: typeof enqueueJob,
  r2: { objectExistsInR2: typeof objectExistsInR2 },
  debugRoutesEnabled: boolean,
  deps?: {
    enqueueJob?: typeof enqueueJob;
    jobs?: { queue?: any };
    r2?: { objectExistsInR2?: typeof objectExistsInR2 };
    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };
  }
): Promise<void> {
  app.post("/api/v1/deals/draft", async (request, reply) => {
    const parsed = dealDraftCreateSchema?.safeParse(request.body);
    if (parsed && !parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }

    const data = parsed?.success ? parsed.data : undefined;

    const stage = data?.stage ?? "intake";
    const priority = data?.priority ?? "medium";
    const owner = data?.owner ?? null;
    const createdByUserId = (request as any)?.auth?.userId ?? null;
    const orgId = (request as any)?.auth?.orgId ?? null;
    const hasDealOrgId = await hasColumn(pool, "deals", "org_id");

    const requestedName = typeof data?.name === "string" ? sanitizeText(data.name) : "";
    const name = requestedName || `Draft Deal ${randomUUID().slice(0, 8)}`;

    const { rows } = await pool.query<{ id: string }>(
      hasDealOrgId
        ? `INSERT INTO deals (name, stage, priority, llm_phase_mode, owner, created_by_user_id, org_id)
           VALUES ($1, $2, $3, 'exploratory', $4, $5, $6)
           RETURNING id`
        : `INSERT INTO deals (name, stage, priority, llm_phase_mode, owner, created_by_user_id)
           VALUES ($1, $2, $3, 'exploratory', $4, $5)
           RETURNING id`,
      hasDealOrgId
        ? [name, stage, priority, owner, createdByUserId, orgId]
        : [name, stage, priority, owner, createdByUserId]
    );

    const dealId = rows[0]?.id;

    if (dealId && (await hasColumn(pool, "deals", "lifecycle_status"))) {
      try {
        await pool.query(`UPDATE deals SET lifecycle_status = 'draft', updated_at = now() WHERE id = $1`, [dealId]);
      } catch {
        // ignore
      }
    }

    return reply.status(201).send({ deal_id: dealId });
  });

  // Claim legacy deals that don't have an explicit creator.
  // Useful when moving from a single-tenant/dev dataset to per-user deal ownership.
  app.post("/api/v1/deals/claim", async (request, reply) => {
    const userId = (request as any)?.auth?.userId;
    const orgId = (request as any)?.auth?.orgId;
    if (typeof userId !== "string" || userId.trim().length === 0) {
      return reply.status(401).send({ error: "Unauthorized" });
    }

    const hasDealOrgId = await hasColumn(pool, "deals", "org_id");

    const { rowCount } = await pool.query(
      hasDealOrgId
        ? `UPDATE deals
            SET created_by_user_id = $1,
                org_id = COALESCE(org_id, $2),
                updated_at = now()
          WHERE deleted_at IS NULL
            AND created_by_user_id IS NULL`
        : `UPDATE deals
            SET created_by_user_id = $1,
                updated_at = now()
          WHERE deleted_at IS NULL
            AND created_by_user_id IS NULL`,
      hasDealOrgId
        ? [userId.trim(), typeof orgId === "string" && orgId.trim().length > 0 ? orgId.trim() : null]
        : [userId.trim()]
    );

    return reply.status(200).send({ claimed: rowCount ?? 0 });
  });

  app.post("/api/v1/deals/:deal_id/auto-profile", async (request, reply) => {
    const dealIdRaw = (request.params as any)?.deal_id;
    const dealId = sanitizeText(typeof dealIdRaw === "string" ? dealIdRaw : String(dealIdRaw ?? ""));
    const warnings: string[] = [];

    if (!dealId) {
      return reply.status(400).send({ error: "deal_id is required" });
    }

    let docs: AutoProfileDocRow[] = [];
    try {
      const canJoinOriginalFile = await hasTable(pool, "document_files");
      const res = await pool.query<AutoProfileDocRow>(
        canJoinOriginalFile
          ? `SELECT d.id, d.title, f.file_name, d.full_text, d.structured_data, d.full_content
             FROM documents d
             LEFT JOIN document_files f ON f.document_id = d.id
             WHERE d.deal_id = $1
             ORDER BY d.uploaded_at DESC`
          : `SELECT id, title, full_text, structured_data, full_content
             FROM documents
             WHERE deal_id = $1
             ORDER BY uploaded_at DESC`,
        [dealId]
      );
      docs = res.rows ?? [];
    } catch {
      warnings.push("failed to load documents for auto-profile");
      docs = [];
    }

    const computed = computeAutoProfileFromDocuments(docs);
    warnings.push(...computed.warnings);

    const canPersist =
      (await hasColumn(pool, "deals", "proposed_profile")) &&
      (await hasColumn(pool, "deals", "proposed_profile_confidence")) &&
      (await hasColumn(pool, "deals", "proposed_profile_sources")) &&
      (await hasColumn(pool, "deals", "proposed_profile_warnings"));

    if (canPersist) {
      try {
        const proposedProfileDb = (computed as any)?.proposed_profile ?? null;
        const confidenceDb = (computed as any)?.confidence ?? null;
        const sourcesDb = (computed as any)?.sources ?? null;
        const warningsDb = normalizeWarningsForPersistence(warnings);

        await pool.query(
          `UPDATE deals
           SET proposed_profile = $2,
               proposed_profile_confidence = $3,
               proposed_profile_sources = $4,
               proposed_profile_warnings = $5,
               updated_at = now()
           WHERE id = $1`,
          [dealId, jsonbParam(proposedProfileDb), jsonbParam(confidenceDb), jsonbParam(sourcesDb), jsonbParam(warningsDb)]
        );
      } catch (err: any) {
        const msg = typeof err?.message === "string" ? err.message : "unknown error";
        const warningsDb = normalizeWarningsForPersistence(warnings);
        request.log?.warn?.(
          {
            err: msg,
            deal_id: dealId,
            value_types: {
              proposed_profile: typeof (computed as any)?.proposed_profile,
              proposed_profile_isArray: Array.isArray((computed as any)?.proposed_profile),
              proposed_profile_confidence: typeof (computed as any)?.confidence,
              proposed_profile_sources: typeof (computed as any)?.sources,
              proposed_profile_warnings: warningsDb === null ? "null" : typeof warningsDb,
              proposed_profile_warnings_isArray: Array.isArray(warningsDb),
              proposed_profile_warnings_len: Array.isArray(warningsDb) ? warningsDb.length : 0,
            },
          },
          "auto-profile.persist_failed"
        );
        warnings.push(`failed to persist proposed profile (non-fatal): ${String(msg).slice(0, 240)}`);
      }
    } else {
      warnings.push("proposed profile storage not available (missing columns)");
    }

    return reply.status(200).send({
      deal_id: dealId,
      proposed_profile: computed.proposed_profile,
      confidence: computed.confidence,
      sources: computed.sources,
      warnings,
    });
  });

  app.post("/api/v1/deals/:deal_id/confirm-profile", async (request, reply) => {
    const dealIdRaw = (request.params as any)?.deal_id;
    const dealId = sanitizeText(typeof dealIdRaw === "string" ? dealIdRaw : String(dealIdRaw ?? ""));
    if (!dealId) {
      return reply.status(400).send({ error: "deal_id is required" });
    }

    const parsed = dealConfirmProfileSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }

    const body = parsed.data;
    const dealName = sanitizeProfileValue(body.deal_name) ?? null;
    const companyName = sanitizeProfileValue(body.company_name) ?? null;
    const industry = sanitizeProfileValue(body.industry) ?? null;
    const investmentType = sanitizeProfileValue(body.investment_type) ?? null;
    const round = sanitizeProfileValue(body.round) ?? null;

    const hasLifecycle = await hasColumn(pool, "deals", "lifecycle_status");
    const hasInvestmentType = await hasColumn(pool, "deals", "investment_type");
    const hasRound = await hasColumn(pool, "deals", "round");
    const hasProposal = await hasColumn(pool, "deals", "proposed_profile");
    const hasIndustry = await hasColumn(pool, "deals", "industry");

    try {
      const setFragments: string[] = [];
      const params: any[] = [dealId];
      let idx = 2;

      if (dealName) {
        setFragments.push(`name = $${idx++}`);
        params.push(dealName);
      }
      if (companyName) {
        setFragments.push(`owner = $${idx++}`);
        params.push(companyName);
      }
      if (industry && hasIndustry) {
        setFragments.push(`industry = $${idx++}`);
        params.push(industry);
      }
      if (investmentType && hasInvestmentType) {
        setFragments.push(`investment_type = $${idx++}`);
        params.push(investmentType);
      }
      if (round && hasRound) {
        setFragments.push(`round = $${idx++}`);
        params.push(round);
      }
      if (hasLifecycle) {
        setFragments.push(`lifecycle_status = 'active'`);
      }
      if (hasProposal) {
        setFragments.push(`proposed_profile = NULL`);
        if (await hasColumn(pool, "deals", "proposed_profile_confidence")) setFragments.push(`proposed_profile_confidence = NULL`);
        if (await hasColumn(pool, "deals", "proposed_profile_sources")) setFragments.push(`proposed_profile_sources = NULL`);
        if (await hasColumn(pool, "deals", "proposed_profile_warnings")) setFragments.push(`proposed_profile_warnings = NULL`);
      }

      if (setFragments.length === 0) {
        return reply.status(400).send({ error: "No fields provided to confirm" });
      }

      const { rows } = await pool.query<DealRow>(
        `UPDATE deals SET ${setFragments.join(", ")}, updated_at = now() WHERE id = $1 RETURNING *`,
        params
      );

      if (!rows?.[0]) {
        return reply.status(404).send({ error: "Deal not found" });
      }

      return reply.status(200).send(mapDeal(rows[0], null, "full"));
    } catch {
      return reply.status(500).send({ error: "Failed to confirm profile" });
    }
  });

  app.post("/api/v1/deals", async (request, reply) => {
    const parsed = dealCreateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }

    const { name, stage, priority, trend, score, owner } = parsed.data;
    const createdByUserId = (request as any)?.auth?.userId ?? null;
    const orgId = (request as any)?.auth?.orgId ?? null;
    const hasDealOrgId = await hasColumn(pool, "deals", "org_id");

    // Guard against accidental duplicates (common in bulk assignment / OCR scenarios).
    // We keep this lightweight (no schema changes) by normalizing and comparing in-app.
    const normalized = normalizeDealName(name);
    if (normalized) {
      const { rows: existing } = await pool.query<{ id: string; name: string }>(
        `SELECT id, name FROM deals WHERE deleted_at IS NULL`
      );
      const match = existing.find((d: { id: string; name: string }) => normalizeDealName(d.name) === normalized);
      if (match) {
        return reply.status(409).send({
          error: "Deal already exists",
          existing_deal_id: match.id,
          existing_deal_name: match.name,
        });
      }
    }

    const { rows } = await pool.query<DealRow>(
      hasDealOrgId
        ? `INSERT INTO deals (name, stage, priority, llm_phase_mode, trend, score, owner, created_by_user_id, org_id)
           VALUES ($1, $2, $3, 'exploratory', $4, $5, $6, $7, $8)
           RETURNING *`
        : `INSERT INTO deals (name, stage, priority, llm_phase_mode, trend, score, owner, created_by_user_id)
           VALUES ($1, $2, $3, 'exploratory', $4, $5, $6, $7)
           RETURNING *`,
      hasDealOrgId
        ? [name, stage, priority, trend ?? null, score ?? null, owner ?? null, createdByUserId, orgId]
        : [name, stage, priority, trend ?? null, score ?? null, owner ?? null, createdByUserId]
    );

    return mapDeal(rows[0], null, "full");
  });

  const dealMergeSchema = z.object({
    source_deal_id: z.string().uuid(),
    target_deal_id: z.string().uuid(),
    delete_source_dio: z.boolean().optional().default(false),
  });

  // Merge one deal into another by reassigning documents (and related rows) and soft-deleting the source deal.
  app.post("/api/v1/deals/merge", async (request, reply) => {
    const parsed = dealMergeSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }

    const { source_deal_id, target_deal_id, delete_source_dio } = parsed.data;
    if (source_deal_id === target_deal_id) {
      return reply.status(400).send({ error: "source_deal_id and target_deal_id must be different" });
    }

    const client = await pool.connect?.();
    if (!client) return reply.status(500).send({ error: "Database connection unavailable" });
    try {
      await client.query("BEGIN");

      const { rows: sourceRows } = await client.query<DealRow>(
        `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
        [source_deal_id]
      );
      const { rows: targetRows } = await client.query<DealRow>(
        `SELECT * FROM deals WHERE id = $1 AND deleted_at IS NULL`,
        [target_deal_id]
      );

      if (sourceRows.length === 0) {
        await client.query("ROLLBACK");
        return reply.status(404).send({ error: "Source deal not found" });
      }
      if (targetRows.length === 0) {
        await client.query("ROLLBACK");
        return reply.status(404).send({ error: "Target deal not found" });
      }

      const source = sourceRows[0];
      const target = targetRows[0];

      const docsRes = await client.query(
        `UPDATE documents SET deal_id = $2, updated_at = now() WHERE deal_id = $1`,
        [source_deal_id, target_deal_id]
      );

      const evidenceRes = await client.query(
        `UPDATE evidence SET deal_id = $2 WHERE deal_id = $1`,
        [source_deal_id, target_deal_id]
      );
      const dealEvidenceRes = await client.query(
        `UPDATE deal_evidence SET deal_id = $2 WHERE deal_id = $1`,
        [source_deal_id, target_deal_id]
      );
      const jobsRes = await client.query(
        `UPDATE jobs SET deal_id = $2, updated_at = now() WHERE deal_id = $1`,
        [source_deal_id, target_deal_id]
      );

      let dioDeleted = 0;
      if (delete_source_dio) {
        const del = await client.query(
          `DELETE FROM deal_intelligence_objects WHERE deal_id = $1`,
          [source_deal_id]
        );
        dioDeleted = del.rowCount ?? 0;
      }

      await client.query(
        `UPDATE deals SET deleted_at = now(), updated_at = now() WHERE id = $1`,
        [source_deal_id]
      );

      await client.query("COMMIT");

      return reply.send({
        ok: true,
        source: { id: source.id, name: source.name },
        target: { id: target.id, name: target.name },
        moved: {
          documents: docsRes.rowCount ?? 0,
          evidence: evidenceRes.rowCount ?? 0,
          deal_evidence: dealEvidenceRes.rowCount ?? 0,
          jobs: jobsRes.rowCount ?? 0,
        },
        deleted: {
          source_dio_rows: dioDeleted,
        },
      });
    } catch (err) {
      await client.query("ROLLBACK");
      const message = err instanceof Error ? err.message : "Merge failed";
      return reply.status(500).send({ error: message });
    } finally {
      client.release();
    }
  });

  app.get("/api/v1/deals/:deal_id/visual-assets", async (request, reply) => {
    const dealId = sanitizeText((request.params as { deal_id: string }).deal_id);
    if (!dealId) return reply.status(400).send({ error: "deal_id is required" });

    const groupWordRequested = parseBoolQ(((request.query as any) ?? {})?.group_word, false);
    const docHintRequested = parseBoolQ(((request.query as any) ?? {})?.doc_hint, false);
    const includeOcrRequested = parseBoolQ(((request.query as any) ?? {})?.include_ocr, false);
    const includeImagesRequested = parseBoolQ(((request.query as any) ?? {})?.include_images, false);
    const includePageOcrV2Requested = parseBoolQ(((request.query as any) ?? {})?.include_page_ocr_v2, false);
    const includePageUnderstandingRequested = parseBoolQ(((request.query as any) ?? {})?.include_page_understanding_v1, false);
    const includePageFallbackRequested = parseBoolQ(((request.query as any) ?? {})?.include_page_fallback, false);

    const logCtx = { route: "deal_visual_assets", deal_id: dealId };

    try {
      const dealExistsRes = await pool.query("SELECT id FROM deals WHERE id = $1 LIMIT 1", [dealId]);
      const dealExists = Array.isArray(dealExistsRes?.rows) && dealExistsRes.rows.length > 0;
      if (!dealExists) {
        request.log?.warn?.({ ...logCtx }, "deal_visual_assets.not_found");
        return reply.status(404).send({ error: "deal_not_found", deal_id: dealId });
      }

      const assetsOk = await hasTable(pool, "public.visual_assets");
      const extractionsOk = await hasTable(pool, "public.visual_extractions");
      const documentsOk = await hasTable(pool, "public.documents");
      const aiAnalysesOk = await hasTable(pool, "public.visual_asset_ai_analyses");

      if (!assetsOk || !extractionsOk || !documentsOk) {
        request.log?.warn?.(
          { ...logCtx, assets_table: assetsOk, extractions_table: extractionsOk, documents_table: documentsOk },
          "deal_visual_assets.schema_missing"
        );
        return reply.send({ deal_id: dealId, visual_assets: [] });
      }

      const hasStructuredSummary = await hasColumn(pool, "visual_extractions", "structured_summary");
      const hasStructuredKind = await hasColumn(pool, "visual_extractions", "structured_kind");
      const hasOcrBlocks = await hasColumn(pool, "visual_extractions", "ocr_blocks");
      const hasUnits = await hasColumn(pool, "visual_extractions", "units");
      const hasMimeType = await hasColumn(pool, "documents", "mime_type");
      const structuredSummarySelect = hasStructuredSummary
        ? "ve.structured_summary AS structured_summary"
        : "NULL::jsonb AS structured_summary";

      request.log?.info?.(
        {
          ...logCtx,
          has_structured_summary: hasStructuredSummary,
          has_structured_kind: hasStructuredKind,
          has_ai_analyses: aiAnalysesOk,
        },
        "deal_visual_assets.schema_ready"
      );

      const aiInvestorSelect = aiAnalysesOk ? "aa_inv.last_at AS ai_analysis_investor_last_at" : "NULL::timestamptz AS ai_analysis_investor_last_at";
      const aiAnalystSelect = aiAnalysesOk ? "aa_an.last_at AS ai_analysis_analyst_last_at" : "NULL::timestamptz AS ai_analysis_analyst_last_at";
      const aiInvestorJoin = aiAnalysesOk
        ? "LEFT JOIN LATERAL (SELECT MAX(created_at) AS last_at FROM visual_asset_ai_analyses WHERE visual_asset_id = va.id AND audience = 'investor') aa_inv ON true"
        : "";
      const aiAnalystJoin = aiAnalysesOk
        ? "LEFT JOIN LATERAL (SELECT MAX(created_at) AS last_at FROM visual_asset_ai_analyses WHERE visual_asset_id = va.id AND audience = 'analyst') aa_an ON true"
        : "";

      const includePageOcrV2Select = includePageOcrV2Requested
        ? "(d.full_content->'pdf_v2'->'pages'->(va.page_index)::int->'ocr_v2'->>'text') AS page_ocr_v2_text"
        : "NULL::text AS page_ocr_v2_text";
      const includePageOcrV2ConfSelect = includePageOcrV2Requested
        ? "(d.full_content->'pdf_v2'->'pages'->(va.page_index)::int->'ocr_v2'->>'avg_confidence')::double precision AS page_ocr_v2_avg_confidence"
        : "NULL::double precision AS page_ocr_v2_avg_confidence";
      const includePageOcrV2ProviderSelect = includePageOcrV2Requested
        ? "(d.full_content->'pdf_v2'->'pages'->(va.page_index)::int->'ocr_v2'->>'provider') AS page_ocr_v2_provider"
        : "NULL::text AS page_ocr_v2_provider";

      const includePageOcrV2JsonSelect = includePageOcrV2Requested
        ? "(d.full_content->'pdf_v2'->'pages'->(va.page_index)::int->'ocr_v2') AS page_ocr_v2_json"
        : "NULL::jsonb AS page_ocr_v2_json";

      const includePageUnderstandingSelect = includePageUnderstandingRequested
        ? "dpu.payload AS page_understanding_v1"
        : "NULL::jsonb AS page_understanding_v1";

      const includePageUnderstandingUpdatedAtSelect = includePageUnderstandingRequested
        ? "dpu.updated_at AS page_understanding_v1_updated_at"
        : "NULL::timestamptz AS page_understanding_v1_updated_at";

      const pageUnderstandingJoin = includePageUnderstandingRequested
        ? "LEFT JOIN document_page_understanding dpu ON dpu.document_id = va.document_id AND dpu.page_index = va.page_index AND dpu.version = 'page_understanding_v1'"
        : "";

      const { rows } = await pool.query(
        `WITH latest_extraction AS (
           SELECT ve.visual_asset_id,
                  ${hasStructuredKind ? "ve.structured_kind AS structured_kind" : "NULL::text AS structured_kind"},
                  ${structuredSummarySelect},
                  ve.ocr_text,
                  ${hasOcrBlocks ? "ve.ocr_blocks AS ocr_blocks" : "NULL::jsonb AS ocr_blocks"},
                  ${hasUnits ? "ve.units AS units" : "NULL::jsonb AS units"},
                  ve.structured_json,
                  ROW_NUMBER() OVER (PARTITION BY ve.visual_asset_id ORDER BY ve.created_at DESC) AS rn
             FROM visual_extractions ve
        )
         SELECT
           va.id AS visual_asset_id,
           va.id,
           va.document_id,
           d.deal_id,
           va.page_index,
           va.bbox,
           va.image_uri,
           va.image_hash,
           va.created_at,
           va.asset_type,
           va.confidence,
           va.quality_flags,
           va.extractor_version,
           d.title AS document_title,
           d.type AS document_type,
           d.status AS document_status,
           d.page_count AS document_page_count,
           ${hasMimeType ? "d.mime_type AS document_mime_type" : "NULL::text AS document_mime_type"},
           ${includePageOcrV2Select},
           ${includePageOcrV2ConfSelect},
           ${includePageOcrV2ProviderSelect},
           ${includePageOcrV2JsonSelect},
           ${includePageUnderstandingSelect},
           ${includePageUnderstandingUpdatedAtSelect},
           COALESCE(ev.count, 0) AS evidence_count,
           COALESCE(ev.sample_snippets, ARRAY[]::text[]) AS evidence_sample_snippets,
           (SELECT EXISTS (SELECT 1 FROM visual_extractions ve WHERE ve.visual_asset_id = va.id)) AS has_extraction,
           le.structured_kind,
           le.structured_summary,
           le.ocr_text,
           le.ocr_blocks,
           le.units,
           le.structured_json,
           ${aiInvestorSelect},
           ${aiAnalystSelect}
         FROM visual_assets va
         JOIN documents d ON d.id = va.document_id
         ${pageUnderstandingJoin}
         ${aiInvestorJoin}
         ${aiAnalystJoin}
         LEFT JOIN LATERAL (
           SELECT COUNT(*)::int AS count,
                  ARRAY(
                  SELECT LEFT(el.snippet, 200)
                   FROM evidence_links el
                  WHERE el.visual_asset_id = va.id AND el.snippet IS NOT NULL AND el.snippet <> ''
                  ORDER BY el.created_at DESC
                     LIMIT 3
                  ) AS sample_snippets
             FROM evidence_links el2
            WHERE el2.visual_asset_id = va.id
         ) ev ON true
         LEFT JOIN latest_extraction le ON le.visual_asset_id = va.id AND le.rn = 1
        WHERE d.deal_id = $1
        ORDER BY va.document_id ASC, va.page_index ASC, va.created_at ASC
        LIMIT 5000`,
        [dealId]
      );

      const rawAssets = rows ?? [];

      if (includePageOcrV2Requested && rawAssets.length > 0) {
        for (const r of rawAssets as any[]) {
          const { text, keptBlocks, totalBlocks } = computeOcrV2CleanText((r as any).page_ocr_v2_json);
          (r as any).page_ocr_v2_text_clean = text;
          (r as any).page_ocr_v2_kept_blocks = keptBlocks;
          (r as any).page_ocr_v2_total_blocks = totalBlocks;
          delete (r as any).page_ocr_v2_json;
        }
      }

      const brandModelByDocId = new Map<string, BrandModel>();
      const brandNameByDocId = new Map<string, { brand: string | null; confidence: number | null }>();

      const docIds = Array.from(
        new Set(
          rawAssets
            .map((r: any) => (typeof r?.document_id === "string" ? r.document_id : null))
            .filter((x: any): x is string => Boolean(x))
        )
      );

      for (const docId of docIds) {
        const pageInputs: PageInput[] = rawAssets
          .filter((r: any) => r?.document_id === docId)
          .map((r: any) => ({ ocr_blocks: (r as any).ocr_blocks ?? null, ocr_text: r?.ocr_text ?? null }));

        const brandModel = buildBrandModel(pageInputs);

        const brandInfo = inferDocumentBrandName(pageInputs);
        if (brandInfo.brand_name) {
          const normBrand = normalizePhrase(brandInfo.brand_name);
          if (normBrand) brandModel.phrases.add(normBrand);
        }

        brandModelByDocId.set(docId, brandModel);
        brandNameByDocId.set(docId, { brand: brandInfo.brand_name, confidence: brandInfo.confidence });
      }

      const segmentInputByVisualId = new Map<string, SegmentClassifierInput>();

      const visualAssetsPass1 = rawAssets.map((r: any) => {
        const visual_asset_id = r?.visual_asset_id ?? r?.id ?? null;
        const brandModel = brandModelByDocId.get(r?.document_id) ?? buildBrandModel([]);
        const blacklist = brandModel.phrases;
        const brandInfo = brandNameByDocId.get(r?.document_id) ?? { brand: null, confidence: null };

        const derivedStructure = deriveStructuredSummary((r as any)?.structured_json, (r as any)?.units ?? null);
        const structured_kind = (r as any)?.structured_kind ?? derivedStructure.structured_kind;
        const structured_summary = (r as any)?.structured_summary ?? derivedStructure.structured_summary;

        const titleDerived = inferSlideTitleForSlide({
          blocks: (r as any).ocr_blocks as any[],
          ocr_text: r?.ocr_text,
          page_index:
            typeof (r as any)?.page_index === "number" && Number.isFinite((r as any).page_index) ? (r as any).page_index : null,
          page_width: null,
          page_height: null,
          brandModel,
          enableDebug: false,
        });

        const structuredTitleMeta = (() => {
          const sjObj = safeJsonValue((r as any)?.structured_json);
          if (!sjObj || typeof sjObj !== "object") return null;
          const kind = typeof (sjObj as any).kind === "string" ? String((sjObj as any).kind).toLowerCase() : "";
          const clean = (s: unknown): string | null => {
            if (typeof s !== "string") return null;
            const t = s.trim().replace(/\s+/g, " ");
            return t.length > 0 ? t.slice(0, 180) : null;
          };

          // Vision understanding (local model) output persisted by vision_worker.
          const vuObj = (sjObj as any)?.vision_understanding_v1;
          if (vuObj && typeof vuObj === "object") {
            const vuTitle = clean((vuObj as any).title);
            if (vuTitle) {
              const vuConfRaw = (vuObj as any).confidence;
              const vuConf = typeof vuConfRaw === "number" && Number.isFinite(vuConfRaw) ? vuConfRaw : 0.7;
              const vuHint = typeof (vuObj as any).segment_hint === "string" ? String((vuObj as any).segment_hint) : null;
              return {
                title: vuTitle,
                source: "structured_json.vision_understanding_v1.title",
                confidence: Math.max(0.45, Math.min(0.85, vuConf)),
                hint_segment: vuHint,
                hint_confidence: vuConf,
              };
            }
          }

          if (kind === "powerpoint_slide") {
            const title = clean((sjObj as any).title);
            return title ? { title, source: "structured_json.title", confidence: 0.9 } : null;
          }

          if (kind === "excel_sheet") {
            // Prefer the sheet_name from structured extraction; fall back to table.name.
            const title = clean((sjObj as any).sheet_name) ?? clean((sjObj as any)?.table?.name);
            return title ? { title, source: "structured_json.title", confidence: 0.9 } : null;
          }

          if (kind === "word_section") {
            const genericHeadings = new Set([
              "overview",
              "problem",
              "solution",
              "market",
              "traction",
              "business_model",
              "distribution",
              "team",
              "competition",
              "risks",
              "financials",
              "raise_terms",
              "exit",
              "unknown",
              "product",
            ]);
            const heading = clean((sjObj as any).heading);
            if (heading && !genericHeadings.has(heading.toLowerCase())) {
              return { title: heading, source: "structured_json.title", confidence: 0.9 };
            }

            const headings = Array.isArray((sjObj as any).headings) ? (sjObj as any).headings : [];
            for (const h of headings) {
              const v = clean(h);
              if (v && !genericHeadings.has(v.toLowerCase())) return { title: v, source: "structured_json.title", confidence: 0.9 };
            }

            const paras = Array.isArray((sjObj as any).paragraphs) ? (sjObj as any).paragraphs : [];
            for (const p of paras) {
              const v = clean(p);
              if (v && v.length >= 6) return { title: v, source: "structured_json.title", confidence: 0.9 };
            }

            const title = clean((sjObj as any).text_snippet);
            return title ? { title, source: "structured_json.title", confidence: 0.9 } : null;
          }

          return null;
        })();

        // Default behavior: OCR-derived title wins. Exception: if we have a local vision title and OCR title
        // confidence is low (common in garbled OCR), prefer the vision title.
        const hasVisionTitle = structuredTitleMeta?.source === "structured_json.vision_understanding_v1.title";
        const ocrTitleConfidence =
          typeof titleDerived.slide_title_confidence === "number" && Number.isFinite(titleDerived.slide_title_confidence)
            ? titleDerived.slide_title_confidence
            : 0;
        const useOcrTitle = Boolean(titleDerived.slide_title && (!hasVisionTitle || ocrTitleConfidence >= 0.55));

        const indexFallbackTitle =
          typeof r?.page_index === "number" && Number.isFinite(r.page_index) ? `Slide ${Math.max(0, r.page_index) + 1}` : "Slide";

        const slide_title = useOcrTitle
          ? titleDerived.slide_title
          : structuredTitleMeta?.title ?? titleDerived.slide_title ?? indexFallbackTitle;
        const slide_title_source = useOcrTitle
          ? titleDerived.slide_title_source
          : structuredTitleMeta
            ? structuredTitleMeta.source
            : titleDerived.slide_title
              ? titleDerived.slide_title_source
              : "index_fallback_v1";
        const slide_title_confidence = useOcrTitle
          ? titleDerived.slide_title_confidence
          : structuredTitleMeta
            ? structuredTitleMeta.confidence
            : titleDerived.slide_title_confidence ?? 0.15;

        // Avoid emitting misleading index-only placeholders.
        const slide_title_final = slide_title_source === "index_fallback_v1" ? null : slide_title;
        const slide_title_source_final = slide_title_final ? slide_title_source : "none";
        const slide_title_confidence_final = slide_title_final ? slide_title_confidence : 0;
        const slide_title_warnings = useOcrTitle
          ? titleDerived.slide_title_warnings
          : titleDerived.slide_title_warnings?.includes("picked_title_garbled")
            ? titleDerived.slide_title_warnings
            : undefined;

        // Segment resolution order (effective truth, non-destructive):
        // 1) human_override (quality_flags.segment_source === 'human_override' or 'human_override_*')
        // 2) promoted/persisted (quality_flags.segment_key)
        // 3) computed (API classifier) when non-unknown
        // 4) persisted extraction hint (structured_json.segment_key) when computed is unknown
        // 5) unknown
        // NOTE: structured_json.segment_key never affects computed_v1; it only acts as a fallback to avoid returning unknown.
        const persistedFromQualityRaw = normalizeAnalystSegment((r as any)?.quality_flags?.segment_key);
        const persistedFromStructuredRaw = normalizeAnalystSegment((r as any)?.structured_json?.segment_key);
        const qualitySourceRaw =
          typeof (r as any)?.quality_flags?.source === "string" ? String((r as any).quality_flags.source) : null;
        const qualitySegmentSourceRawDirect =
          typeof (r as any)?.quality_flags?.segment_source === "string" ? String((r as any).quality_flags.segment_source) : null;
        const qualityPersistMarker = qualitySegmentSourceRawDirect ?? qualitySourceRaw;
        const allowQualityPersist = (() => {
          const s = typeof qualityPersistMarker === "string" ? qualityPersistMarker.trim() : "";
          if (!s) return false;
          if (s === "human_override" || s === "human_override_v1" || s.startsWith("human_override_")) return true;
          if (s.startsWith("promoted") || s.startsWith("promoted_")) return true;
          if (s.startsWith("structured_")) return true;
          return false;
        })();
        const persistedFromQuality =
          allowQualityPersist && persistedFromQualityRaw && persistedFromQualityRaw !== "unknown" ? persistedFromQualityRaw : null;
        const persistedFromStructured = persistedFromStructuredRaw && persistedFromStructuredRaw !== "unknown" ? persistedFromStructuredRaw : null;
        const persistedSegmentKey = persistedFromQuality ?? persistedFromStructured;
        const persistedSourceKey = persistedFromQuality
          ? "quality_flags.segment_key"
          : persistedFromStructured
            ? "structured_json.segment_key"
            : null;

        const qualitySegmentSourceRaw = qualityPersistMarker;

        const isHumanOverride = Boolean(
          persistedFromQuality &&
            (qualitySegmentSourceRaw === "human_override" ||
              qualitySegmentSourceRaw === "human_override_v1" ||
              Boolean(qualitySegmentSourceRaw?.startsWith("human_override_")))
        );

        const isStructuredAsset =
          String((r as any)?.extractor_version ?? "") === "structured_native_v1" ||
          (typeof (r as any)?.quality_flags?.source === "string" && String((r as any).quality_flags.source).startsWith("structured_")) ||
          (typeof (r as any)?.structured_json?.kind === "string" &&
            ["word_section", "powerpoint_slide", "excel_sheet"].includes(String((r as any).structured_json.kind)));

        // Prefer worker-provided structured_json.segment_key when present; otherwise fall back to promoted key.
        // For vision assets, only pass a hint when it comes from vision_understanding_v1 and the page is low-signal.
        const visionHintRaw = structuredTitleMeta && typeof structuredTitleMeta.hint_segment === "string" ? structuredTitleMeta.hint_segment : null;
        const visionHint = visionHintRaw ? normalizeAnalystSegment(visionHintRaw) : null;
        const visionHintConfidenceRaw = structuredTitleMeta && typeof structuredTitleMeta.hint_confidence === "number" && Number.isFinite(structuredTitleMeta.hint_confidence)
          ? structuredTitleMeta.hint_confidence
          : null;
        const ocrLen = typeof r?.ocr_text === "string" ? r.ocr_text.trim().length : 0;
        const ocrTitleBad = !titleDerived.slide_title || ocrTitleConfidence < 0.45;
        const allowVisionHint = Boolean(
          !isStructuredAsset &&
            visionHint &&
            visionHint !== "unknown" &&
            (visionHintConfidenceRaw == null || visionHintConfidenceRaw >= 0.45) &&
            (ocrLen < 40 || ocrTitleBad)
        );

        const hintSegment = isStructuredAsset ? (persistedFromStructured ?? persistedFromQuality) : allowVisionHint ? visionHint : null;

        const baseInput: SegmentClassifierInput = {
          ocr_text: r?.ocr_text,
          ocr_snippet: ocrSnippet(r?.ocr_text),
          structured_kind,
          structured_summary,
          structured_json: (r as any)?.structured_json,
          asset_type: r?.asset_type,
          page_index: r?.page_index,
          // Keep computed_v1 consistent with lineage: don't let index-only placeholders influence classification.
          slide_title: slide_title_final,
          slide_title_confidence: slide_title_confidence_final,
          evidence_snippets: Array.isArray((r as any).evidence_sample_snippets) ? (r as any).evidence_sample_snippets : [],
          brand_blacklist: blacklist,
          brand_name: brandInfo.brand,
          extractor_version: (r as any)?.extractor_version,
          quality_source: (r as any)?.quality_flags?.source,
          enable_debug: false,
          include_debug_text_snippet: false,
          // Make computed_v1 deterministic and independent of worker-provided segment_key.
          disable_structured_segment_key_signal: true,
          disable_structured_segment_key_fallback: true,
        };

        if (typeof visual_asset_id === "string" && visual_asset_id.trim().length > 0) {
          segmentInputByVisualId.set(visual_asset_id.trim(), baseInput);
        }

        const computed = classifySegment({ ...baseInput, hint_segment: hintSegment });

        const computedReason = (() => {
          const seg = normalizeAnalystSegment(computed.segment) ?? "unknown";
          if (seg !== "unknown") return null;

          const text = typeof r?.ocr_text === "string" ? r.ocr_text.trim() : "";
          const hasText = text.length > 0;

          return {
            rule_id: "COMPUTED_V1_UNKNOWN",
            unknown_reason_code: hasText ? "LOW_SIGNAL" : "NO_TEXT",
          };
        })();

        const computedSegment = normalizeAnalystSegment(computed.segment) ?? "unknown";

        const effectiveSegment = isHumanOverride
          ? (persistedFromQuality ?? computedSegment)
          : persistedFromQuality
            ? persistedFromQuality
            : computedSegment !== "unknown"
              ? computedSegment
              : (persistedFromStructured ?? (allowVisionHint ? visionHint : null) ?? computedSegment);

        const persistedConfidenceRaw = (r as any)?.quality_flags?.segment_confidence;
        const persistedConfidence =
          typeof persistedConfidenceRaw === "number" && Number.isFinite(persistedConfidenceRaw)
            ? persistedConfidenceRaw
            : 1;
        const effectiveConfidence = (() => {
          if (persistedFromQuality) return persistedConfidence;
          if (computedSegment !== "unknown") return computed.confidence;
          if (persistedFromStructured) return 0.75;
          if (allowVisionHint && visionHint && visionHint !== "unknown") return Math.max(0.45, Math.min(0.75, visionHintConfidenceRaw ?? 0.6));
          return computed.confidence;
        })();

        const effectiveSource = (() => {
          if (persistedFromQuality) {
            if (isHumanOverride) return qualitySegmentSourceRaw || "human_override_v1";
            return qualitySegmentSourceRaw || "persisted_v0";
          }
          if (computedSegment !== "unknown") return "computed_v1";
          if (persistedFromStructured) return "structured_fallback_v1";
          if (allowVisionHint && visionHint && visionHint !== "unknown") return "vision_hint_fallback_v1";
          return "computed_v1";
        })();

        const qf = ((r as any)?.quality_flags ?? {}) as Record<string, any>;

        return {
          ...r,
          visual_asset_id,
          structured_summary,
          structured_kind,
          slide_title: slide_title_final,
          slide_title_source: slide_title_source_final,
          slide_title_confidence: slide_title_confidence_final,
          slide_title_warnings,
          // Backwards-compatible if any consumers use "segment" from this endpoint.
          segment: effectiveSegment,
          effective_segment: effectiveSegment,
          segment_source: effectiveSource,
          segment_confidence: effectiveConfidence,
          computed_segment: computed.segment,
          computed_confidence: computed.confidence,
          computed_reason: computedReason,
          persisted_segment_key: persistedSegmentKey,
          persisted_segment_source: persistedSourceKey,
          segment_promoted_at: typeof qf.segment_promoted_at === "string" ? qf.segment_promoted_at : null,
          segment_overridden_at: typeof qf.segment_overridden_at === "string" ? qf.segment_overridden_at : null,
          segment_override_note: typeof qf.segment_override_note === "string" ? qf.segment_override_note : null,
          document: {
            id: r?.document_id ?? null,
            title: r?.document_title ?? null,
            type: r?.document_type ?? null,
            status: r?.document_status ?? null,
            page_count: r?.document_page_count ?? null,
          },
        };
      });

      const visualAssetsPass2 = applyNeighborHintPropagationToAssets(visualAssetsPass1 as any, {
        maxDistancePages: 2,
        minNeighborConfidence: 0.65,
      });

      // Option A: DOCX doc-level hint propagation for low-signal structured_word blocks.
      const docHintByDocId = computeDocHintSegmentByDocId(visualAssetsPass2 as any, { minMajorityPct: 0.6 });

      let visualAssets = visualAssetsPass2.map((v: any) => {
        if (!isStructuredWordSectionAsset(v)) return v;
        if (isEmptyStructuredWordSectionAsset(v)) return v;
        const docId = typeof v?.document_id === "string" ? v.document_id : null;
        if (!docId) return v;
        const hint = docHintByDocId.get(docId) ?? null;
        if (!hint) return v;

        const persisted = pickNonUnknownSegment(v?.persisted_segment_key);
        if (persisted) return v;

        const computedSeg = normalizeAnalystSegment(v?.computed_segment);
        if (computedSeg && computedSeg !== "unknown") return v;

        const src = typeof v?.segment_source === "string" ? String(v.segment_source) : "";
        if (src === "human_override" || src === "human_override_v1" || src.startsWith("human_override_")) return v;

        const id = typeof v?.visual_asset_id === "string" ? v.visual_asset_id : typeof v?.id === "string" ? v.id : null;
        if (!id) return v;
        const base = segmentInputByVisualId.get(id);
        if (!base) return v;

        const recomputed = classifySegment({ ...base, hint_segment: hint });
        const seg = normalizeAnalystSegment(recomputed.segment) ?? "unknown";
        if (seg === "unknown") return v;

        return {
          ...v,
          segment: seg,
          effective_segment: seg,
          segment_source: "doc_hint_v1",
          segment_confidence: recomputed.confidence,
          computed_segment: seg,
          computed_confidence: recomputed.confidence,
          ...(docHintRequested ? { doc_hint_segment: hint } : {}),
          computed_reason: {
            rule_id: "DOCX_DOC_HINT_FALLBACK",
            doc_hint_segment: hint,
          },
        };
      });

      // Option B: cue-based rescue for structured_word blocks that are still unknown.
      // Conservative: only runs when there is no persisted override and computed remains unknown.
      visualAssets = visualAssets.map((v: any) => {
        if (!isStructuredWordSectionAsset(v)) return v;
        if (isEmptyStructuredWordSectionAsset(v)) return v;

        const persisted = pickNonUnknownSegment(v?.persisted_segment_key);
        if (persisted) return v;

        const computedSeg = normalizeAnalystSegment(v?.computed_segment);
        if (computedSeg && computedSeg !== "unknown") return v;

        const inferred = inferStructuredWordCueSegment(v);
        if (!inferred) return v;

        return {
          ...v,
          segment: inferred.segment,
          effective_segment: inferred.segment,
          segment_source: "docx_cue_v1",
          segment_confidence: inferred.confidence,
          computed_segment: inferred.segment,
          computed_confidence: inferred.confidence,
          computed_reason: {
            rule_id: "DOCX_CUE_RULE_V1",
            matched: inferred.matched,
          },
        };
      });

      // Policy: Excel (XLSX) should be structured-first.
      // - Hide OCR by default (opt-in via ?include_ocr=true).
      // - Hide image previews by default (opt-in via ?include_images=true).
      if (!includeOcrRequested || !includeImagesRequested) {
        const isExcelDoc = (v: any): boolean => {
          const title = typeof v?.document_title === "string" ? v.document_title.toLowerCase() : "";
          const mime = typeof v?.document_mime_type === "string" ? v.document_mime_type.toLowerCase() : "";
          const docType = typeof v?.document_type === "string" ? v.document_type.toLowerCase() : "";
          if (mime.includes("spreadsheet") || mime.includes("excel") || mime.includes("xlsx")) return true;
          if (title.endsWith(".xlsx") || title.includes(".xlsx")) return true;
          if (docType.includes("spreadsheet") || docType.includes("excel")) return true;
          return false;
        };

        visualAssets = (visualAssets as any[]).map((v: any) => {
          if (!isExcelDoc(v)) return v;
          const next: any = { ...v };
          if (!includeOcrRequested) {
            next.ocr_text = null;
            next.ocr_blocks = null;
            next.ocr_suppressed = true;
          }
          if (!includeImagesRequested) {
            next.image_uri = null;
            next.image_hash = null;
          }
          return next;
        });
      }

      let wordGroupingStatsForVisualAssets: WordGroupingStats | null = null;

      const groupedVisualAssets = (() => {
        if (!groupWordRequested) return undefined;
        const { groups: rawGroups, stats } = groupWordVisualAssetsByDocumentWithStats(visualAssets as any, { maxBlocksPerGroup: 8, maxCapturedChars: 1500 });
        wordGroupingStatsForVisualAssets = stats;

        const byId = new Map<string, any>();
        for (const v of visualAssets as any[]) {
          const id = typeof v?.id === "string" ? v.id : typeof v?.visual_asset_id === "string" ? v.visual_asset_id : null;
          if (id) byId.set(id, v);
        }

        return rawGroups.map((g: any) => {
          const docId = typeof g?.document_id === "string" ? g.document_id : null;
          const membersRaw = Array.isArray(g?.member_visual_asset_ids) ? g.member_visual_asset_ids : [];
          const members = membersRaw
            .map((id: any) => (typeof id === "string" ? byId.get(id) : null))
            .filter((v: any) => v && typeof v === "object");

          members.sort((a: any, b: any) => {
            const pa = typeof a?.page_index === "number" ? a.page_index : 1e9;
            const pb = typeof b?.page_index === "number" ? b.page_index : 1e9;
            if (pa !== pb) return pa - pb;
            const ca = typeof a?.created_at === "string" ? a.created_at : "";
            const cb = typeof b?.created_at === "string" ? b.created_at : "";
            if (ca !== cb) return ca.localeCompare(cb);
            return String(a?.id ?? "").localeCompare(String(b?.id ?? ""));
          });

          const groupText = buildDeterministicGroupCapturedText(members, 1500);

          const hintSegment =
            majorityNonUnknownSegment([
              ...members.map((m: any) => m?.persisted_segment_key),
              ...members.map((m: any) => m?.effective_segment),
              ...members.map((m: any) => (m?.structured_json as any)?.segment_key),
              // Segment-bucketed grouping: even if members are low-signal, the group already has a segment_key.
              g?.segment_key,
            ]) ?? null;

          // Persisted must ONLY come from persisted member segments; never from computed/effective hints.
          const persistedSegmentKey = majorityNonUnknownSegment(members.map((m: any) => m?.persisted_segment_key)) ?? null;

          const brandModel = docId ? brandModelByDocId.get(docId) ?? buildBrandModel([]) : buildBrandModel([]);
          const blacklist = brandModel.phrases;
          const brandInfo = docId ? brandNameByDocId.get(docId) ?? { brand: null, confidence: null } : { brand: null, confidence: null };

          const computed = classifySegment({
            ocr_text: null,
            ocr_snippet: groupText ? groupText.slice(0, 140) : null,
            structured_kind: "word_section",
            structured_summary: null,
            structured_json: {
              kind: "word_section",
              heading: typeof g?.heading === "string" ? g.heading : null,
              paragraphs: groupText ? [groupText] : [],
              text_snippet: groupText,
              segment_key: hintSegment,
            },
            asset_type: "structured_word_group",
            page_index: typeof g?.page_index === "number" ? g.page_index : null,
            slide_title: null,
            slide_title_confidence: null,
            evidence_snippets: Array.isArray(g?.evidence_snippets) ? g.evidence_snippets : [],
            brand_blacklist: blacklist,
            brand_name: brandInfo.brand,
            extractor_version: "structured_native_v1",
            quality_source: "structured_word",
            hint_segment: hintSegment,
            enable_debug: false,
            include_debug_text_snippet: false,
            disable_structured_segment_key_signal: true,
            disable_structured_segment_key_fallback: true,
          });

          const computedReasonRaw = computed.debug && typeof computed.debug === "object" ? computed.debug : null;
          const unknownReasonCode = typeof (computedReasonRaw as any)?.unknown_reason_code === "string" ? String((computedReasonRaw as any).unknown_reason_code) : null;

          const computedSegment =
            computed.segment === "unknown" && hintSegment && (unknownReasonCode === "NO_TEXT" || unknownReasonCode === "LOW_SIGNAL")
              ? hintSegment
              : computed.segment;

          const computedConfidence =
            computed.segment === "unknown" && hintSegment && (unknownReasonCode === "NO_TEXT" || unknownReasonCode === "LOW_SIGNAL")
              ? Math.max(0.2, computed.confidence)
              : computed.confidence;

          const computedReason =
            computed.segment === "unknown" && hintSegment && (unknownReasonCode === "NO_TEXT" || unknownReasonCode === "LOW_SIGNAL")
              ? {
                  ...(computedReasonRaw ?? {}),
                  rule_id: "STRUCTURED_HINT_FALLBACK",
                  unknown_reason_code: null,
                }
              : computedReasonRaw;

          const hasHumanOverride = members.some((m: any) => {
            const seg = pickNonUnknownSegment(m?.persisted_segment_key);
            const src = typeof m?.segment_source === "string" ? String(m.segment_source) : "";
            if (!seg || !persistedSegmentKey) return false;
            return seg === persistedSegmentKey && (src === "human_override" || src === "human_override_v1" || src.startsWith("human_override_"));
          });

          const effectiveSegment = hasHumanOverride
            ? (persistedSegmentKey ?? computedSegment)
            : persistedSegmentKey
              ? persistedSegmentKey
              : computedSegment;

          const segmentSource = (() => {
            if (hasHumanOverride && persistedSegmentKey) return "human_override_v1";
            if (persistedSegmentKey) return "persisted_v0";
            return "computed_v1";
          })();

          const segmentConfidence = persistedSegmentKey ? 1 : computedConfidence;

          return {
            ...g,
            captured_text: groupText,
            persisted_segment_key: persistedSegmentKey,
            persisted_segment_source: persistedSegmentKey ? "group_majority" : null,
            computed_segment: computedSegment,
            computed_confidence: computedConfidence,
            computed_reason: computedReason,
            effective_segment: effectiveSegment,
            segment_source: segmentSource,
            segment_confidence: segmentConfidence,
            segment_promoted_at: null,
            segment_overridden_at: null,
            segment_override_note: null,
          };
        });
      })();

      // Option B: if grouping requested, inherit group segment to any remaining unknown raw members (non-destructive).
      if (groupWordRequested && Array.isArray(groupedVisualAssets)) {
        const memberToGroupMeta = new Map<string, { segment: AnalystSegment; visual_asset_group_id: string | null }>();
        for (const g of groupedVisualAssets as any[]) {
          const seg = pickNonUnknownSegment(g?.effective_segment);
          if (!seg) continue;
          const groupIdRaw = typeof g?.visual_asset_group_id === "string" ? g.visual_asset_group_id : typeof g?.group_id === "string" ? g.group_id : "";
          const groupId = groupIdRaw && groupIdRaw.trim().length > 0 ? groupIdRaw.trim() : null;
          const members = Array.isArray(g?.member_visual_asset_ids) ? g.member_visual_asset_ids : [];
          for (const mid of members) {
            if (typeof mid !== "string" || !mid.trim()) continue;
            if (!memberToGroupMeta.has(mid)) memberToGroupMeta.set(mid, { segment: seg, visual_asset_group_id: groupId });
          }
        }

        for (let i = 0; i < visualAssets.length; i++) {
          const v = visualAssets[i] as any;
          if (!isStructuredWordSectionAsset(v)) continue;
          const id = typeof v?.visual_asset_id === "string" ? v.visual_asset_id : typeof v?.id === "string" ? v.id : null;
          if (!id) continue;
          const meta = memberToGroupMeta.get(id) ?? null;
          if (!meta) continue;
          const groupSeg = meta.segment;
          const persisted = pickNonUnknownSegment(v?.persisted_segment_key);
          if (persisted) continue;
          const effective = normalizeAnalystSegment(v?.effective_segment);
          if (effective && effective !== "unknown") continue;
          const src = typeof v?.segment_source === "string" ? String(v.segment_source) : "";
          if (src === "human_override" || src === "human_override_v1" || src.startsWith("human_override_")) continue;
          if (isEmptyStructuredWordSectionAsset(v)) continue;

          visualAssets[i] = {
            ...v,
            segment: groupSeg,
            effective_segment: groupSeg,
            segment_source: "group_inherit_v1",
            segment_confidence: Math.max(typeof v?.segment_confidence === "number" ? v.segment_confidence : 0, 0.2),
            computed_segment: groupSeg,
            computed_confidence: Math.max(typeof v?.computed_confidence === "number" ? v.computed_confidence : 0, 0.2),
            computed_reason: {
              rule_id: "GROUP_MEMBER_INHERIT",
              inherited_from_visual_asset_group_id: meta.visual_asset_group_id,
            },
          };
        }
      }

      // Optional inspector UX: expose doc-level hint segment on structured_word blocks.
      if (docHintRequested) {
        for (let i = 0; i < visualAssets.length; i++) {
          const v = visualAssets[i] as any;
          if (!isStructuredWordSectionAsset(v)) continue;
          const docId = typeof v?.document_id === "string" ? v.document_id : null;
          if (!docId) continue;
          const hint = docHintByDocId.get(docId) ?? null;
          if (!hint) continue;
          if (typeof v?.doc_hint_segment === "string" && v.doc_hint_segment.trim().length > 0) continue;
          visualAssets[i] = { ...v, doc_hint_segment: hint };
        }
      }

      // DEV-only logging: remaining true-unknown structured_word blocks should correlate with empty blocks.
      const devLogUnknown = process.env.NODE_ENV !== "production" && process.env.DDAI_DEV_LOG_DOCX_UNKNOWN === "1";
      if (devLogUnknown) {
        try {
          const unknowns = (visualAssets as any[])
            .filter((v: any) => isStructuredWordSectionAsset(v))
            .filter((v: any) => {
              const eff = normalizeAnalystSegment(v?.effective_segment) ?? "unknown";
              return eff === "unknown";
            })
            .slice(0, 50)
            .map((v: any) => {
              const id = typeof v?.visual_asset_id === "string" ? v.visual_asset_id : typeof v?.id === "string" ? v.id : null;
              const docId = typeof v?.document_id === "string" ? v.document_id : null;
              const stats = structuredWordContentStats(v);
              const hint = docId ? docHintByDocId.get(docId) ?? null : null;
              const base = id ? segmentInputByVisualId.get(id) : null;
              const debug = base ? classifySegment({ ...base, hint_segment: hint, enable_debug: true, include_debug_text_snippet: false }).debug : undefined;
              return {
                id,
                document_id: docId,
                page_index: typeof v?.page_index === "number" ? v.page_index : null,
                text_snippet_len: stats.textSnippetLen,
                paragraphs_len: stats.paragraphsLen,
                unknown_reason_code: typeof (debug as any)?.unknown_reason_code === "string" ? (debug as any).unknown_reason_code : null,
                rule_id: typeof (debug as any)?.rule_id === "string" ? (debug as any).rule_id : null,
                doc_hint_segment: hint,
              };
            });
          console.log("[DEV docx_unknown structured_word]", { deal_id: dealId, n: unknowns.length, unknowns });
        } catch {
          // ignore
        }
      }

      const wordGroupingStatsFinal: WordGroupingStats = wordGroupingStatsForVisualAssets ?? { word_members_skipped_empty: 0, word_groups_skipped_empty: 0 };

      // System-wide guarantee: do not return effective_segment="unknown" when we can reasonably infer
      // a segment without burning tokens.
      //
      // Step 1: document-majority fallback (non-destructive, only for remaining unknowns).
      // Step 1.5: cue-based rescue for low-signal pages (non-destructive, only for remaining unknowns).
      // Step 2: final default segment for any remaining unknowns.
      const docMajority = (() => {
        const countsByDoc = new Map<string, Map<AnalystSegment, number>>();
        const totalsByDoc = new Map<string, number>();

        const shouldCountForMajority = (v: any): boolean => {
          const seg = normalizeAnalystSegment(v?.effective_segment ?? v?.segment) ?? "unknown";
          if (seg === "unknown") return false;

          const src = typeof v?.segment_source === "string" ? String(v.segment_source) : "";
          // Avoid reinforcement loops by excluding propagated/rescued sources.
          if (src === "neighbor_hint_v1" || src === "doc_majority_v1" || src === "default_fallback_v1") return false;
          return true;
        };

        for (const v of visualAssets as any[]) {
          const docId = typeof v?.document_id === "string" ? v.document_id : null;
          if (!docId) continue;
          if (!shouldCountForMajority(v)) continue;

          const seg = (normalizeAnalystSegment(v?.effective_segment ?? v?.segment) ?? "unknown") as AnalystSegment;
          const map = countsByDoc.get(docId) ?? new Map<AnalystSegment, number>();
          map.set(seg, (map.get(seg) ?? 0) + 1);
          countsByDoc.set(docId, map);
          totalsByDoc.set(docId, (totalsByDoc.get(docId) ?? 0) + 1);
        }

        const out = new Map<string, { segment: AnalystSegment; pct: number; count: number; total: number }>();
        for (const [docId, map] of countsByDoc.entries()) {
          const total = totalsByDoc.get(docId) ?? 0;
          if (total <= 0) continue;

          let bestSeg: AnalystSegment | null = null;
          let bestCount = 0;
          for (const [seg, n] of map.entries()) {
            if (n > bestCount) {
              bestSeg = seg;
              bestCount = n;
            }
          }

          if (!bestSeg) continue;
          const pct = bestCount / total;
          out.set(docId, { segment: bestSeg, pct, count: bestCount, total });
        }
        return out;
      })();

      const docMajorityMinPct = 0.55;
      const docMajorityMinCount = 2;

      const cueRescue = cueRescueLowSignal;

      // Cue-based rescue pass (before doc-majority, before default fallback).
      for (let i = 0; i < visualAssets.length; i++) {
        const v = visualAssets[i] as any;
        const seg = normalizeAnalystSegment(v?.effective_segment ?? v?.segment) ?? "unknown";
        if (seg !== "unknown") continue;

        const src = typeof v?.segment_source === "string" ? String(v.segment_source) : "";
        if (src === "human_override" || src === "human_override_v1" || src.startsWith("human_override_")) continue;

        const persisted = pickNonUnknownSegment(v?.persisted_segment_key);
        if (persisted) continue;

        const reason = typeof v?.computed_reason?.unknown_reason_code === "string" ? String(v.computed_reason.unknown_reason_code) : null;
        if (reason && reason !== "LOW_SIGNAL" && reason !== "NO_TEXT") continue;

        const inferred = cueRescue(v);
        if (!inferred) continue;

        visualAssets[i] = {
          ...v,
          segment: inferred.segment,
          effective_segment: inferred.segment,
          segment_source: "cue_rescue_v1",
          segment_confidence: inferred.confidence,
          computed_segment: inferred.segment,
          computed_confidence: inferred.confidence,
          computed_reason: {
            ...(typeof v?.computed_reason === "object" && v.computed_reason ? v.computed_reason : {}),
            rule_id: "CUE_RESCUE_V1",
            matched: inferred.matched,
          },
        };
      }

      // Vision hint rescue pass (lightweight local model).
      // Only applies when we still have unknown and there is no persisted override.
      for (let i = 0; i < visualAssets.length; i++) {
        const v = visualAssets[i] as any;
        const seg = normalizeAnalystSegment(v?.effective_segment ?? v?.segment) ?? "unknown";
        if (seg !== "unknown") continue;

        const src = typeof v?.segment_source === "string" ? String(v.segment_source) : "";
        if (src === "human_override" || src === "human_override_v1" || src.startsWith("human_override_")) continue;

        const persisted = pickNonUnknownSegment(v?.persisted_segment_key);
        if (persisted) continue;

        const vu = v?.structured_json?.vision_understanding_v1;
        if (!vu || typeof vu !== "object") continue;

        const hintRaw = typeof vu.segment_hint === "string" ? String(vu.segment_hint) : "";
        const hint = hintRaw ? normalizeAnalystSegment(hintRaw) : null;
        if (!hint || hint === "unknown") continue;

        const confRaw = (vu as any).confidence;
        const conf = typeof confRaw === "number" && Number.isFinite(confRaw) ? confRaw : 0.6;
        if (conf < 0.45) continue;

        visualAssets[i] = {
          ...v,
          segment: hint,
          effective_segment: hint,
          segment_source: "vision_hint_rescue_v1",
          segment_confidence: Math.max(0.35, Math.min(0.75, conf)),
          computed_segment: hint,
          computed_confidence: Math.max(0.35, Math.min(0.75, conf)),
          computed_reason: {
            ...(typeof v?.computed_reason === "object" && v.computed_reason ? v.computed_reason : {}),
            rule_id: "VISION_HINT_RESCUE_V1",
            vision_confidence: conf,
          },
        };
      }

      for (let i = 0; i < visualAssets.length; i++) {
        const v = visualAssets[i] as any;
        const seg = normalizeAnalystSegment(v?.effective_segment ?? v?.segment) ?? "unknown";
        if (seg !== "unknown") continue;

        const src = typeof v?.segment_source === "string" ? String(v.segment_source) : "";
        if (src === "human_override" || src === "human_override_v1" || src.startsWith("human_override_")) continue;

        const persisted = pickNonUnknownSegment(v?.persisted_segment_key);
        if (persisted) continue;

        const reason = typeof v?.computed_reason?.unknown_reason_code === "string" ? String(v.computed_reason.unknown_reason_code) : null;
        if (reason && reason !== "LOW_SIGNAL" && reason !== "NO_TEXT") continue;

        const docId = typeof v?.document_id === "string" ? v.document_id : null;
        if (!docId) continue;
        const m = docMajority.get(docId);
        if (!m) continue;
        if (m.count < docMajorityMinCount) continue;
        if (m.pct < docMajorityMinPct) continue;

        visualAssets[i] = {
          ...v,
          segment: m.segment,
          effective_segment: m.segment,
          segment_source: "doc_majority_v1",
          segment_confidence: Math.max(0.25, Math.min(0.6, m.pct)),
          computed_segment: m.segment,
          computed_confidence: Math.max(0.25, Math.min(0.6, m.pct)),
          computed_reason: {
            ...(typeof v?.computed_reason === "object" && v.computed_reason ? v.computed_reason : {}),
            rule_id: "DOC_MAJORITY_FALLBACK",
            majority_pct: m.pct,
            majority_count: m.count,
            majority_total: m.total,
          },
        };
      }

      // Final fallback: ensure every node has a segment (even if low confidence).
      for (let i = 0; i < visualAssets.length; i++) {
        const v = visualAssets[i] as any;
        const seg = normalizeAnalystSegment(v?.effective_segment ?? v?.segment) ?? "unknown";
        if (seg !== "unknown") continue;

        const src = typeof v?.segment_source === "string" ? String(v.segment_source) : "";
        if (src === "human_override" || src === "human_override_v1" || src.startsWith("human_override_")) continue;

        const persisted = pickNonUnknownSegment(v?.persisted_segment_key);
        if (persisted) continue;

        visualAssets[i] = {
          ...v,
          segment: "overview",
          effective_segment: "overview",
          segment_source: "default_fallback_v1",
          segment_confidence: 0.1,
          computed_segment: "overview",
          computed_confidence: 0.1,
          computed_reason: {
            ...(typeof v?.computed_reason === "object" && v.computed_reason ? v.computed_reason : {}),
            rule_id: "DEFAULT_SEGMENT_FALLBACK",
          },
        };
      }

      // UI clarity: suppress per-page "page_image_fallback" rows when a higher-quality asset
      // exists for the same document+page. These rows typically have no OCR/title and get the
      // default segment fallback (overview), which looks like a duplicate slide.
      if (!includePageFallbackRequested && visualAssets.length > 0) {
        const keyOf = (a: any): string | null => {
          const docId = typeof a?.document_id === "string" ? a.document_id : null;
          const page = typeof a?.page_index === "number" && Number.isFinite(a.page_index) ? a.page_index : null;
          if (!docId || page == null) return null;
          return `${docId}::${page}`;
        };

        const isPageFallback = (a: any): boolean => {
          const qSource = typeof a?.quality_flags?.source === "string" ? String(a.quality_flags.source) : "";
          const segSrc = typeof a?.segment_source === "string" ? String(a.segment_source) : "";
          const extractorVer = typeof a?.extractor_version === "string" ? String(a.extractor_version) : "";
          const ruleId = typeof a?.computed_reason?.rule_id === "string" ? String(a.computed_reason.rule_id) : "";
          return (
            qSource === "page_image_fallback" ||
            segSrc === "default_fallback_v1" ||
            extractorVer === "default_fallback_v1" ||
            ruleId === "DEFAULT_SEGMENT_FALLBACK"
          );
        };

        const hasNonFallbackByKey = new Map<string, boolean>();
        for (const a of visualAssets as any[]) {
          const k = keyOf(a);
          if (!k) continue;
          if (!isPageFallback(a)) {
            hasNonFallbackByKey.set(k, true);
          }
        }

        visualAssets = (visualAssets as any[]).filter((a: any) => {
          const k = keyOf(a);
          if (!k) return true;
          if (!isPageFallback(a)) return true;
          return !hasNonFallbackByKey.get(k);
        }) as any;
      }

      // Never return persisted signed URLs; mint fresh R2 signed URLs per request.
      if (includeImagesRequested && visualAssets.length > 0) {
        visualAssets = await Promise.all(
          (visualAssets as any[]).map(async (v: any) => ({
            ...v,
            image_uri: typeof v?.image_uri === "string" && v.image_uri.trim() ? await resolveVisualAssetImageUriForApi(v.image_uri) : null,
          }))
        );
      }

      return reply.send({
        deal_id: dealId,
        visual_assets: visualAssets,
			...(groupWordRequested
				? {
					grouped_visual_assets: groupedVisualAssets,
					warnings_counters: {
						word_members_skipped_empty: wordGroupingStatsFinal.word_members_skipped_empty,
						word_groups_skipped_empty: wordGroupingStatsFinal.word_groups_skipped_empty,
					},
				}
				: {}),
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to load visual assets";
      const payload = { error: "internal_error", message, deal_id: dealId };
      const stack = err instanceof Error ? err.stack : undefined;
      request.log?.error?.(
        { ...logCtx, err: process.env.NODE_ENV !== "production" ? err : undefined, stack: process.env.NODE_ENV !== "production" ? stack : undefined },
        "deal_visual_assets.error"
      );
      return reply.status(500).send(payload);
    }
  });

}
