/**
 * apps/api/src/routes/deals/index.ts
 * Orchestrator — same public surface as original deals.ts (PR12)
 * AUTO-GENERATED by scripts/dev/split-deals-final.py
 */

import type { FastifyInstance } from "fastify";
import { getPool } from "../../lib/db";
import { enqueueJob } from "../../services/jobs";
import { objectExistsInR2 } from "../../lib/r2";
import type { DealRoutesPool } from "./_shared";

// ── Public re-exports (preserve original deals.ts surface) ─────────────────
export { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";
export type { QueryResult } from "./_shared";
export { normalizeWarningsForPersistence, buildScoreBreakdownV1 } from "./_shared";

// ── Sub-module imports ────────────────────────────────────────────────────────
import { registerInvestorInsightsRoutes } from "./investor-insights.routes";
import { registerDealAnalysisRoutes } from "./deal-analysis.routes";
import { registerDealSegmentsRoutes } from "./deal-segments.routes";
import { registerDealIngestionRoutes } from "./deal-ingestion.routes";
import { registerDealCoreRoutes } from "./deal-core.routes";
import { registerDealOperationsRoutes } from "./deal-operations.routes";
import { registerIntelligenceRoutes } from "./intelligence.routes";

// ── Main entry point ──────────────────────────────────────────────────────────

export async function registerDealRoutes(
  app: FastifyInstance,
  poolOverride?: any,
  deps?: {
    enqueueJob?: typeof enqueueJob;
    jobs?: { queue?: any };
    r2?: { objectExistsInR2?: typeof objectExistsInR2 };
    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };
  }
): Promise<void> {
  const pool = (poolOverride ?? getPool()) as DealRoutesPool;
  const enqueue = deps?.enqueueJob ?? enqueueJob;
  const r2 = { objectExistsInR2: deps?.r2?.objectExistsInR2 ?? objectExistsInR2 };
  const debugRoutesEnabled = process.env.DEBUG_ROUTES === "1" || process.env.NODE_ENV !== "production";

  await registerInvestorInsightsRoutes(app, pool, enqueue, r2, debugRoutesEnabled, deps);
  await registerDealAnalysisRoutes(app, pool, enqueue, r2, debugRoutesEnabled, deps);
  await registerDealSegmentsRoutes(app, pool, enqueue, r2, debugRoutesEnabled, deps);
  await registerDealIngestionRoutes(app, pool, enqueue, r2, debugRoutesEnabled, deps);
  await registerDealCoreRoutes(app, pool, enqueue, r2, debugRoutesEnabled, deps);
  await registerDealOperationsRoutes(app, pool, enqueue, r2, debugRoutesEnabled, deps);
  await registerIntelligenceRoutes(app, pool);
}
