/**
 * apps/api/src/routes/deals/investor-insights.routes.ts
 * registerInvestorInsightsRoutes — extracted from deals.ts (PR12)
 * AUTO-GENERATED by scripts/dev/split-deals-final.py
 */
import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import { fetchPhaseBVisualsFromDb } from "../../lib/phaseb-visuals";
import { getUploadsRootDir } from "../../plugins/uploads-static";
import { getPool } from "../../lib/db";
import { resolveVisualAssetImageUriForApi } from "../../lib/visual-asset-image-uri";
import type { Deal } from "@dealdecision/contracts";
import type { JobStatus, JobType } from "@dealdecision/contracts";
import { QUEUE_NAMES } from "@dealdecision/core";
import { enqueueBullmqJob, enqueueJob, insertJobRow } from "../../services/jobs";
import { getQueues } from "../../lib/queue";
import { runIdempotentOperation } from "../../lib/jobs";
import { getStorageDriver } from "../../lib/storage-contract";
import { autoProgressDealStage } from "../../services/stageProgression";
import { updateDealPriority, updateAllDealPriorities } from "../../services/priorityClassification";
import { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";
import { getNodeEvidenceGateForDeal } from "../../services/nodeEvidenceGateForDeal";
import { normalizeDealName } from "../../lib/normalize-deal-name";
import { buildDocumentsDigest } from "../../lib/documents-digest";
import type { DocumentsDigestV1 } from "../../lib/documents-digest";
import { objectExistsInR2 } from "../../lib/r2";
import {
  purgeDealCascade,
  isPurgeDealNotFoundError,
  sanitizeText,
  getDocumentCapabilities,
  buildDealScoringInputV0FromLineage,
  getSegmentConfidenceThresholds,
  detectContentArchetypeTags,
  buildOrchestratorReportV1,
} from "@dealdecision/core";
import {
  BrandModel,
  PageInput,
  buildBrandModel,
  inferDocumentBrandName,
  inferSlideTitleForSlide,
  isLikelyGarbledSlideTitle,
  normalizePhrase,
} from "../../lib/slide-title";
import {
  buildClassificationText,
  buildSegmentFeatures,
  classifySegment,
  normalizeAnalystSegment,
  type AnalystSegment,
  type SegmentClassifierInput,
} from "../../lib/analyst-segment";
import {
  groupWordVisualAssetsByDocument,
  groupWordVisualAssetsByDocumentWithStats,
  type WordGroupingStats,
} from "../../lib/word-visual-grouping";
import { fetchPageUnderstandingReadinessForDeal } from "../../lib/deal-page-understanding-readiness";
import { ensureDocumentsReadyForAnalysis } from "../../lib/ensure-documents-ready-for-analysis";
import { getCanonicalFieldsForAI } from "../../lib/canonical-fields-for-ai";
import type {
  QueryResult,
  DealRoutesPool,
  DealRoutesClient,
  DealApiMode,
  AutoProfileDocRow,
  DealRow,
  DIOAggregateRow,
  ScoreBreakdownSectionKey,
  EvidenceRow,
  StatusSummaryAnalysis,
  StatusSummaryReport,
  StatusSummaryEvidenceGate,
  StatusSummary,
} from "./_shared";
import {
  hasTable,
  hasColumn,
  getColumnDataType,
  isUuid,
  stripEvidenceFromExecutiveSummary,
  stripEvidenceFromClaims,
  parseDealApiMode,
  bestEffortReadinessJobPresenceCheck,
  parseBoolQ,
  computeOcrV2CleanText,
  pickNonUnknownSegment,
  majorityNonUnknownSegment,
  isStructuredWordSectionAsset,
  structuredWordContentStats,
  isEmptyStructuredWordSectionAsset,
  computeDocHintSegmentByDocId,
  applyNeighborHintPropagationToAssets,
  buildDeterministicGroupCapturedText,
  extractStructuredWordTextForCue,
  inferStructuredWordCueSegment,
  requireDestructiveAuth,
  dealStageEnum,
  dealPriorityEnum,
  normalizeDealTrend,
  dealTrendEnum,
  dealCreateSchema,
  dealDraftCreateSchema,
  dealConfirmProfileSchema,
  sanitizeProfileValue,
  extractLabeledValue,
  isGenericCandidateName,
  deriveNameFromFilenameLike,
  extractCompanyFromEarlyText,
  computeAutoProfileFromDocuments,
  normalizeWarningsForPersistence,
  jsonbParam,
  dealUpdateSchema,
  llmPhaseModeEnum,
  parseNullableNumber,
  SCORE_BREAKDOWN_SECTION_ORDER,
  CLAIM_CATEGORY_SECTION_MAP,
  normalizeCategory,
  sectionForCategory,
  buildScoreBreakdownV1,
  collectEvidenceIdsFromClaims,
  getEvidenceByIds,
  getDocumentIndex,
  fetchEvidenceSamplesBySection,
  normalizeEvidenceSnippet,
  BUSINESS_MODEL_STRONG_REGEX,
  deriveSectionKeyFromClaim,
  ensureEvidenceLinksForClaims,
  buildPhase1ScoreEvidence,
  buildScoreEvidenceFromBreakdown,
  mapDeal,
  safeJsonValue,
  ocrSnippet,
  deriveStructuredSummary,
  cueRescueLowSignal,
  deriveBestExtractionConfidence,
  mapAnalysisJobStatus,
  mapReportRowStatus,
  maxIsoTs,
  buildStatusSummary,
} from "./_shared";

export async function registerInvestorInsightsRoutes(
  app: FastifyInstance,
  pool: DealRoutesPool,
  enqueue: typeof enqueueJob,
  r2: { objectExistsInR2: typeof objectExistsInR2 },
  debugRoutesEnabled: boolean,
  deps?: {
    enqueueJob?: typeof enqueueJob;
    jobs?: { queue?: any };
    r2?: { objectExistsInR2?: typeof objectExistsInR2 };
    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };
  }
): Promise<void> {
  app.post("/api/v1/deals/:deal_id/investor-insights/generate", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    // Deterministic dedup key: allows one queued/running manual-generate per deal per version.
    // Format mirrors makeJobId("investor_insights", [dealId, "v1", "manual_generate"]) from worker.
    const jobId = `investor_insights__${dealId}__v1__manual_generate`;

    const insightsQueue = deps?.investorInsightsQueue ?? (getQueues().investorInsightsQueue as any);
    try {
      await insightsQueue.add(
        "generate_investor_insights",
        { deal_id: dealId, engine_version: "v1", triggered_by: "manual_generate", force_recompute: true },
        { jobId, removeOnComplete: true, removeOnFail: false, attempts: 3, backoff: { type: "exponential", delay: 1000 } }
      );
    } catch (err) {
      console.error("[investor-insights] enqueue_failed", { dealId, err: err instanceof Error ? err.message : String(err) });
      return reply.status(500).send({ error: "enqueue_failed" });
    }

    return reply.status(202).send({ ok: true });
  });

  // Investor Insight Engine – Stage 0: force a fresh regeneration, bypassing BullMQ dedup.
  // Uses a timestamp-keyed jobId so every call enqueues a new job regardless of prior state.
  // Returns 202 { ok: true, deal_id, enqueued: true }.
  //
  // Phase J invariant: governed summary must resolve via resolveGovernedSummaryWithCache.
  // force_recompute=true bypasses the upstream-fingerprint dedup index, but the governed
  // summary cache (fingerprint-based) is evaluated independently inside the worker —
  // unchanged inputs will still produce a cache hit even on a forced regenerate.
  app.post("/api/v1/deals/:deal_id/investor-insights/regenerate", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    // ── Pre-check: does a usable render_package already exist? ───────────────
    // Used below so that when DPU is partial but a prior report was already
    // generated, the UI can show the existing report with a soft banner instead
    // of a full-screen "Preparing Documents…" spinner.
    let hasExistingRenderPackage = false;
    try {
      const existingResult = await (pool as any).query(
        `SELECT id FROM investor_insight_reports
          WHERE deal_id = $1 AND render_package IS NOT NULL
          ORDER BY updated_at DESC LIMIT 1`,
        [dealId]
      );
      hasExistingRenderPackage = Array.isArray(existingResult?.rows) && existingResult.rows.length > 0;
    } catch {
      // best-effort — if the check fails, default to false (full spinner)
    }

    // ── Gate 1: DPU preflight ─────────────────────────────────────────────────
    // Before enqueueing investor-insights, verify DPU readiness. When DPU is
    // missing, stale, or partially covered, auto-enqueue DPU backfill and return
    // 202 { status: "preparing_documents" } so the UI can poll rather than
    // proceeding straight to an insights job that would fail the DPU gate.
    //
    // Fail-open: if the preflight itself throws (e.g. pool unavailable in test),
    // we log and proceed rather than blocking the user.
    try {
      const prep = await ensureDocumentsReadyForAnalysis({
        pool: pool as any,
        dealId,
        requirePageUnderstanding: true,
        pageUnderstandingVersion: "page_understanding_v1",
        logger: request.log,
        enqueue,
      });

      if (!prep.ready && prep.action === "enqueue_dpu_backfill") {
        // Map internal blocked_reason to spec-normalized client values:
        //   "DPU_STALE"     → "dpu_stale"
        //   null + no rows  → "missing_dpu"
        //   null + partial  → "dpu_partial"
        const clientBlockedReason = (() => {
          const raw = prep.blocked_reason;
          if (raw === "DPU_STALE") return "dpu_stale";
          const expPages = prep.readiness.expected_pages_total ?? 0;
          const dpuRows = prep.readiness.dpu_rows_total ?? 0;
          const missingPages = prep.readiness.missing_pages_total ?? 0;
          if (expPages > 0 && dpuRows === 0) return "missing_dpu";
          if (expPages > 0 && dpuRows > 0 && missingPages > 0) return "dpu_partial";
          return raw ?? "missing_dpu";
        })();

        request.log.info(
          {
            event: "REGENERATE_GATE1_DPU_BACKFILL",
            deal_id: dealId,
            blocked_reason: clientBlockedReason,
            docs_fingerprint: prep.docs_fingerprint,
            expected_pages_total: prep.readiness.expected_pages_total,
            dpu_rows_total: prep.readiness.dpu_rows_total,
            missing_pages_total: prep.readiness.missing_pages_total,
            enqueued: prep.enqueued,
          },
          "investor-insights/regenerate DPU gate blocked — auto-enqueued backfill"
        );

        return reply.status(202).send({
          status: "preparing_documents",
          blocked_reason: clientBlockedReason,
          // true when a prior render_package already exists — UI should show a soft
          // "still processing" banner rather than a full-screen spinner.
          has_existing_render_package: hasExistingRenderPackage,
          action: "enqueue_dpu_backfill",
          poll_after_ms: prep.poll_after_ms ?? 1500,
          docs_fingerprint: prep.docs_fingerprint,
          expected_pages_total: prep.readiness.expected_pages_total ?? 0,
          dpu_rows_total: prep.readiness.dpu_rows_total ?? 0,
          missing_pages_total: prep.readiness.missing_pages_total ?? 0,
          enqueued: prep.enqueued,
          stale_diagnostics: prep.stale_diagnostics ?? null,
        });
      }
    } catch (err) {
      // Fail-open: DPU preflight failed (e.g. pool unavailable in tests), proceed with enqueueing.
      const msg = err instanceof Error ? err.message : String(err);
      request.log.warn(
        { event: "REGENERATE_GATE1_PREFLIGHT_FAILED", deal_id: dealId, err: msg },
        "Gate 1 DPU preflight failed — proceeding with insights enqueue"
      );
    }

    // Unique per-request jobId — bypasses BullMQ dedup so regenerate always enqueues.
    const jobId = `investor_insights__${dealId}__v1__manual_regenerate__${Date.now()}`;

    const body = (request.body ?? {}) as { override_llm_mode?: boolean };
    const overrideLlmMode = body.override_llm_mode === true;

    const insightsQueue = deps?.investorInsightsQueue ?? (getQueues().investorInsightsQueue as any);
    try {
      await insightsQueue.add(
        "generate_investor_insights",
        {
          deal_id: dealId,
          engine_version: "v1",
          triggered_by: "manual_regenerate",
          force_recompute: true,
          ...(overrideLlmMode && { override_llm_mode: true }),
        },
        { jobId, removeOnComplete: true, removeOnFail: false, attempts: 3, backoff: { type: "exponential", delay: 1000 } }
      );
    } catch (err) {
      console.error("[investor-insights] regenerate_enqueue_failed", { dealId, err: err instanceof Error ? err.message : String(err) });
      return reply.status(500).send({ error: "enqueue_failed" });
    }

    return reply.status(202).send({ ok: true, deal_id: dealId, enqueued: true });
  });

  // ── Investor Insight Engine: structured-JSON recovery endpoint ─────────────
  //
  // POST /api/v1/deals/:deal_id/investor-insights/recover
  //
  // Triggers a structured-JSON-only retry for a deal whose most recent report
  // is in deterministic_only status due to a recoverable G3 gate failure
  // (GATE_STRUCTURED_JSON_MISSING, _PARSE_FAILED, or _SCHEMA_MISMATCH).
  //
  // Passes mode="recover_structured_json" to the worker processor so a
  // DETERMINISTIC_ONLY_RECOVERY_* event trail is emitted and recovery metadata
  // is persisted in render_package.recovery_metadata.
  //
  // Returns:
  //   202 { ok: true, deal_id, enqueued: true }               — recovery queued
  //   400 { error: "invalid_deal_id" }                        — bad UUID
  //   500 { error: "enqueue_failed" }                         — BullMQ error
  //
  // Note: does NOT run a DPU preflight — recovery is specifically for structural
  // JSON readability failures that are unrelated to DPU coverage.
  app.post("/api/v1/deals/:deal_id/investor-insights/recover", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    // Unique per-request jobId so each recovery attempt is individually tracked.
    const jobId = `investor_insights__${dealId}__v1__recover__${Date.now()}`;

    const insightsQueue = deps?.investorInsightsQueue ?? (getQueues().investorInsightsQueue as any);
    try {
      await insightsQueue.add(
        "generate_investor_insights",
        {
          deal_id: dealId,
          engine_version: "v1",
          triggered_by: "manual_recover",
          force_recompute: true,
          mode: "recover_structured_json",
        },
        { jobId, removeOnComplete: true, removeOnFail: false, attempts: 3, backoff: { type: "exponential", delay: 1000 } }
      );
    } catch (err) {
      console.error("[investor-insights] recover_enqueue_failed", { dealId, err: err instanceof Error ? err.message : String(err) });
      return reply.status(500).send({ error: "enqueue_failed" });
    }

    return reply.status(202).send({ ok: true, deal_id: dealId, enqueued: true });
  });
  // POST /api/v1/deals/:deal_id/analysis/deal-terms
  //
  // Lightweight LLM synthesis endpoint used EXCLUSIVELY by the AI Analysis Tab
  // DealTermsCard component. Does NOT touch the investor insights pipeline,
  // render_package, or any governed_* section.
  //
  // Input:  { canonical_fields: Record<string, string | null> }
  // Output: { structure_summary, structure_assessment, missing_terms }


  // Investor Insight Engine – Stage 0: read the latest persisted report for a deal.
  // Returns { status: "not_started" } when the table is absent or no row exists.
  // report_payload is intentionally excluded to keep the response light.
  app.get("/api/v1/deals/:deal_id/investor-insights", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id", message: "deal_id must be a UUID" });
    }
    const dealId = parsed.data.deal_id;

    const tableOk = await hasTable(pool as any, "investor_insight_reports");
    if (!tableOk) {
      const NOT_STARTED_SUMMARY: StatusSummary = {
        analysis_status: "not_started",
        report_status: "not_started",
        has_existing_render_package: false,
        blocking_reason: null,
        last_activity_at: null,
        evidence_gate: null,
      };
      return reply.status(200).send({ status: "not_started", status_summary: NOT_STARTED_SUMMARY });
    }

    // Fetch both the report row AND the status_summary in parallel.
    const [{ rows }, statusSummary] = await Promise.all([
      pool.query<{
        status: string;
        engine_version: string;
        upstream_fingerprint: string;
        gate_state: unknown;
        compliance_state: unknown;
        render_package: unknown;
        narrative_contradiction_bundle: unknown;
        updated_at: string;
      }>(
        // PR36.9: also surface the contradiction bundle from report_payload so the UI
        // can show mixed-evidence states without returning the full payload.
        `SELECT status, engine_version, upstream_fingerprint, gate_state, compliance_state, render_package,
                report_payload->'narrative_contradiction_bundle' AS narrative_contradiction_bundle,
                updated_at
           FROM investor_insight_reports
          WHERE deal_id = $1
          ORDER BY updated_at DESC
          LIMIT 1`,
        [dealId]
      ),
      buildStatusSummary(pool, dealId),
    ]);

    if (rows.length === 0) {
      return reply.status(200).send({ status: "not_started", status_summary: statusSummary });
    }

    const row = rows[0];
    return reply.status(200).send({
      status: row.status,
      engine_version: row.engine_version,
      upstream_fingerprint: row.upstream_fingerprint,
      gate_state: row.gate_state,
      compliance_state: row.compliance_state,
      render_package: row.render_package,
      // PR36.9: contradiction bundle for UI mixed-signal display (null when absent).
      ...(row.narrative_contradiction_bundle != null && {
        narrative_contradiction_bundle: row.narrative_contradiction_bundle,
      }),
      updated_at: row.updated_at,
      status_summary: statusSummary,
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // GET /api/v1/deals/:deal_id/orchestrator-report
  // Read-only. Computes the deterministic OrchestratorReportV1 on-the-fly from
  // the most recent investor_insight_reports render_package. No DB writes.
  // ─────────────────────────────────────────────────────────────────────────
  app.get("/api/v1/deals/:deal_id/orchestrator-report", async (request, reply) => {
    const rawDealId = (request.params as { deal_id: string }).deal_id;
    const parsed = z.object({ deal_id: z.string().uuid() }).safeParse({ deal_id: rawDealId });
    if (!parsed.success) {
      return reply.status(400).send({ error: "invalid_deal_id" });
    }
    const dealId = parsed.data.deal_id;

    const tableOk = await hasTable(pool as any, "investor_insight_reports");
    if (!tableOk) {
      return reply.status(404).send({ error: "not_found" });
    }

    const { rows } = await pool.query<{
      render_package: unknown;
      upstream_fingerprint: string;
      schema_version?: string;
      status: string;
    }>(
      `SELECT status, render_package, upstream_fingerprint
       FROM investor_insight_reports
       WHERE deal_id = $1
       ORDER BY updated_at DESC
       LIMIT 1`,
      [dealId]
    );

    if (rows.length === 0) {
      return reply.status(404).send({ error: "not_found" });
    }

    const rp = rows[0].render_package as any;
    if (!rp || !Array.isArray(rp.sections)) {
      return reply.status(404).send({ error: "not_found" });
    }

    try {
      const report = buildOrchestratorReportV1({ dealId, renderPackage: rp });
      return reply.status(200).send({ schema_version: "ddai_orchestrator_report_v1", report });
    } catch (err) {
      return reply.status(500).send({
        error: "build_failed",
        message: err instanceof Error ? err.message : String(err),
      });
    }
  });

  if (debugRoutesEnabled) {
    app.get<{ Params: { dealId: string } }>(
      "/api/v1/debug/deals/:dealId/phaseb",
      {
        schema: {
          tags: ["debug"],
          params: {
            type: "object",
            properties: { dealId: { type: "string" } },
            required: ["dealId"],
          },
        } as any,
      },
      async (request, reply) => {
        const parsed = z.string().uuid().safeParse(request.params.dealId);
        if (!parsed.success) {
          return reply.status(400).send({ error: "dealId must be a valid UUID" });
        }

        const dealId = parsed.data;

        let dealRow: { id: string; name: string } | null = null;
        let dealExists = false;

        try {
          const { rows } = await pool.query<{ id: string; name: string }>(
            `SELECT id, name FROM deals WHERE id = $1 AND deleted_at IS NULL LIMIT 1`,
            [dealId]
          );
          if (rows?.[0]) {
            dealRow = rows[0];
            dealExists = true;
          }
        } catch {
          // keep dealRow null
        }

        let latestRun: any = null;
        let runHistory: any[] = [];
        const hasPhaseBTable = await hasTable(pool, "public.deal_phase_b_runs");
        if (hasPhaseBTable) {
          try {
            const { rows } = await pool.query(
              `SELECT id, deal_id, version, created_at, source_run_id, phase_b_features, phase_b_result
                 FROM deal_phase_b_runs
                WHERE deal_id = $1
                ORDER BY created_at DESC NULLS LAST, version DESC, id DESC
                LIMIT 3`,
              [dealId]
            );
            runHistory = rows ?? [];
            latestRun = runHistory[0] ?? null;
          } catch {
            latestRun = null;
            runHistory = [];
          }
        }

        let db_identity = {
          current_database: null as string | null,
          inet_server_addr: null as string | null,
          inet_server_port: null as number | null,
          current_user: null as string | null,
        };
        try {
          const dbIdentityResult = await pool.query<{
            current_database: string | null;
            inet_server_addr: string | null;
            inet_server_port: number | null;
            current_user: string | null;
          }>(
            `SELECT current_database(), inet_server_addr(), inet_server_port(), current_user`
          );
          db_identity = dbIdentityResult?.rows?.[0] ?? db_identity;
        } catch {
          // keep nulls
        }

        let visuals_sanity: {
          visuals_count: number | null;
          evidence_count: number | null;
          visuals_count_db?: number | null;
          visuals_with_structured?: number | null;
          visuals_with_ocr?: number | null;
          ocr_chars_total?: number | null;
          visuals_source?: string | null;
          ocr_hint?: string | null;
        } | null = null;

        try {
          const summary = await fetchPhaseBVisualsFromDb(pool as any, dealId);
          if (summary) {
            const ocrHint = !summary.ocr_text_available
              ? "OCR text not stored; install/enable OCR to populate"
              : summary.ocr_quality_counts && summary.ocr_quality_counts.pytesseract_missing > 0
                ? "OCR missing for some visuals (pytesseract_missing flagged)"
                : null;

            visuals_sanity = {
              visuals_count: summary.visuals_count,
              evidence_count: summary.evidence_count,
              visuals_count_db: summary.visuals_count,
              visuals_with_structured: summary.visuals_with_structured,
              visuals_with_ocr: summary.visuals_with_ocr,
              ocr_chars_total: summary.ocr_chars_total,
              visuals_source: summary.source,
              ocr_hint: ocrHint,
            };
          }
        } catch {
          visuals_sanity = null;
        }

        app.log.info(
          {
            event: "debug_phaseb",
            deal_id: dealId,
            deal_exists: dealExists,
            has_latest_run: Boolean(latestRun),
          },
          "debug phaseb endpoint"
        );

        return reply.send({
          requested_deal_id: dealId,
          deal_exists: dealExists,
          deal: dealRow,
          db_identity,
          phase_b: {
            latest_run: latestRun,
            history: runHistory,
          },
          visuals_sanity,
        });
      }
    );

    // ── GET /api/v1/debug/deals/:dealId/intelligence ─────────────────────────
    // Internal-only. Returns the most recent Stage 5 intelligence output for a
    // deal: confidence assessment and challenge pass result.
    //
    // Gated behind debugRoutesEnabled — never exposed to end users.
    // Memory influence is a secondary signal; it does not change ORS or
    // overwrite verdicts.
    app.get<{ Params: { dealId: string } }>(
      "/api/v1/debug/deals/:dealId/intelligence",
      {
        schema: {
          tags: ["debug"],
          params: {
            type: "object",
            properties: { dealId: { type: "string" } },
            required: ["dealId"],
          },
        } as any,
      },
      async (request, reply) => {
        const parsed = z.string().uuid().safeParse(request.params.dealId);
        if (!parsed.success) {
          return reply.status(400).send({ error: "dealId must be a valid UUID" });
        }
        const dealId = parsed.data;

        const hasConfidenceTable = await hasTable(pool, "deal_confidence_assessments");
        const hasChallengeTable = await hasTable(pool, "deal_challenge_pass_results");

        let confidence: Record<string, unknown> | null = null;
        let challenge: Record<string, unknown> | null = null;

        if (hasConfidenceTable) {
          try {
            const { rows } = await pool.query<Record<string, unknown>>(
              `SELECT
                 intelligence_run_id,
                 overall_confidence_score,
                 overall_confidence_band,
                 memory_adjustment,
                 memory_adjustment_reason,
                 jsonb_array_length(penalties_applied) AS penalty_count,
                 (SELECT COALESCE(SUM((item->>'penalty')::int), 0)
                  FROM jsonb_array_elements(penalties_applied) item) AS total_penalty,
                 penalties_applied,
                 created_at
               FROM deal_confidence_assessments
               WHERE deal_id = $1
               ORDER BY created_at DESC
               LIMIT 1`,
              [dealId]
            );
            confidence = rows[0] ?? null;
          } catch {
            confidence = null;
          }
        }

        if (hasChallengeTable && confidence?.intelligence_run_id) {
          try {
            const { rows } = await pool.query<Record<string, unknown>>(
              `SELECT
                 intelligence_run_id,
                 verdict_resistance_score,
                 verdict_resistance_label,
                 flag_count_critical,
                 flag_count_error,
                 flag_count_warn,
                 jsonb_array_length(missing_evidence) AS missing_evidence_count,
                 jsonb_array_length(diligence_gaps) AS diligence_gaps_count,
                 memory_challenge_used,
                 memory_challenge_summary,
                 primary_challenge_reason,
                 challenge_factors,
                 created_at
               FROM deal_challenge_pass_results
               WHERE intelligence_run_id = $1
               LIMIT 1`,
              [confidence.intelligence_run_id]
            );
            challenge = rows[0] ?? null;
          } catch {
            challenge = null;
          }
        }

        // Pull memory influence snapshot from deal_memory_snapshots.
        // Created by Stage 5 after deriveMemoryInfluence() so reviewers can
        // see WHY memory did or did not adjust confidence for this run.
        const hasMemorySnapshotTable = await hasTable(pool as any, "deal_memory_snapshots");

        let memory: Record<string, unknown> | null = null;
        if (hasMemorySnapshotTable && confidence?.intelligence_run_id) {
          try {
            const { rows } = await pool.query<Record<string, unknown>>(
              `SELECT
                 similar_deal_count,
                 avg_similarity_pct,
                 memory_support_signal,
                 memory_fragility_signal,
                 verdict_agreement_fraction,
                 confidence_adjustment,
                 neighbor_snapshots
               FROM deal_memory_snapshots
               WHERE intelligence_run_id = $1
               LIMIT 1`,
              [confidence.intelligence_run_id]
            );
            memory = rows[0] ?? null;
          } catch {
            memory = null;
          }
        }

        return reply.send({
          deal_id: dealId,
          run_id: confidence?.intelligence_run_id ?? null,
          confidence,
          challenge,
          memory,
          _meta: {
            has_confidence_table: hasConfidenceTable,
            has_challenge_table: hasChallengeTable,
            has_memory_snapshot_table: hasMemorySnapshotTable,
          },
        });
      }
    );
  }
}
