/**
 * llm-interpretation-v1.ts
 *
 * LLM Interpretation Layer — PR36 (upgraded from PR34.3)
 *
 * Generates a structured investor memo from deterministic pipeline outputs:
 * posture, confidence, executive summary, product differentiation,
 * go-to-market strategy, financial outlook, business quality, market position,
 * capital interpretation, strengths, risks, key unknowns, and next questions.
 *
 * Design contract:
 *  - The LLM may ONLY restate, summarize, or rephrase values already
 *    present in the canonical input corpus.
 *  - It MUST NOT introduce any numbers, dollar amounts, percentages, or
 *    year values that do not appear verbatim (after normalization) in the
 *    canonical input text.
 *  - Posture (GO | INVESTIGATE | CAUTION | PASS) and confidence (HIGH | MEDIUM | LOW)
 *    are generated by the LLM from the corpus; validated output is persisted in
 *    the render_package section body.
 *  - When evidence gate failed, evidence_caveat is set so the UI can warn the
 *    reader that coverage was limited at time of interpretation.
 */

import {
	OpenAIGPT4oProvider,
} from "../../lib/llm/providers/openai-provider";
import type { ProviderConfig } from "../../lib/llm/types";
import {
	validateNoNewNumbers,
	normalizeLlmFinanceShorthand,
} from "./governed-summary-v1";

// ─── Types ────────────────────────────────────────────────────────────────────

/**
 * Investment posture:
 *  - GO:          Multiple supporting signals; compelling fundamentals
 *  - INVESTIGATE: Interesting but requires diligence; gaps or risks present
 *  - CAUTION:     Notable red flags or significant data gaps
 *  - PASS:        Clear negatives, missing fundamentals, or fatal flaws
 */
export type LlmInterpretationPosture = "GO" | "INVESTIGATE" | "CAUTION" | "PASS";

/**
 * Confidence in the posture classification:
 *  - HIGH:   ≥2 cross-validated signals with no major gaps
 *  - MEDIUM: Some signals present but gaps remain
 *  - LOW:    Sparse data, major contradictions, or heavy reliance on incomplete evidence
 */
export type LlmInterpretationConfidence = "HIGH" | "MEDIUM" | "LOW";

/** All valid posture values for exhaustive validation checks. */
export const POSTURE_VALUES: ReadonlySet<string> = new Set<LlmInterpretationPosture>([
	"GO",
	"INVESTIGATE",
	"CAUTION",
	"PASS",
]);

/** All valid confidence values for exhaustive validation checks. */
export const CONFIDENCE_VALUES: ReadonlySet<string> = new Set<LlmInterpretationConfidence>([
	"HIGH",
	"MEDIUM",
	"LOW",
]);

export interface LlmInterpretationV1 {
	schema_version: "llm_interpretation_v1";
	/** Investment posture classification: GO | INVESTIGATE | CAUTION | PASS */
	posture: LlmInterpretationPosture;
	/** Confidence level: HIGH | MEDIUM | LOW */
	confidence: LlmInterpretationConfidence;
	/** 2–4 sentence executive interpretation of the investment opportunity. */
	executive_summary: string;
	/** Up to 3 key strengths grounded in extracted evidence. Each ≤150 chars. */
	strengths: string[];
	/** Up to 3 key risks or concerns. Each ≤150 chars. */
	risks: string[];
	/** Up to 3 targeted questions for the next investor-company interaction. Each ≤180 chars. */
	next_questions: string[];
	/**
	 * 1–3 sentences on the financial profile:
	 * revenue trajectory, growth rate, margins, burn, runway, stage-readiness.
	 * Use "Not disclosed" when financial data is absent.
	 */
	financial_outlook: string;
	/**
	 * 1–3 sentences on business quality:
	 * model defensibility, team signals, operational maturity, product-market fit evidence.
	 */
	business_quality: string;
	/**
	 * 1–3 sentences on market position:
	 * TAM/SAM/SOM claims, competitive positioning, and whether the sizing is credible.
	 */
	market_position: string;
	/**
	 * 1–3 sentences interpreting the raise:
	 * amount, structure / instrument, valuation, use of funds, and how they relate.
	 */
	capital_and_raise_interpretation: string;
	/**
	 * 1–3 sentences on product differentiation:
	 * what the company actually builds, what makes it potentially unique,
	 * and what extracted evidence supports that claim.
	 * Use "Not determinable from available signals" when product data is absent.
	 */
	product_differentiation: string;
	/**
	 * 1–3 sentences on go-to-market strategy:
	 * target buyer, pricing signals, distribution channels, and commercial model.
	 * Use "Not determinable from available signals" when GTM data is absent.
	 */
	go_to_market_strategy: string;
	/**
	 * PR36: 1–3 sentences on the external macro + sector environment:
	 * industry growth signals, macro tailwinds/headwinds, and sector competitiveness
	 * derived from external due diligence market research.
	 * Empty string when external diligence is unavailable.
	 */
	external_market_context: string;
	/**
	 * PR36: 1–3 sentences mapping the competitive landscape:
	 * comparable companies identified via web research, market structure,
	 * and whether the company's differentiation claims hold up externally.
	 * Empty string when external diligence is unavailable.
	 */
	competitive_landscape: string;
	/**
	 * PR36: 1–3 sentences on claim verification:
	 * classifies deck claims as supported / contradicted / mixed / insufficient evidence
	 * based on claim_corroborations from external due diligence.
	 * Empty string when external diligence is unavailable.
	 */
	claim_verification_summary: string;
	/**
	 * PR36: 1–3 sentences on externally-sourced risk signals:
	 * regulatory risks, reputation signals, sector instability, or negative news
	 * surfaced via external_risks and company_footprint buckets.
	 * Empty string when external diligence is unavailable.
	 */
	external_risk_signals: string;
	/**
	 * Up to 3 critical unknowns that must be answered before conviction is possible.
	 * Each ≤150 chars.
	 */
	key_unknowns: string[];
	/**
	 * When non-null, warns the reader that evidence coverage was limited at
	 * time of generation and the interpretation may be incomplete.
	 */
	evidence_caveat: string | null;
	/** True when numeric-parity validation passed. */
	validated: boolean;
}

export interface LlmInterpretationArgs {
	canonicalFieldsBody: string | null;
	insightSlotsBody: string | null;
	financialStmtBody: string | null;
	useOfFundsBody: string | null;
	conflictsBody: string | null;
	/** Derived financial health metrics (revenue, growth, margins, efficiency). */
	financialHealthBody: string | null;
	/** Deterministic financial reconciliation summary. */
	financialReconciliationBody: string | null;
	/** Deck-derived financial signal mentions (ARR, MRR, burn, revenue, pricing, unit econ). */
	deckFinancialSignalsBody: string | null;
	/**
	 * Deterministic product signal bundle: capability language, automation/AI mentions,
	 * workflow integrations, competitive slide text, and differentiation claims.
	 */
	productSignalsBundleBody: string | null;
	/**
	 * Deterministic GTM signal bundle: pricing structures, target customer/ICP descriptions,
	 * subscription tiers, distribution/partnership signals, GTM-related use-of-funds.
	 */
	gtmSignalsBundleBody: string | null;
	/**
	 * PR35: Serialised external due diligence body (from Tavily web research).
	 * LLM-safe — contains only sanitised snippets and claim corroborations.
	 * Null when Tavily is disabled or no results were found.
	 */
	externalDiligenceBody: string | null;
	dealName?: string;
	productNarrativeBody?: string | null;
	/**
	 * When true the LLM is instructed to include an evidence caveat in its
	 * output, and the caller passes through the coverage metrics for context.
	 */
	evidenceCaveat?: boolean;
}

export type LlmInterpretationResult =
	| { ok: true; value: LlmInterpretationV1 }
	| { ok: false; reason: string; unknownTokens?: string[] };

// ─── System prompt ─────────────────────────────────────────────────────────────

const SYSTEM_PROMPT_BASE = [
	"You are a senior investment analyst at an early-stage venture firm. Your task is to read structured,",
	"deterministically extracted data from a startup deal and produce a concise, specific investor memo.",
	"You are NOT summarizing a pitch deck — you are interpreting structured signals for a busy investor.",
	"When external due diligence data is provided, integrate it to enrich your interpretation with market,",
	"competitive, and verification signals while keeping internal evidence as the authoritative source.",
	"",
	"STRICT RULES — any violation will cause your output to be discarded:",
	"1. Use the EXACT company name from the Deal Identity section. NEVER use 'Startup Corp', 'the company', or any placeholder.",
	"2. Do NOT introduce any numbers, dollar amounts, percentages, or year values that are NOT present verbatim in the canonical data.",
	"   If a financial figure does not appear in the input, you MUST write 'Not disclosed' — do not estimate or infer.",
	"3. Be SPECIFIC: tie every claim to an extracted signal. If you say the company is strong in X, name the evidence.",
	"4. Avoid generic startup language ('innovative', 'disrupting', 'passionate team') unless tied to specific extracted evidence.",
	"5. Distinguish clearly between: (a) verified/extracted data, (b) signals that suggest something, (c) what is missing.",
	"6. Arrays (strengths, risks, next_questions, key_unknowns) must have AT MOST 3 items each.",
	"7. String fields must not exceed these lengths: strength/risk/unknown ≤150 chars, next_question ≤180 chars.",
	"   financial_outlook, business_quality, market_position, capital_and_raise_interpretation,",
	"   product_differentiation, go_to_market_strategy: 1–3 sentences each.",
	"   executive_summary: 2–4 sentences.",
	"8. posture must be exactly one of: GO | INVESTIGATE | CAUTION | PASS",
	"   GO:          Compelling signals across multiple dimensions with minimal critical gaps",
	"   INVESTIGATE: Interesting but material gaps or risks require active diligence",
	"   CAUTION:     Notable red flags, significant contradictions, or sparse evidence",
	"   PASS:        Clear negatives, missing fundamentals, or fatal flaws dominate",
	"9. confidence must be exactly one of: HIGH | MEDIUM | LOW",
	"   HIGH:   ≥2 cross-validated signals covering raise, market, and financials with minimal gaps",
	"   MEDIUM: Some signals present but gaps remain that could shift the posture",
	"   LOW:    Sparse data, major contradictions, or single-source evidence only",
	"10. For each field, answer the investor's key question and guidance:",
	"   executive_summary — What is this deal and why does it matter (or not)? Be specific to the extracted signals.",
	"   product_differentiation — What does the company actually build? What makes it potentially unique or defensible?",
	"     Reference specific product signals (capabilities, automation claims, integration mentions, workflow descriptions).",
	"     If differentiation is unclear from the signals, explicitly say: 'Not determinable from available signals.'",
	"     Do NOT write 'AI platform' or 'innovative solution' without tying it to something specific from the data.",
	"   go_to_market_strategy — Who is the target buyer? How is the product sold? What pricing signals exist?",
	"     Reference extracted GTM signals (pricing tiers, ICP descriptions, distribution channels, partnership signals,",
	"     or sales-related use-of-funds allocations). If no GTM signals: 'Not determinable from available signals.'",
	"   financial_outlook — What does the financial data tell us? Revenue stage, growth, margins, runway, burn? If none: 'Not disclosed.'",
	"   business_quality — How strong is the business model, team signal, product-market fit, or defensibility based on the data?",
	"   market_position  — Is the TAM/SAM/SOM credible? What competitive dynamics are visible? If none: 'Not disclosed.'",
	"   capital_and_raise_interpretation — What is the raise, at what terms/structure, and how does the use of funds align?",
	"   strengths        — Structural strengths or most defensible signals. Must NOT duplicate risks or key_unknowns.",
	"   risks            — Structural weaknesses or negative signals. Must NOT duplicate key_unknowns or next_questions.",
	"   key_unknowns     — Missing information required to properly evaluate the business (gaps, not risks). Must NOT duplicate risks.",
	"   next_questions   — Top diligence questions investors should ask in the next meeting. These are action items, not restatements of unknowns.",
	"11. Section non-duplication rule: strengths, risks, key_unknowns, and next_questions must each contain DISTINCT content.",
	"    A risk is a known negative. An unknown is an information gap. A next_question is a concrete ask. Do not repeat the same concept across these arrays.",
	"12. External Due Diligence integration (if 'External Due Diligence' section is present):",
	"    - Internal document evidence is AUTHORITATIVE. External signals provide corroboration or context only.",
	"    - The LLM must NEVER override canonical field values with external data.",
	"    - Numbers from the external section may appear ONLY if they appeared verbatim in that section.",
	"    Populate the four external intelligence fields as follows:",
	"    - external_market_context: Use market_outlook and financial_context buckets to summarize industry growth,",
	"      macro tailwinds/headwinds, and sector competitiveness signals. 1–3 sentences. Use '' (empty string) if those buckets are absent or empty.",
	"    - competitive_landscape: Use the competitors bucket to name comparable companies, characterize market structure,",
	"      and evaluate whether the deck's differentiation claims hold up against external findings. 1–3 sentences. Use '' if that bucket is absent or empty.",
	"    - claim_verification_summary: Use claim_corroborations to classify deck claims as:",
	"      'supported' (external evidence aligns), 'contradicted' (external evidence conflicts),",
	"      'mixed' (partial alignment), or 'insufficient evidence' (no external signal found).",
	"      Describe what was corroborated and what was not. 1–3 sentences. Use '' if no corroborations exist.",
	"    - external_risk_signals: Use external_risks and public market data to surface regulatory risks,",
	"      reputation signals, sector instability, or concerning news. 1–3 sentences. Use '' if that bucket is absent or empty.",
	"    CRITICAL: For all four external fields, when the relevant bucket data is absent, empty, or not useful,",
	"    output EXACTLY '' (empty string). NEVER write 'Not disclosed.' for these four fields — use empty string only.",
	"    If external diligence is absent from the input, set all four fields to empty string ''.",
	"13. Return ONLY valid JSON with exactly these keys (no markdown, no code fences, no extra text):",
	'    { "posture": "...", "confidence": "...", "executive_summary": "...",',
	'      "product_differentiation": "...", "go_to_market_strategy": "...",',
	'      "financial_outlook": "...", "business_quality": "...", "market_position": "...",',
	'      "capital_and_raise_interpretation": "...",',
	'      "external_market_context": "...", "competitive_landscape": "...",',
	'      "claim_verification_summary": "...", "external_risk_signals": "...",',
	'      "strengths": [...], "risks": [...], "key_unknowns": [...], "next_questions": [...] }',
	"14. CONFIDENCE METADATA (PR36.6): Each canonical field may carry a confidence= annotation.",
	"    - confidence=WEAK_EVIDENCE: Do NOT restate this value as a definitive fact.",
	"      Use qualifying language, e.g.: 'limited signals suggest...' or 'with limited evidence...'.",
	"    - confidence=CONFLICTING: Do NOT include this field's value. Omit it or note 'conflicting signals present'.",
	"    - confidence=PROVISIONAL: Treat as supporting context only — not a primary fact.",
	"    - confidence=VERIFIED or confidence=STRONG_EVIDENCE: use normally.",
	"    - confidence=SUPPRESSED or confidence=UNKNOWN: ignore this field entirely.",
].join("\n");

const SYSTEM_PROMPT_WITH_CAVEAT =
	SYSTEM_PROMPT_BASE +
	"\n\n15. IMPORTANT: Evidence coverage is limited for this deal. Your interpretation is based on partial data." +
	" Set confidence to LOW unless there are multiple strong cross-validated signals. Explicitly call out where" +
	" key data was missing in the relevant section (e.g., financial_outlook, market_position, product_differentiation)."; 

// ─── LLM caller ───────────────────────────────────────────────────────────────

/**
 * Call gpt-4o-mini to generate an investment interpretation from canonical inputs.
 * Validates output has no hallucinated numbers before returning.
 */
export async function generateLlmInterpretationV1(
	args: LlmInterpretationArgs
): Promise<LlmInterpretationResult> {
	// Build canonical corpus for validation and LLM context.
	// Ordering is deliberate: identity first, then business context, then financials,
	// then evidence quality markers.
	const parts: string[] = [];
	if (args.dealName) parts.push(`## Deal Identity\nDeal name: ${args.dealName}`);
	if (args.productNarrativeBody) parts.push(`## Product Narrative\n${args.productNarrativeBody}`);
	if (args.canonicalFieldsBody) parts.push(`## Canonical Fields\n${args.canonicalFieldsBody}`);
	if (args.insightSlotsBody) parts.push(`## Insight Slots (Raise / Market / Traction / Valuation / Use-of-Funds)\n${args.insightSlotsBody}`);
	if (args.financialHealthBody) parts.push(`## Financial Health Metrics\n${args.financialHealthBody}`);
	if (args.financialStmtBody) parts.push(`## Financial Statement (XLSX)\n${args.financialStmtBody}`);
	if (args.financialReconciliationBody) parts.push(`## Financial Reconciliation\n${args.financialReconciliationBody}`);
	if (args.deckFinancialSignalsBody) parts.push(`## Deck Financial Signals (PDF/PPT)\n${args.deckFinancialSignalsBody}`);
	if (args.productSignalsBundleBody) parts.push(`## Product & Differentiation Signals\n${args.productSignalsBundleBody}`);
	if (args.gtmSignalsBundleBody) parts.push(`## Go-To-Market Signals\n${args.gtmSignalsBundleBody}`);
	if (args.useOfFundsBody) parts.push(`## Use of Funds Detail\n${args.useOfFundsBody}`);
	if (args.conflictsBody) parts.push(`## Conflicting Fields (detected)\n${args.conflictsBody}`);
	if (args.externalDiligenceBody) parts.push(`## External Due Diligence (web research)\n${args.externalDiligenceBody}`);

	if (parts.length === 0) {
		return { ok: false, reason: "no_canonical_data" };
	}

	const canonicalCorpus = parts.join("\n\n");

	const apiKey = process.env.OPENAI_API_KEY;
	if (!apiKey) {
		return { ok: false, reason: "missing_openai_api_key" };
	}

	const providerConfig: ProviderConfig = {
		type: "openai",
		enabled: true,
		priority: 1,
		apiKey,
		timeout: 30_000,
		retries: 2,
	};

	const provider = new OpenAIGPT4oProvider(providerConfig);
	const systemPrompt = args.evidenceCaveat ? SYSTEM_PROMPT_WITH_CAVEAT : SYSTEM_PROMPT_BASE;

	let response: Awaited<ReturnType<typeof provider.complete>>;
	try {
		response = await provider.complete({
			task: "synthesis",
			model: "gpt-4o-mini" as never,
			temperature: 0,
		max_tokens: 2200,
			messages: [
				{ role: "system", content: systemPrompt },
				{ role: "user", content: canonicalCorpus },
			],
			metadata: { kind: "llm_interpretation_v1" },
		});
	} catch {
		return { ok: false, reason: "llm_call_failed" };
	}

	if (!response?.content) {
		return { ok: false, reason: "llm_empty_response" };
	}

	// Parse JSON output
	let parsed: unknown;
	try {
		parsed = JSON.parse(response.content.trim());
	} catch {
		const jsonMatch = /\{[\s\S]*\}/.exec(response.content);
		if (!jsonMatch) {
			return { ok: false, reason: "llm_output_not_json" };
		}
		try {
			parsed = JSON.parse(jsonMatch[0]);
		} catch {
			return { ok: false, reason: "llm_output_not_json" };
		}
	}

	if (
		!parsed ||
		typeof parsed !== "object" ||
		Array.isArray(parsed)
	) {
		return { ok: false, reason: "llm_output_schema_mismatch" };
	}

	const raw = parsed as Record<string, unknown>;

	// Validate posture
	if (typeof raw["posture"] !== "string" || !POSTURE_VALUES.has(raw["posture"])) {
		return { ok: false, reason: "llm_output_invalid_posture" };
	}

	// Validate confidence
	if (typeof raw["confidence"] !== "string" || !CONFIDENCE_VALUES.has(raw["confidence"])) {
		return { ok: false, reason: "llm_output_invalid_confidence" };
	}
	const confidence = raw["confidence"] as LlmInterpretationConfidence;

	// Validate required string fields
	const requiredStrings = [
		"executive_summary",
		"product_differentiation",
		"go_to_market_strategy",
		"financial_outlook",
		"business_quality",
		"market_position",
		"capital_and_raise_interpretation",
	];
	for (const field of requiredStrings) {
		if (typeof raw[field] !== "string") {
			return { ok: false, reason: "llm_output_schema_mismatch" };
		}
	}
	// PR36: external intelligence fields — optional, default to empty string
	const external_market_context = typeof raw["external_market_context"] === "string"
		? (raw["external_market_context"] as string).trim() : "";
	const competitive_landscape = typeof raw["competitive_landscape"] === "string"
		? (raw["competitive_landscape"] as string).trim() : "";
	const claim_verification_summary = typeof raw["claim_verification_summary"] === "string"
		? (raw["claim_verification_summary"] as string).trim() : "";
	const external_risk_signals = typeof raw["external_risk_signals"] === "string"
		? (raw["external_risk_signals"] as string).trim() : "";
	if (
		!Array.isArray(raw["strengths"]) ||
		!Array.isArray(raw["risks"]) ||
		!Array.isArray(raw["next_questions"]) ||
		!Array.isArray(raw["key_unknowns"])
	) {
		return { ok: false, reason: "llm_output_schema_mismatch" };
	}

	const toStringArray = (arr: unknown[], maxItems: number, maxChars: number): string[] =>
		arr
			.filter((x): x is string => typeof x === "string" && x.trim().length > 0)
			.slice(0, maxItems)
			.map((s) => s.trim().slice(0, maxChars));

	const executive_summary = (raw["executive_summary"] as string).trim();
	const product_differentiation = (raw["product_differentiation"] as string).trim();
	const go_to_market_strategy = (raw["go_to_market_strategy"] as string).trim();
	const financial_outlook = (raw["financial_outlook"] as string).trim();
	const business_quality = (raw["business_quality"] as string).trim();
	const market_position = (raw["market_position"] as string).trim();
	const capital_and_raise_interpretation = (raw["capital_and_raise_interpretation"] as string).trim();
	const strengths = toStringArray(raw["strengths"] as unknown[], 3, 150);
	const risks = toStringArray(raw["risks"] as unknown[], 3, 150);
	const next_questions = toStringArray(raw["next_questions"] as unknown[], 3, 180);
	const key_unknowns = toStringArray(raw["key_unknowns"] as unknown[], 3, 150);

	// Numeric-parity validation — covers ALL text fields including PR36 external fields
	const allOutputText = [
		executive_summary,
		product_differentiation,
		go_to_market_strategy,
		financial_outlook,
		business_quality,
		market_position,
		capital_and_raise_interpretation,
		external_market_context,
		competitive_landscape,
		claim_verification_summary,
		external_risk_signals,
		...strengths,
		...risks,
		...next_questions,
		...key_unknowns,
	].join(" ");
	const fullOutput = normalizeLlmFinanceShorthand(allOutputText);
	const { ok: parityOk, unknown: unknownTokens } = validateNoNewNumbers(fullOutput, canonicalCorpus);

	if (!parityOk) {
		return { ok: false, reason: "numeric_parity_failed", unknownTokens };
	}

	const evidenceCaveat: string | null = args.evidenceCaveat
		? "Limited coverage — interpretation may be incomplete"
		: null;

	return {
		ok: true,
		value: {
			schema_version: "llm_interpretation_v1",
			posture: raw["posture"] as LlmInterpretationPosture,
			confidence,
			executive_summary,
			product_differentiation,
			go_to_market_strategy,
			financial_outlook,
			business_quality,
			market_position,
			capital_and_raise_interpretation,
			external_market_context,
			competitive_landscape,
			claim_verification_summary,
			external_risk_signals,
			strengths,
			risks,
			next_questions,
			key_unknowns,
			evidence_caveat: evidenceCaveat,
			validated: true,
		},
	};
}

// ─── Section body serializer ──────────────────────────────────────────────────

/**
 * Serialize a LlmInterpretationV1 to a human-readable body string suitable for
 * the render_package section body field.
 *
 * The JSON representation is embedded under a delimiter so that the UI can
 * parse structured data without a separate field.
 */
export function serializeLlmInterpretationBody(value: LlmInterpretationV1): string {
	const lines: string[] = [];

	// Posture + confidence header
	lines.push(`Investment Posture: ${value.posture} | Confidence: ${value.confidence}`);

	if (value.evidence_caveat) {
		lines.push(`⚠ ${value.evidence_caveat}`);
	}
	lines.push("");

	lines.push("Executive Summary");
	lines.push(value.executive_summary);
	lines.push("");

	lines.push("Financial Outlook");
	lines.push(value.financial_outlook);
	lines.push("");

	lines.push("Business Quality");
	lines.push(value.business_quality);
	lines.push("");

	lines.push("Market Position");
	lines.push(value.market_position);
	lines.push("");

	lines.push("Capital & Raise");
	lines.push(value.capital_and_raise_interpretation);
	lines.push("");

	lines.push("Product & Differentiation");
	lines.push(value.product_differentiation);
	lines.push("");

	lines.push("Go-To-Market Strategy");
	lines.push(value.go_to_market_strategy);
	lines.push("");

	if (value.external_market_context) {
		lines.push("External Market Context");
		lines.push(value.external_market_context);
		lines.push("");
	}

	if (value.competitive_landscape) {
		lines.push("Competitive Landscape");
		lines.push(value.competitive_landscape);
		lines.push("");
	}

	if (value.claim_verification_summary) {
		lines.push("Claim Verification");
		lines.push(value.claim_verification_summary);
		lines.push("");
	}

	if (value.external_risk_signals) {
		lines.push("External Risk Signals");
		lines.push(value.external_risk_signals);
		lines.push("");
	}

	if (value.strengths.length > 0) {
		lines.push("Strengths");
		value.strengths.forEach((s) => lines.push(`• ${s}`));
		lines.push("");
	}

	if (value.risks.length > 0) {
		lines.push("Risks");
		value.risks.forEach((r) => lines.push(`• ${r}`));
		lines.push("");
	}

	if (value.next_questions.length > 0) {
		lines.push("Next Questions");
		value.next_questions.forEach((q) => lines.push(`• ${q}`));
		lines.push("");
	}

	if (value.key_unknowns.length > 0) {
		lines.push("Key Unknowns");
		value.key_unknowns.forEach((u) => lines.push(`• ${u}`));
		lines.push("");
	}

	// Embed structured JSON for UI parsing
	lines.push(`---llm_interpretation_v1_json---`);
	lines.push(JSON.stringify(value));

	return lines.join("\n");
}

/**
 * Parse a LlmInterpretationV1 from a section body string previously created
 * by serializeLlmInterpretationBody. Returns null on parse failure.
 */
export function parseLlmInterpretationBody(body: string): LlmInterpretationV1 | null {
	const delimiter = "---llm_interpretation_v1_json---\n";
	const idx = body.indexOf(delimiter);
	if (idx === -1) return null;
	try {
		const json = body.slice(idx + delimiter.length).trim();
		const parsed = JSON.parse(json) as LlmInterpretationV1;
		if (parsed?.schema_version !== "llm_interpretation_v1") return null;
		return parsed;
	} catch {
		return null;
	}
}
