import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { getPool } from "../lib/db";
import { enqueueJob } from "../services/jobs";

type PoolLike = {
  query: <T = any>(sql: string, params?: unknown[]) => Promise<{ rows: T[] }>;
};

async function hasTable(pool: PoolLike, table: string): Promise<boolean> {
  try {
    const { rows } = await pool.query<{ oid: string | null }>("SELECT to_regclass($1) as oid", [table]);
    return rows?.[0]?.oid !== null;
  } catch {
    return false;
  }
}

async function hasColumn(pool: PoolLike, table: string, column: string): Promise<boolean> {
  try {
    const { rows } = await pool.query<{ ok: number }>(
      `SELECT 1 as ok FROM information_schema.columns WHERE table_name = $1 AND column_name = $2 LIMIT 1`,
      [table, column]
    );
    return Array.isArray(rows) && rows.length > 0;
  } catch {
    return false;
  }
}

async function getColumnDataType(pool: PoolLike, table: string, column: string): Promise<string | null> {
  try {
    const { rows } = await pool.query<{ data_type: string }>(
      `SELECT data_type
         FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = $1
          AND column_name = $2
        LIMIT 1`,
      [table, column]
    );
    return rows?.[0]?.data_type ?? null;
  } catch {
    return null;
  }
}

function isUuid(value: string): boolean {
  return z.string().uuid().safeParse(value).success;
}

// Parse synthetic citation strings generated by the conviction builder.
// Formats: "doc:<uuid>:page:<n>", "doc:<uuid>:page_index:<n>", "doc:<uuid>", "<bare-uuid>"
type ParsedRef =
  | { kind: "doc_page"; document_id: string; page: number; raw: string }
  | { kind: "doc_page_index"; document_id: string; page_index: number; raw: string }
  | { kind: "doc_only"; document_id: string; raw: string }
  | { kind: "uuid"; id: string; raw: string }
  | { kind: "opaque"; raw: string };

function parseRef(id: string): ParsedRef {
  // "doc:<uuid>:page:<n>"
  const docPageMatch = id.match(/^doc:([0-9a-f-]{36}):page:(\d+)$/i);
  if (docPageMatch && isUuid(docPageMatch[1])) {
    return { kind: "doc_page", document_id: docPageMatch[1], page: parseInt(docPageMatch[2], 10), raw: id };
  }
  // "doc:<uuid>:page_index:<n>"
  const docPageIndexMatch = id.match(/^doc:([0-9a-f-]{36}):page_index:(\d+)$/i);
  if (docPageIndexMatch && isUuid(docPageIndexMatch[1])) {
    return { kind: "doc_page_index", document_id: docPageIndexMatch[1], page_index: parseInt(docPageIndexMatch[2], 10), raw: id };
  }
  // "doc:<uuid>" (no page)
  const docOnlyMatch = id.match(/^doc:([0-9a-f-]{36})$/i);
  if (docOnlyMatch && isUuid(docOnlyMatch[1])) {
    return { kind: "doc_only", document_id: docOnlyMatch[1], raw: id };
  }
  // bare UUID
  if (isUuid(id)) {
    return { kind: "uuid", id, raw: id };
  }
  return { kind: "opaque", raw: id };
}

const fetchSchema = z.object({
  deal_id: z.string().min(1),
  filter: z.string().optional(),
});

const resolveSchema = z.object({
  ids: z.string().min(1),
});

const dealIdSchema = z.string().min(1);

export async function registerEvidenceRoutes(app: FastifyInstance, pool = getPool(), enqueue = enqueueJob) {
  app.post("/api/v1/evidence/fetch", async (request, reply) => {
    const parsed = fetchSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }

    const { deal_id, filter } = parsed.data;
    const { rows: deals } = await pool.query(`SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL`, [deal_id]);
    if (deals.length === 0) {
      return reply.status(404).send({ error: "Deal not found" });
    }

    try {
      const job = await enqueue({ deal_id, type: "fetch_evidence", payload: filter ? { filter } : {} });
      return reply.status(202).send({ job_id: job.job_id, status: job.status });
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to queue evidence job";
      return reply.status(500).send({ error: message });
    }
  });

  // Resolve evidence IDs to citations for UI trace mode.
  // Accepts comma-separated IDs: /api/v1/evidence/resolve?ids=a,b,c
  // Handles formats:
  //   "doc:<uuid>:page:<n>"        — synthetic citation from conviction builder
  //   "doc:<uuid>:page_index:<n>"  — same, using page_index
  //   "doc:<uuid>"                 — document reference without page
  //   "<bare-uuid>"                — evidence table row ID
  app.get("/api/v1/evidence/resolve", async (request, reply) => {
    const parsed = resolveSchema.safeParse(request.query);
    if (!parsed.success) {
      return reply.status(400).send({ error: "Invalid input", details: parsed.error.flatten() });
    }

    const ids = parsed.data.ids
      .split(",")
      .map((s) => s.trim())
      .filter((s) => s.length > 0);

    const uniqueIds = Array.from(new Set(ids)).slice(0, 100);
    if (uniqueIds.length === 0) {
      return reply.status(400).send({ error: "No ids provided" });
    }

    // Parse all incoming refs into typed buckets
    const parsedRefs = uniqueIds.map(parseRef);

    // Bucket 1: doc: format refs — resolve directly from documents table
    const docRefs = parsedRefs.filter(
      (r): r is Extract<ParsedRef, { kind: "doc_page" | "doc_page_index" | "doc_only" }> =>
        r.kind === "doc_page" || r.kind === "doc_page_index" || r.kind === "doc_only"
    );

    // Bucket 2: bare UUID refs — try evidence table, then evidence_items
    const uuidRefs = parsedRefs.filter((r): r is Extract<ParsedRef, { kind: "uuid" }> => r.kind === "uuid");

    // Bucket 3: opaque refs that cannot be resolved
    // (no query needed — return ok: false)

    type ResolvedRow = {
      id: string;
      ok: boolean;
      resolvable?: boolean;
      document_id?: string;
      document_title?: string;
      page?: number;
      snippet?: string;
    };

    const resultMap = new Map<string, ResolvedRow>();

    // --- Resolve doc: format refs from documents table ---
    const documentsTableExists = await hasTable(pool as unknown as PoolLike, "documents");
    if (documentsTableExists && docRefs.length > 0) {
      const docIds = Array.from(new Set(docRefs.map((r) => r.document_id)));
      try {
        type DocRow = { id: string; title: string | null };
        const { rows: docRows } = await pool.query<DocRow>(
          `SELECT id::text as id, title FROM documents WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL`,
          [docIds]
        );
        const docById = new Map<string, DocRow>();
        for (const row of docRows ?? []) {
          if (row?.id) docById.set(row.id, row);
        }
        for (const ref of docRefs) {
          const doc = docById.get(ref.document_id);
          const page =
            ref.kind === "doc_page" ? ref.page
            : ref.kind === "doc_page_index" ? ref.page_index
            : undefined;
          resultMap.set(ref.raw, {
            id: ref.raw,
            ok: doc != null,
            resolvable: doc != null,
            document_id: ref.document_id,
            document_title: doc?.title ?? undefined,
            page,
          });
        }
      } catch {
        for (const ref of docRefs) {
          resultMap.set(ref.raw, { id: ref.raw, ok: false });
        }
      }
    } else {
      for (const ref of docRefs) {
        resultMap.set(ref.raw, { id: ref.raw, ok: false });
      }
    }

    // --- Resolve bare UUID refs from evidence + evidence_items tables ---
    if (uuidRefs.length > 0) {
      const uuidIds = uuidRefs.map((r) => r.id);

      const evidenceTableExists = await hasTable(pool as unknown as PoolLike, "evidence");

      // Try evidence table first
      if (evidenceTableExists) {
        const [hasId, hasEvidenceId] = await Promise.all([
          hasColumn(pool as unknown as PoolLike, "evidence", "id"),
          hasColumn(pool as unknown as PoolLike, "evidence", "evidence_id"),
        ]);
        const evidenceIdColumn = hasId ? "id" : hasEvidenceId ? "evidence_id" : "id";
        const [hasDocumentId, hasPage, hasPageNumber, hasText, hasExcerpt] = await Promise.all([
          hasColumn(pool as unknown as PoolLike, "evidence", "document_id"),
          hasColumn(pool as unknown as PoolLike, "evidence", "page"),
          hasColumn(pool as unknown as PoolLike, "evidence", "page_number"),
          hasColumn(pool as unknown as PoolLike, "evidence", "text"),
          hasColumn(pool as unknown as PoolLike, "evidence", "excerpt"),
        ]);
        const evidenceIdType = await getColumnDataType(pool as unknown as PoolLike, "evidence", evidenceIdColumn);
        const evidenceDocumentIdType = hasDocumentId
          ? await getColumnDataType(pool as unknown as PoolLike, "evidence", "document_id")
          : null;
        const documentsIdType = documentsTableExists
          ? await getColumnDataType(pool as unknown as PoolLike, "documents", "id")
          : null;

        const evidenceIdExpr = `e.${evidenceIdColumn}`;
        const documentIdExpr = hasDocumentId ? "e.document_id" : "NULL::text AS document_id";
        const pageExpr = hasPage ? "e.page" : hasPageNumber ? "e.page_number" : "NULL::int AS page";
        const snippetExpr = hasExcerpt ? "e.excerpt" : hasText ? "e.text" : "NULL::text AS snippet";
        const documentTitleExpr =
          documentsTableExists && (await hasColumn(pool as unknown as PoolLike, "documents", "title"))
            ? "d.title"
            : "NULL::text AS document_title";
        const joinDocuments = (() => {
          if (!(documentsTableExists && hasDocumentId)) return "";
          if (documentsIdType === "uuid" || evidenceDocumentIdType === "uuid") {
            return "LEFT JOIN documents d ON d.id::text = e.document_id::text";
          }
          return "LEFT JOIN documents d ON d.id = e.document_id";
        })();

        const useUuidIds = evidenceIdType === "uuid";
        const queryIds = useUuidIds ? uuidIds.filter(isUuid) : uuidIds;

        type EvidRow = {
          id: string;
          document_id: string | null;
          page: number | null;
          snippet: string | null;
          document_title: string | null;
        };

        if (queryIds.length > 0) {
          try {
            const { rows: evidRows } = await pool.query<EvidRow>(
              `SELECT ${evidenceIdExpr} as id,
                      ${documentIdExpr},
                      ${pageExpr},
                      ${snippetExpr} as snippet,
                      ${documentTitleExpr}
                 FROM evidence e
                 ${joinDocuments}
                WHERE ${evidenceIdExpr} = ANY($1::${useUuidIds ? "uuid" : "text"}[])`,
              [queryIds]
            );
            for (const row of evidRows ?? []) {
              if (!row?.id) continue;
              const document_id = row.document_id ?? undefined;
              const document_title = row.document_title ?? undefined;
              const page = typeof row.page === "number" && Number.isFinite(row.page) ? row.page : row.page ?? undefined;
              const snippet = typeof row.snippet === "string" && row.snippet.trim().length > 0 ? row.snippet : undefined;
              resultMap.set(row.id, {
                id: row.id,
                ok: true,
                resolvable: Boolean(document_id),
                document_id,
                document_title,
                page,
                snippet,
              });
            }
          } catch {
            // fallthrough to evidence_items
          }
        }
      }

      // For any UUID refs still unresolved, try evidence_items table
      const unresolvedUuids = uuidRefs.filter((r) => !resultMap.has(r.raw));
      if (unresolvedUuids.length > 0) {
        const evidenceItemsExists = await hasTable(pool as unknown as PoolLike, "evidence_items");
        if (evidenceItemsExists) {
          try {
            type ItemRow = {
              evidence_id: string;
              source_document_id: string | null;
              content_text: string | null;
              doc_title: string | null;
            };
            const { rows: itemRows } = await pool.query<ItemRow>(
              `SELECT ei.evidence_id,
                      ei.source_document_id::text,
                      ei.content_text,
                      d.title as doc_title
                 FROM evidence_items ei
                 LEFT JOIN documents d ON d.id = ei.source_document_id
                WHERE ei.evidence_id = ANY($1::text[])`,
              [unresolvedUuids.map((r) => r.id)]
            );
            for (const row of itemRows ?? []) {
              if (!row?.evidence_id) continue;
              const document_id = row.source_document_id ?? undefined;
              const snippet =
                typeof row.content_text === "string" && row.content_text.trim().length > 0
                  ? row.content_text.slice(0, 280)
                  : undefined;
              resultMap.set(row.evidence_id, {
                id: row.evidence_id,
                ok: true,
                resolvable: Boolean(document_id),
                document_id,
                document_title: row.doc_title ?? undefined,
                snippet,
              });
            }
          } catch {
            // leave unresolved
          }
        }
      }

      // Mark any still-unresolved UUIDs as not found
      for (const ref of uuidRefs) {
        if (!resultMap.has(ref.raw)) {
          resultMap.set(ref.raw, { id: ref.raw, ok: false });
        }
      }
    }

    // Build final results in original order
    const results = uniqueIds.map((id) => resultMap.get(id) ?? { id, ok: false });

    return reply.status(200).send({ results });
  });

  app.get("/api/v1/deals/:deal_id/evidence", async (request) => {
    const startTs = Date.now();
    const dealParam = (request.params as { deal_id: string }).deal_id;
    const parsedDeal = dealIdSchema.safeParse(dealParam);
    if (!parsedDeal.success) {
      return { evidence: [] };
    }
    const dealId = parsedDeal.data;

    request.log.info({ msg: "deal.evidence.start", deal_id: dealId, start_ts: new Date(startTs).toISOString() });

    const { rows: deals } = await pool.query(`SELECT id FROM deals WHERE id = $1 AND deleted_at IS NULL`, [dealId]);
    if (deals.length === 0) {
      return { evidence: [] };
    }

    const [hasId, hasEvidenceId, hasDocumentId, hasConfidence, hasVisualAssetId] = await Promise.all([
      hasColumn(pool as unknown as PoolLike, "evidence", "id"),
      hasColumn(pool as unknown as PoolLike, "evidence", "evidence_id"),
      hasColumn(pool as unknown as PoolLike, "evidence", "document_id"),
      hasColumn(pool as unknown as PoolLike, "evidence", "confidence"),
      hasColumn(pool as unknown as PoolLike, "evidence", "visual_asset_id"),
    ]);

    const idExpr = hasId ? "id" : hasEvidenceId ? "evidence_id" : "id";
    const documentIdExpr = hasDocumentId ? "document_id" : "NULL::text AS document_id";
    const confidenceExpr = hasConfidence ? "confidence::float8 AS confidence" : "NULL::float8 AS confidence";
    const visualAssetIdExpr = hasVisualAssetId ? "visual_asset_id" : "NULL::text AS visual_asset_id";

    const { rows } = await pool.query(
      `SELECT ${idExpr} as id,
              deal_id,
              ${documentIdExpr},
              ${visualAssetIdExpr},
              source,
              kind,
              text,
              ${confidenceExpr},
              created_at
       FROM evidence
       WHERE deal_id = $1
       ORDER BY created_at DESC
       LIMIT 50`,
      [dealId]
    );

    const endTs = Date.now();
    request.log.info({
      msg: "deal.evidence.done",
      deal_id: dealId,
      count: rows.length,
      start_ts: new Date(startTs).toISOString(),
      end_ts: new Date(endTs).toISOString(),
      duration_ms: endTs - startTs,
    });

    return { evidence: rows.map((row) => ({
      id: row.id,
      deal_id: row.deal_id,
      document_id: row.document_id ?? undefined,
      visual_asset_id: (row as any).visual_asset_id ?? undefined,
      source: row.source,
      kind: row.kind,
      text: row.text,
      confidence: row.confidence ?? undefined,
      created_at: row.created_at,
    })) };
  });
}
