-- Platform access entitlement table.
-- Supports invite-only signup and time-limited access windows.
--
-- Access lifecycle:
--   pending  → user is created but not yet granted access (awaiting invite acceptance / admin approval)
--   active   → user has full platform access (optionally time-bounded via access_expires_at)
--   expired  → access_expires_at has passed (enforced by the API auth middleware)
--   revoked  → manually revoked by an admin at any time
--
-- Enforcement logic (apps/api/src/plugins/clerk-auth.ts):
--   1. No row for clerk_user_id → ACCESS_NOT_PROVISIONED (403)
--   2. access_status = 'pending' → ACCESS_PENDING (403)
--   3. access_status = 'revoked' → ACCESS_REVOKED (403)
--   4. access_status = 'expired' → ACCESS_EXPIRED (403)
--   5. access_status = 'active' but access_expires_at <= now() → ACCESS_EXPIRED (403)
--   6. access_status = 'active' and (access_expires_at IS NULL or > now()) → allow
--
-- Provisioning:
--   Use POST /api/v1/admin/platform-access (Phase 1 manual bootstrap)
--   Future: linked to invite codes generated by AEs.

BEGIN;

CREATE TABLE IF NOT EXISTS platform_access (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  clerk_user_id       TEXT        NOT NULL,
  org_id              TEXT        NULL,
  access_status       TEXT        NOT NULL DEFAULT 'pending'
                                  CHECK (access_status IN ('active', 'pending', 'expired', 'revoked')),
  access_expires_at   TIMESTAMPTZ NULL,
  granted_by_user_id  TEXT        NULL,
  grant_source        TEXT        NULL
                                  CHECK (grant_source IS NULL OR grant_source IN ('manual', 'invite', 'admin', 'system')),
  notes               TEXT        NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Primary lookup: auth middleware queries by Clerk user ID on every request.
CREATE UNIQUE INDEX IF NOT EXISTS idx_platform_access_clerk_user_id
  ON platform_access (clerk_user_id);

-- Support filtering active users by org.
CREATE INDEX IF NOT EXISTS idx_platform_access_org_id
  ON platform_access (org_id)
  WHERE org_id IS NOT NULL;

-- Support expiry sweeps (future scheduled job or cron).
CREATE INDEX IF NOT EXISTS idx_platform_access_expires_at
  ON platform_access (access_expires_at)
  WHERE access_expires_at IS NOT NULL AND access_status = 'active';

COMMIT;
