#!/usr/bin/env python3
"""
scripts/dev/split-deals-final.py
Final version of the deals.ts splitter with correct line boundaries.

Key findings from analysis:
- Lines 3702-3915: inner helpers (safeJsonValue, ocrSnippet, etc.) defined inside
  registerDealRoutes — used by segments AND ingestion → must go to _shared.ts
- Lines 10995-11091: StatusSummary types + helpers (mapAnalysisJobStatus, etc.)
  defined inside registerDealRoutes → must go to _shared.ts
- Lines 3546-3700: if(debugRoutesEnabled) block containing segments/features route
  → must start the segments module (NOT end the analysis module)
"""
import re, os, subprocess, sys

REPO = "/Users/ryanmorrow/Documents/Projects2025/DealDecisionAI"
SRC = os.path.join(REPO, "apps/api/src/routes/deals.ts")
OUT = os.path.join(REPO, "apps/api/src/routes/deals")

if os.path.exists(SRC):
    raw = open(SRC).read()
else:
    r = subprocess.run(["git","show","HEAD:apps/api/src/routes/deals.ts"],
        capture_output=True, text=True, cwd=REPO)
    if r.returncode != 0:
        print("ERROR: deals.ts not found")
        sys.exit(1)
    raw = r.stdout
    print("  Using git HEAD deals.ts")

os.makedirs(OUT, exist_ok=True)
lines = raw.splitlines()
print(f"  deals.ts: {len(lines)} lines")

def GL(s, e):
    """Get 1-based inclusive range as list of strings."""
    return lines[s-1:e]

def write_file(name, content):
    path = os.path.join(OUT, name)
    open(path, "w").write(content)
    print(f"  wrote deals/{name}")

# ─────────────────────────────────────────────────────────────────────────────
# _shared.ts: preamble + inner helpers (dedented) + StatusSummary block
# ─────────────────────────────────────────────────────────────────────────────

def xform_preamble(ln):
    """Transform a preamble line: fix import paths, add export."""
    ln = ln.replace('"../', '"../../')
    if re.match(r'^(async function |function |const |type |interface )', ln):
        ln = "export " + ln
    return ln

def dedent_and_export(lines_list):
    """Remove 2-space indent and add export to top-level decls."""
    result = []
    for ln in lines_list:
        # Remove exactly 2 leading spaces (the indent from registerDealRoutes body)
        if ln.startswith("  "):
            ln = ln[2:]
        # Add export to bare top-level declarations
        if re.match(r'^(async function |function |const |type |interface )', ln):
            ln = "export " + ln
        result.append(ln)
    return result

preamble = [xform_preamble(l) for l in GL(1, 2466)]

# Inner helpers group 1: segment-area helpers (3702-3915)
inner_helpers_1 = dedent_and_export(GL(3702, 3915))

# Inner helpers group 2: StatusSummary types + investor-insights helpers (10995-11091)
inner_helpers_2 = dedent_and_export(GL(10995, 11091))

shared_content = (
    "/**\n"
    " * apps/api/src/routes/deals/_shared.ts\n"
    " *\n"
    " * Shared types and helper functions for deal route sub-modules.\n"
    " * Contains:\n"
    " *   1. Original preamble (lines 1-2466)\n"
    " *   2. Inner helpers from registerDealRoutes body (3702-3915, 10995-11091)\n"
    " *\n"
    " * AUTO-GENERATED by scripts/dev/split-deals-final.py (PR12)\n"
    " */\n"
    + "\n".join(preamble) + "\n\n"
    + "// ── Inner helpers (originally defined inside registerDealRoutes) ──────────────\n"
    + "\n".join(inner_helpers_1) + "\n\n"
    + "// ── StatusSummary types + investor-insights helpers ──────────────────────────\n"
    + "\n".join(inner_helpers_2) + "\n"
)
write_file("_shared.ts", shared_content)

# ─────────────────────────────────────────────────────────────────────────────
# Module configuration
# ─────────────────────────────────────────────────────────────────────────────

BLOCKS = {
    # investor-insights: generate+regenerate (early) + GET+orchestrator+debug (late)
    "investor-insights": [(2493, 2652), (11092, 11343)],
    # deal-analysis: all 4 analysis routes (ends before if(debugRoutesEnabled) at 3546)
    "deal-analysis":     [(2653, 3545)],
    # deal-segments: if(debugRoutesEnabled) block (3546-3700) + other segment routes
    # (skips inner helpers 3702-3915 which go to _shared.ts)
    "deal-segments":     [(3546, 3700), (3916, 7593)],
    # deal-ingestion: draft, claim, auto-profile, confirm-profile, create, merge, visual-assets
    "deal-ingestion":    [(7594, 9094)],
    # deal-core: list, get, update, llm-phase, governed-llm, diagnostics, delete
    "deal-core":         [(9095, 9909)],
    # deal-operations: analyze, prepare, readiness, extract-visuals, deep-scan, etc.
    # (ends before StatusSummary types at 10995)
    "deal-operations":   [(9910, 10994)],
}

REGISTRATION_ORDER = [
    "investor-insights", "deal-analysis", "deal-segments",
    "deal-ingestion", "deal-core", "deal-operations",
]

FN = {
    "investor-insights": "registerInvestorInsightsRoutes",
    "deal-analysis":     "registerDealAnalysisRoutes",
    "deal-segments":     "registerDealSegmentsRoutes",
    "deal-ingestion":    "registerDealIngestionRoutes",
    "deal-core":         "registerDealCoreRoutes",
    "deal-operations":   "registerDealOperationsRoutes",
}

IMPORTS = """\
import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import { fetchPhaseBVisualsFromDb } from "../../lib/phaseb-visuals";
import { getUploadsRootDir } from "../../plugins/uploads-static";
import { getPool } from "../../lib/db";
import { resolveVisualAssetImageUriForApi } from "../../lib/visual-asset-image-uri";
import type { Deal } from "@dealdecision/contracts";
import type { JobStatus, JobType } from "@dealdecision/contracts";
import { QUEUE_NAMES } from "@dealdecision/core";
import { enqueueBullmqJob, enqueueJob, insertJobRow } from "../../services/jobs";
import { getQueues } from "../../lib/queue";
import { runIdempotentOperation } from "../../lib/jobs";
import { getStorageDriver } from "../../lib/storage-contract";
import { autoProgressDealStage } from "../../services/stageProgression";
import { updateDealPriority, updateAllDealPriorities } from "../../services/priorityClassification";
import { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";
import { getNodeEvidenceGateForDeal } from "../../services/nodeEvidenceGateForDeal";
import { normalizeDealName } from "../../lib/normalize-deal-name";
import { buildDocumentsDigest } from "../../lib/documents-digest";
import type { DocumentsDigestV1 } from "../../lib/documents-digest";
import { objectExistsInR2 } from "../../lib/r2";
import {
  purgeDealCascade,
  isPurgeDealNotFoundError,
  sanitizeText,
  getDocumentCapabilities,
  buildDealScoringInputV0FromLineage,
  getSegmentConfidenceThresholds,
  detectContentArchetypeTags,
  buildOrchestratorReportV1,
} from "@dealdecision/core";
import {
  BrandModel,
  PageInput,
  buildBrandModel,
  inferDocumentBrandName,
  inferSlideTitleForSlide,
  isLikelyGarbledSlideTitle,
  normalizePhrase,
} from "../../lib/slide-title";
import {
  buildClassificationText,
  buildSegmentFeatures,
  classifySegment,
  normalizeAnalystSegment,
  type AnalystSegment,
  type SegmentClassifierInput,
} from "../../lib/analyst-segment";
import {
  groupWordVisualAssetsByDocument,
  groupWordVisualAssetsByDocumentWithStats,
  type WordGroupingStats,
} from "../../lib/word-visual-grouping";
import { fetchPageUnderstandingReadinessForDeal } from "../../lib/deal-page-understanding-readiness";
import { ensureDocumentsReadyForAnalysis } from "../../lib/ensure-documents-ready-for-analysis";
import { getCanonicalFieldsForAI } from "../../lib/canonical-fields-for-ai";
import type {
  QueryResult,
  DealRoutesPool,
  DealRoutesClient,
  DealApiMode,
  AutoProfileDocRow,
  DealRow,
  DIOAggregateRow,
  ScoreBreakdownSectionKey,
  EvidenceRow,
  StatusSummaryAnalysis,
  StatusSummaryReport,
  StatusSummaryEvidenceGate,
  StatusSummary,
} from "./_shared";
import {
  hasTable,
  hasColumn,
  getColumnDataType,
  isUuid,
  stripEvidenceFromExecutiveSummary,
  stripEvidenceFromClaims,
  parseDealApiMode,
  bestEffortReadinessJobPresenceCheck,
  parseBoolQ,
  computeOcrV2CleanText,
  pickNonUnknownSegment,
  majorityNonUnknownSegment,
  isStructuredWordSectionAsset,
  structuredWordContentStats,
  isEmptyStructuredWordSectionAsset,
  computeDocHintSegmentByDocId,
  applyNeighborHintPropagationToAssets,
  buildDeterministicGroupCapturedText,
  extractStructuredWordTextForCue,
  inferStructuredWordCueSegment,
  requireDestructiveAuth,
  dealStageEnum,
  dealPriorityEnum,
  normalizeDealTrend,
  dealTrendEnum,
  dealCreateSchema,
  dealDraftCreateSchema,
  dealConfirmProfileSchema,
  sanitizeProfileValue,
  extractLabeledValue,
  isGenericCandidateName,
  deriveNameFromFilenameLike,
  extractCompanyFromEarlyText,
  computeAutoProfileFromDocuments,
  normalizeWarningsForPersistence,
  jsonbParam,
  dealUpdateSchema,
  llmPhaseModeEnum,
  parseNullableNumber,
  SCORE_BREAKDOWN_SECTION_ORDER,
  CLAIM_CATEGORY_SECTION_MAP,
  normalizeCategory,
  sectionForCategory,
  buildScoreBreakdownV1,
  collectEvidenceIdsFromClaims,
  getEvidenceByIds,
  getDocumentIndex,
  fetchEvidenceSamplesBySection,
  normalizeEvidenceSnippet,
  BUSINESS_MODEL_STRONG_REGEX,
  deriveSectionKeyFromClaim,
  ensureEvidenceLinksForClaims,
  buildPhase1ScoreEvidence,
  buildScoreEvidenceFromBreakdown,
  mapDeal,
  safeJsonValue,
  ocrSnippet,
  deriveStructuredSummary,
  cueRescueLowSignal,
  deriveBestExtractionConfidence,
  mapAnalysisJobStatus,
  mapReportRowStatus,
  maxIsoTs,
  buildStatusSummary,
} from "./_shared";
"""

PARAMS = """\
  app: FastifyInstance,
  pool: DealRoutesPool,
  enqueue: typeof enqueueJob,
  r2: { objectExistsInR2: typeof objectExistsInR2 },
  debugRoutesEnabled: boolean,
  deps?: {
    enqueueJob?: typeof enqueueJob;
    jobs?: { queue?: any };
    r2?: { objectExistsInR2?: typeof objectExistsInR2 };
    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };
  }"""

# ─────────────────────────────────────────────────────────────────────────────
# Build route module files
# ─────────────────────────────────────────────────────────────────────────────

for mk in REGISTRATION_ORDER:
    fn_name = FN[mk]
    body_parts = ["\n".join(GL(s, e)) for (s, e) in BLOCKS[mk]]
    body = "\n\n".join(body_parts)
    content = (
        f"/**\n * apps/api/src/routes/deals/{mk}.routes.ts\n"
        f" * {fn_name} — extracted from deals.ts (PR12)\n"
        f" * AUTO-GENERATED by scripts/dev/split-deals-final.py\n */\n"
        + IMPORTS + "\n"
        + f"export async function {fn_name}(\n{PARAMS}\n): Promise<void> {{\n"
        + body + "\n}\n"
    )
    write_file(f"{mk}.routes.ts", content)
    rc = len(re.findall(r"app\.(get|post|put|patch|delete)[<(]", content))
    expected = sum(1 for _ in [
        (2493, 2528) if mk=="investor-insights" else None,  # just count differently
    ])
    # Just count and verify
    expected_counts = {
        "investor-insights": 5, "deal-analysis": 4, "deal-segments": 4,
        "deal-ingestion": 7, "deal-core": 7, "deal-operations": 9,
    }
    exp = expected_counts[mk]
    status = "✓" if rc == exp else f"MISMATCH expected={exp}"
    print(f"    {mk}: {rc} routes {status}")

# ─────────────────────────────────────────────────────────────────────────────
# index.ts
# ─────────────────────────────────────────────────────────────────────────────

idx_imports = "\n".join(
    f'import {{ {FN[k]} }} from "./{k}.routes";' for k in REGISTRATION_ORDER
)
idx_calls = "\n".join(
    f"  await {FN[k]}(app, pool, enqueue, r2, debugRoutesEnabled, deps);" for k in REGISTRATION_ORDER
)

idx_content = (
    "/**\n * apps/api/src/routes/deals/index.ts\n"
    " * Orchestrator — same public surface as original deals.ts (PR12)\n"
    " * AUTO-GENERATED by scripts/dev/split-deals-final.py\n */\n\n"
    'import type { FastifyInstance } from "fastify";\n'
    'import { getPool } from "../../lib/db";\n'
    'import { enqueueJob } from "../../services/jobs";\n'
    'import { objectExistsInR2 } from "../../lib/r2";\n'
    'import type { DealRoutesPool } from "./_shared";\n\n'
    '// ── Public re-exports (preserve original deals.ts surface) ─────────────────\n'
    'export { computeNodeEvidenceGateV1 } from "../../services/nodeEvidenceGateV1";\n'
    'export type { QueryResult } from "./_shared";\n'
    'export { normalizeWarningsForPersistence, buildScoreBreakdownV1 } from "./_shared";\n\n'
    '// ── Sub-module imports ────────────────────────────────────────────────────────\n'
    + idx_imports + "\n\n"
    '// ── Main entry point ──────────────────────────────────────────────────────────\n\n'
    "export async function registerDealRoutes(\n"
    "  app: FastifyInstance,\n"
    "  poolOverride?: any,\n"
    "  deps?: {\n"
    "    enqueueJob?: typeof enqueueJob;\n"
    "    jobs?: { queue?: any };\n"
    "    r2?: { objectExistsInR2?: typeof objectExistsInR2 };\n"
    "    investorInsightsQueue?: { add: (name: string, data: unknown, opts?: unknown) => Promise<unknown> };\n"
    "  }\n"
    "): Promise<void> {\n"
    "  const pool = (poolOverride ?? getPool()) as DealRoutesPool;\n"
    "  const enqueue = deps?.enqueueJob ?? enqueueJob;\n"
    "  const r2 = deps?.r2 ?? { objectExistsInR2 };\n"
    "  const debugRoutesEnabled = process.env.DEBUG_ROUTES === \"1\" || process.env.NODE_ENV !== \"production\";\n\n"
    + idx_calls + "\n}\n"
)
write_file("index.ts", idx_content)
print("Done!")
